version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  ignore:
    # backoff is managed speakeasy when generating the SDK.
    - dependency-name: "github.com/cenkalti/backoff/*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
