# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.19.0"
# renovate: datasource=github-releases depName=vektra/mockery
mockery: "3.5.5"
# renovate: datasource=github-releases depName=vburenin/ifacemaker
ifacemaker: "1.3.0"
