# renovate: datasource=github-releases depName=kubernetes-sigs/controller-tools
controller-tools: "0.20.0"
# renovate: datasource=github-releases depName=vektra/mockery
mockery: "3.6.1"
# renovate: datasource=github-releases depName=vburenin/ifacemaker
ifacemaker: "1.3.0"
