// Code generated by ifacemaker; DO NOT EDIT.

package sdkkonnectgo

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
)

// AIGatewayConsumersSDK is a generated interface.
type AIGatewayConsumersSDK interface {
	// ListAiGatewayConsumers - List AI Gateway Consumers
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Returns a list of all consumers for the AI Gateway.
	ListAiGatewayConsumers(ctx context.Context, request operations.ListAiGatewayConsumersRequest, opts ...operations.Option) (*operations.ListAiGatewayConsumersResponse, error)
	// CreateAiGatewayConsumer - Create an AI Gateway Consumer
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Creates a new consumer for the AI Gateway.
	CreateAiGatewayConsumer(ctx context.Context, gatewayID string, createAIGatewayConsumerRequest components.CreateAIGatewayConsumerRequest, opts ...operations.Option) (*operations.CreateAiGatewayConsumerResponse, error)
	// ListAiGatewayConsumerCredentials - List AI Gateway Consumer Credentials
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Returns a list of all credentials for an AI Gateway consumer.
	ListAiGatewayConsumerCredentials(ctx context.Context, request operations.ListAiGatewayConsumerCredentialsRequest, opts ...operations.Option) (*operations.ListAiGatewayConsumerCredentialsResponse, error)
	// CreateAiGatewayConsumerCredential - Create an AI Gateway Consumer Credential
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Creates a new credential for an AI Gateway consumer.
	CreateAiGatewayConsumerCredential(ctx context.Context, request operations.CreateAiGatewayConsumerCredentialRequest, opts ...operations.Option) (*operations.CreateAiGatewayConsumerCredentialResponse, error)
	// GetAiGatewayConsumerCredential - Get an AI Gateway Consumer Credential
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Returns the details of a specific credential for an AI Gateway consumer.
	GetAiGatewayConsumerCredential(ctx context.Context, request operations.GetAiGatewayConsumerCredentialRequest, opts ...operations.Option) (*operations.GetAiGatewayConsumerCredentialResponse, error)
	// DeleteAiGatewayConsumerCredential - Delete an AI Gateway Consumer Credential
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Removes a specific credential for an AI Gateway consumer.
	DeleteAiGatewayConsumerCredential(ctx context.Context, request operations.DeleteAiGatewayConsumerCredentialRequest, opts ...operations.Option) (*operations.DeleteAiGatewayConsumerCredentialResponse, error)
	// GetAiGatewayConsumer - Get an AI Gateway Consumer
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Returns the details of a specific AI Gateway consumer.
	GetAiGatewayConsumer(ctx context.Context, gatewayID string, consumerIDOrName string, opts ...operations.Option) (*operations.GetAiGatewayConsumerResponse, error)
	// UpdateAiGatewayConsumer - Update an AI Gateway Consumer
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Updates the configuration of an existing AI Gateway consumer.
	UpdateAiGatewayConsumer(ctx context.Context, request operations.UpdateAiGatewayConsumerRequest, opts ...operations.Option) (*operations.UpdateAiGatewayConsumerResponse, error)
	// DeleteAiGatewayConsumer - Delete an AI Gateway Consumer
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Removes a specific AI Gateway consumer.
	DeleteAiGatewayConsumer(ctx context.Context, gatewayID string, consumerIDOrName string, opts ...operations.Option) (*operations.DeleteAiGatewayConsumerResponse, error)
	// ListAiGatewayConsumerGroupsForConsumer - List Consumer Groups a Consumer belongs to
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// List AI Gateway Consumer Groups an Consumer belongs to
	ListAiGatewayConsumerGroupsForConsumer(ctx context.Context, request operations.ListAiGatewayConsumerGroupsForConsumerRequest, opts ...operations.Option) (*operations.ListAiGatewayConsumerGroupsForConsumerResponse, error)
	// UpdateAiGatewayConsumerGroupsForConsumer - Updates Consumer Groups a Consumer belongs to
	// **Pre-release Endpoint**
	// This endpoint is currently in beta and is subject to change.
	//
	// Updates AI Gateway Consumer Groups a Consumer belongs to
	UpdateAiGatewayConsumerGroupsForConsumer(ctx context.Context, request operations.UpdateAiGatewayConsumerGroupsForConsumerRequest, opts ...operations.Option) (*operations.UpdateAiGatewayConsumerGroupsForConsumerResponse, error)
}
