// Code generated by ifacemaker; DO NOT EDIT.

package sdkkonnectgo

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
)

// AIGatewayVaultsSDK is a generated interface.
type AIGatewayVaultsSDK interface {
	// ListAiGatewayVaults - List AI Gateway Vaults
	// Returns a list of vaults associated with the AI Gateway.
	ListAiGatewayVaults(ctx context.Context, request operations.ListAiGatewayVaultsRequest, opts ...operations.Option) (*operations.ListAiGatewayVaultsResponse, error)
	// CreateAiGatewayVault - Create an AI Gateway Vault
	// Registers a new vault for the AI Gateway.
	CreateAiGatewayVault(ctx context.Context, gatewayID string, createAIGatewayVaultRequest components.CreateAIGatewayVaultRequest, opts ...operations.Option) (*operations.CreateAiGatewayVaultResponse, error)
	// GetAiGatewayVault - Get an AI Gateway Vault
	// Returns the details of a specific AI Gateway vault.
	GetAiGatewayVault(ctx context.Context, gatewayID string, vaultIDOrName string, opts ...operations.Option) (*operations.GetAiGatewayVaultResponse, error)
	// UpdateAiGatewayVault - Update an AI Gateway Vault
	// Updates the configuration of an existing AI Gateway vault.
	UpdateAiGatewayVault(ctx context.Context, request operations.UpdateAiGatewayVaultRequest, opts ...operations.Option) (*operations.UpdateAiGatewayVaultResponse, error)
	// DeleteAiGatewayVault - Delete an AI Gateway Vault
	// Removes a specific AI Gateway vault.
	DeleteAiGatewayVault(ctx context.Context, gatewayID string, vaultIDOrName string, opts ...operations.Option) (*operations.DeleteAiGatewayVaultResponse, error)
}
