// Code generated by ifacemaker; DO NOT EDIT.

package sdkkonnectgo

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/operations"
)

// CatalogServiceResourcesSDK is a generated interface.
type CatalogServiceResourcesSDK interface {
	// ListCatalogServiceResources - List Service Resources
	// Returns a paginated collection of resources mapped to a service.
	ListCatalogServiceResources(ctx context.Context, request operations.ListCatalogServiceResourcesRequest, opts ...operations.Option) (*operations.ListCatalogServiceResourcesResponse, error)
}
