// Code generated by ifacemaker; DO NOT EDIT.

package sdkkonnectgo

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
)

// DashboardsSDK is a generated interface.
type DashboardsSDK interface {
	// DashboardsList - List dashboards
	// Get a paginated list of dashboards that your account has access to.
	DashboardsList(ctx context.Context, request operations.DashboardsListRequest, opts ...operations.Option) (*operations.DashboardsListResponse, error)
	// DashboardsCreate - Create a new dashboard
	// Creates a new dashboard from the provided definition.
	DashboardsCreate(ctx context.Context, request components.DashboardUpdateRequest, opts ...operations.Option) (*operations.DashboardsCreateResponse, error)
	// DashboardsGet - Get a single dashboard
	// Get a dashboard that your account has access to.
	DashboardsGet(ctx context.Context, dashboardID string, opts ...operations.Option) (*operations.DashboardsGetResponse, error)
	// DashboardsUpdate - Update an existing dashboard
	// Update an existing dashboard, replacing its definition with the provided one.
	DashboardsUpdate(ctx context.Context, dashboardID string, dashboardUpdateRequest components.DashboardUpdateRequest, opts ...operations.Option) (*operations.DashboardsUpdateResponse, error)
	// DashboardsDelete - Delete an existing dashboard
	// Delete an existing dashboard.
	DashboardsDelete(ctx context.Context, dashboardID string, opts ...operations.Option) (*operations.DashboardsDeleteResponse, error)
}
