// Code generated by scripts/gentests. DO NOT EDIT.

package fields_test

import (
	"testing"

	"github.com/Kong/sdk-konnect-go/models/components"
)

func TestComponentsServiceFieldTypes(t *testing.T) {
	t.Parallel()

	var value components.Service
	var _ []string = value.CaCertificates
	var _ *components.ClientCertificate = value.ClientCertificate
	var _ *int64 = value.ConnectTimeout
	var _ *int64 = value.CreatedAt
	var _ *bool = value.Enabled
	var _ string = value.Host
	var _ *string = value.ID
	var _ *string = value.Name
	var _ *string = value.Path
	var _ *int64 = value.Port
	var _ *components.Protocol = value.Protocol
	var _ *int64 = value.ReadTimeout
	var _ *int64 = value.Retries
	var _ []string = value.Tags
	var _ *components.TLSSans = value.TLSSans
	var _ *bool = value.TLSVerify
	var _ *int64 = value.TLSVerifyDepth
	var _ *int64 = value.UpdatedAt
	var _ *string = value.URL
	var _ *int64 = value.WriteTimeout
}
