// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type CreateDegraphqlRouteWithServiceInWorkspaceRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// ID of the Service to lookup
	ServiceID string `pathParam:"style=simple,explode=false,name=ServiceId"`
	// The name of the workspace
	Workspace string `pathParam:"style=simple,explode=false,name=workspace"`
	// Description of new Degraphql_route for creation
	DegraphqlRouteWithoutParents components.DegraphqlRouteWithoutParents `request:"mediaType=application/json"`
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceRequest) GetControlPlaneID() string {
	if c == nil {
		return ""
	}
	return c.ControlPlaneID
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceRequest) GetServiceID() string {
	if c == nil {
		return ""
	}
	return c.ServiceID
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceRequest) GetWorkspace() string {
	if c == nil {
		return ""
	}
	return c.Workspace
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceRequest) GetDegraphqlRouteWithoutParents() components.DegraphqlRouteWithoutParents {
	if c == nil {
		return components.DegraphqlRouteWithoutParents{}
	}
	return c.DegraphqlRouteWithoutParents
}

type CreateDegraphqlRouteWithServiceInWorkspaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully created Degraphql_route
	DegraphqlRoute *components.DegraphqlRoute
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateDegraphqlRouteWithServiceInWorkspaceResponse) GetDegraphqlRoute() *components.DegraphqlRoute {
	if c == nil {
		return nil
	}
	return c.DegraphqlRoute
}
