// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 850ee610cc1a

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type CreateEventGatewayTLSTrustBundleRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The request schema for creating a TLS trust bundle.
	CreateTLSTrustBundleRequest components.CreateTLSTrustBundleRequest `request:"mediaType=application/json"`
}

func (c *CreateEventGatewayTLSTrustBundleRequest) GetGatewayID() string {
	if c == nil {
		return ""
	}
	return c.GatewayID
}

func (c *CreateEventGatewayTLSTrustBundleRequest) GetCreateTLSTrustBundleRequest() components.CreateTLSTrustBundleRequest {
	if c == nil {
		return components.CreateTLSTrustBundleRequest{}
	}
	return c.CreateTLSTrustBundleRequest
}

type CreateEventGatewayTLSTrustBundleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created
	TLSTrustBundle *components.TLSTrustBundle
}

func (c *CreateEventGatewayTLSTrustBundleResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateEventGatewayTLSTrustBundleResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateEventGatewayTLSTrustBundleResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateEventGatewayTLSTrustBundleResponse) GetTLSTrustBundle() *components.TLSTrustBundle {
	if c == nil {
		return nil
	}
	return c.TLSTrustBundle
}
