// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

var CreatePrivateDNSServerList = []string{
	"https://global.api.konghq.com/",
}

type CreatePrivateDNSRequest struct {
	// The network to operate on.
	NetworkID               string                             `pathParam:"style=simple,explode=false,name=networkId"`
	CreatePrivateDNSRequest components.CreatePrivateDNSRequest `request:"mediaType=application/json"`
}

func (c *CreatePrivateDNSRequest) GetNetworkID() string {
	if c == nil {
		return ""
	}
	return c.NetworkID
}

func (c *CreatePrivateDNSRequest) GetCreatePrivateDNSRequest() components.CreatePrivateDNSRequest {
	if c == nil {
		return components.CreatePrivateDNSRequest{}
	}
	return c.CreatePrivateDNSRequest
}

type CreatePrivateDNSResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Response format for creating a Private DNS.
	PrivateDNSResponse *components.PrivateDNSResponse
}

func (c *CreatePrivateDNSResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreatePrivateDNSResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreatePrivateDNSResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreatePrivateDNSResponse) GetPrivateDNSResponse() *components.PrivateDNSResponse {
	if c == nil {
		return nil
	}
	return c.PrivateDNSResponse
}
