// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9564808d0591

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type DashboardsListRequest struct {
	// The maximum number of items to include per page. The last page of a collection may include fewer items.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
	// Determines which page of the entities to retrieve.
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page[number]"`
	// Filters dashboards in the response.
	Filter *components.DashboardFilterParameters `queryParam:"style=deepObject,explode=true,name=filter"`
	Sort   *string                               `queryParam:"style=form,explode=true,name=sort"`
}

func (d *DashboardsListRequest) GetPageSize() *int64 {
	if d == nil {
		return nil
	}
	return d.PageSize
}

func (d *DashboardsListRequest) GetPageNumber() *int64 {
	if d == nil {
		return nil
	}
	return d.PageNumber
}

func (d *DashboardsListRequest) GetFilter() *components.DashboardFilterParameters {
	if d == nil {
		return nil
	}
	return d.Filter
}

func (d *DashboardsListRequest) GetSort() *string {
	if d == nil {
		return nil
	}
	return d.Sort
}

// DashboardsListResponseBody - List of dashboards
type DashboardsListResponseBody struct {
	// returns the pagination information
	Meta *components.PaginatedMeta      `json:"meta,omitempty"`
	Data []components.DashboardResponse `json:"data,omitempty"`
}

func (d *DashboardsListResponseBody) GetMeta() *components.PaginatedMeta {
	if d == nil {
		return nil
	}
	return d.Meta
}

func (d *DashboardsListResponseBody) GetData() []components.DashboardResponse {
	if d == nil {
		return nil
	}
	return d.Data
}

type DashboardsListResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of dashboards
	Object *DashboardsListResponseBody
}

func (d *DashboardsListResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DashboardsListResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DashboardsListResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DashboardsListResponse) GetObject() *DashboardsListResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
