// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteContextInterfaceSourceMappingRequest struct {
	// The ID of the Context Interface.
	InterfaceID string `pathParam:"style=simple,explode=false,name=interfaceId"`
	// The ID of the Context Interface Source Mapping.
	MappingID string `pathParam:"style=simple,explode=false,name=mappingId"`
}

func (d *DeleteContextInterfaceSourceMappingRequest) GetInterfaceID() string {
	if d == nil {
		return ""
	}
	return d.InterfaceID
}

func (d *DeleteContextInterfaceSourceMappingRequest) GetMappingID() string {
	if d == nil {
		return ""
	}
	return d.MappingID
}

type DeleteContextInterfaceSourceMappingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteContextInterfaceSourceMappingResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteContextInterfaceSourceMappingResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteContextInterfaceSourceMappingResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
