// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteAiGatewayConsumerGroupRequest struct {
	// The unique ID of the AI Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The unique ID of the AI Gateway Consumer Group.
	ConsumerGroupID string `pathParam:"style=simple,explode=false,name=consumerGroupId"`
}

func (d *DeleteAiGatewayConsumerGroupRequest) GetGatewayID() string {
	if d == nil {
		return ""
	}
	return d.GatewayID
}

func (d *DeleteAiGatewayConsumerGroupRequest) GetConsumerGroupID() string {
	if d == nil {
		return ""
	}
	return d.ConsumerGroupID
}

type DeleteAiGatewayConsumerGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DeleteAiGatewayConsumerGroupResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteAiGatewayConsumerGroupResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteAiGatewayConsumerGroupResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
