// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type FetchAPIVersionRequest struct {
	// The UUID API identifier
	APIID string `pathParam:"style=simple,explode=false,name=apiId"`
	// The API version identifier
	VersionID string `pathParam:"style=simple,explode=false,name=versionId"`
}

func (f *FetchAPIVersionRequest) GetAPIID() string {
	if f == nil {
		return ""
	}
	return f.APIID
}

func (f *FetchAPIVersionRequest) GetVersionID() string {
	if f == nil {
		return ""
	}
	return f.VersionID
}

type FetchAPIVersionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// API version (OpenAPI or AsyncAPI)
	APIVersionResponse *components.APIVersionResponse
}

func (f *FetchAPIVersionResponse) GetContentType() string {
	if f == nil {
		return ""
	}
	return f.ContentType
}

func (f *FetchAPIVersionResponse) GetStatusCode() int {
	if f == nil {
		return 0
	}
	return f.StatusCode
}

func (f *FetchAPIVersionResponse) GetRawResponse() *http.Response {
	if f == nil {
		return nil
	}
	return f.RawResponse
}

func (f *FetchAPIVersionResponse) GetAPIVersionResponse() *components.APIVersionResponse {
	if f == nil {
		return nil
	}
	return f.APIVersionResponse
}
