// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type GetAiGatewayModelProviderRequest struct {
	// The unique ID of the AI Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The unique ID or name of the AI Gateway model provider.
	ModelProviderIDOrName string `pathParam:"style=simple,explode=false,name=modelProviderIdOrName"`
}

func (g *GetAiGatewayModelProviderRequest) GetGatewayID() string {
	if g == nil {
		return ""
	}
	return g.GatewayID
}

func (g *GetAiGatewayModelProviderRequest) GetModelProviderIDOrName() string {
	if g == nil {
		return ""
	}
	return g.ModelProviderIDOrName
}

type GetAiGatewayModelProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A successful response returning an AI Gateway Model Provider.
	AIGatewayModelProvider *components.AIGatewayModelProvider
}

func (g *GetAiGatewayModelProviderResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAiGatewayModelProviderResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAiGatewayModelProviderResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProvider() *components.AIGatewayModelProvider {
	if g == nil {
		return nil
	}
	return g.AIGatewayModelProvider
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderAnthropic() *components.AIGatewayModelProviderAIGatewayModelProviderAnthropic {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderAnthropic
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderAzure() *components.AIGatewayModelProviderAIGatewayModelProviderAzure {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderAzure
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderBedrock() *components.AIGatewayModelProviderAIGatewayModelProviderBedrock {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderBedrock
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderCerebras() *components.AIGatewayModelProviderAIGatewayModelProviderCerebras {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderCerebras
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderCohere() *components.AIGatewayModelProviderAIGatewayModelProviderCohere {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderCohere
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderDashscope() *components.AIGatewayModelProviderAIGatewayModelProviderDashscope {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderDashscope
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderDatabricks() *components.AIGatewayModelProviderAIGatewayModelProviderDatabricks {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderDatabricks
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderDeepseek() *components.AIGatewayModelProviderAIGatewayModelProviderDeepseek {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderDeepseek
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderGemini() *components.AIGatewayModelProviderAIGatewayModelProviderGemini {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderGemini
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderHuggingface() *components.AIGatewayModelProviderAIGatewayModelProviderHuggingface {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderHuggingface
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderKimi() *components.AIGatewayModelProviderAIGatewayModelProviderKimi {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderKimi
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderLlama2() *components.AIGatewayModelProviderAIGatewayModelProviderLlama2 {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderLlama2
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderMistral() *components.AIGatewayModelProviderAIGatewayModelProviderMistral {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderMistral
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderOllama() *components.AIGatewayModelProviderAIGatewayModelProviderOllama {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderOllama
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderOpenai() *components.AIGatewayModelProviderAIGatewayModelProviderOpenai {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderOpenai
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderVercel() *components.AIGatewayModelProviderAIGatewayModelProviderVercel {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderVercel
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderVllm() *components.AIGatewayModelProviderAIGatewayModelProviderVllm {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderVllm
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderXai() *components.AIGatewayModelProviderAIGatewayModelProviderXai {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderXai
	}
	return nil
}

func (g *GetAiGatewayModelProviderResponse) GetAIGatewayModelProviderVertex() *components.AIGatewayModelProviderAIGatewayModelProviderVertex {
	if v := g.GetAIGatewayModelProvider(); v != nil {
		return v.AIGatewayModelProviderAIGatewayModelProviderVertex
	}
	return nil
}
