// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type GetInvoiceRequest struct {
	InvoiceID string `pathParam:"style=simple,explode=false,name=invoiceId"`
}

func (g *GetInvoiceRequest) GetInvoiceID() string {
	if g == nil {
		return ""
	}
	return g.InvoiceID
}

type GetInvoiceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invoice response.
	BillingInvoice *components.BillingInvoice
}

func (g *GetInvoiceResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetInvoiceResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetInvoiceResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetInvoiceResponse) GetBillingInvoice() *components.BillingInvoice {
	if g == nil {
		return nil
	}
	return g.BillingInvoice
}

func (g *GetInvoiceResponse) GetBillingInvoiceStandard() *components.BillingInvoiceStandard {
	if v := g.GetBillingInvoice(); v != nil {
		return v.BillingInvoiceStandard
	}
	return nil
}
