// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 56e4f2dfaed4

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type GetNotificationChannelRequest struct {
	NotificationChannelID string `pathParam:"style=simple,explode=false,name=notificationChannelId"`
}

func (g *GetNotificationChannelRequest) GetNotificationChannelID() string {
	if g == nil {
		return ""
	}
	return g.NotificationChannelID
}

type GetNotificationChannelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// NotificationChannel response.
	BillingNotificationChannel *components.BillingNotificationChannel
}

func (g *GetNotificationChannelResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetNotificationChannelResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetNotificationChannelResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetNotificationChannelResponse) GetBillingNotificationChannel() *components.BillingNotificationChannel {
	if g == nil {
		return nil
	}
	return g.BillingNotificationChannel
}
