// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e3750497c45d

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type GetPortalFormRequest struct {
	// ID of the portal.
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
	// ID of the portal form.
	FormID string `pathParam:"style=simple,explode=false,name=formId"`
}

func (g *GetPortalFormRequest) GetPortalID() string {
	if g == nil {
		return ""
	}
	return g.PortalID
}

func (g *GetPortalFormRequest) GetFormID() string {
	if g == nil {
		return ""
	}
	return g.FormID
}

type GetPortalFormResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A custom form belonging to a portal.
	CustomFormResponse *components.CustomFormResponse
}

func (g *GetPortalFormResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetPortalFormResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetPortalFormResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetPortalFormResponse) GetCustomFormResponse() *components.CustomFormResponse {
	if g == nil {
		return nil
	}
	return g.CustomFormResponse
}
