// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type ListPortalDeveloperTeamsRequest struct {
	// ID of the developer.
	DeveloperID string `pathParam:"style=simple,explode=false,name=developerId"`
	// ID of the portal.
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
	// The maximum number of items to include per page. The last page of a collection may include fewer items.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
	// Determines which page of the entities to retrieve.
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page[number]"`
}

func (l *ListPortalDeveloperTeamsRequest) GetDeveloperID() string {
	if l == nil {
		return ""
	}
	return l.DeveloperID
}

func (l *ListPortalDeveloperTeamsRequest) GetPortalID() string {
	if l == nil {
		return ""
	}
	return l.PortalID
}

func (l *ListPortalDeveloperTeamsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListPortalDeveloperTeamsRequest) GetPageNumber() *int64 {
	if l == nil {
		return nil
	}
	return l.PageNumber
}

type ListPortalDeveloperTeamsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A paginated list of teams in a portal.
	ListPortalTeamsResponse *components.ListPortalTeamsResponse
}

func (l *ListPortalDeveloperTeamsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPortalDeveloperTeamsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPortalDeveloperTeamsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPortalDeveloperTeamsResponse) GetListPortalTeamsResponse() *components.ListPortalTeamsResponse {
	if l == nil {
		return nil
	}
	return l.ListPortalTeamsResponse
}
