// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

// ListPortalIdpTeamGroupMappingsQueryParamFilter - Filter mappings by team ID or group name.
type ListPortalIdpTeamGroupMappingsQueryParamFilter struct {
	// Filters on the given string field value by exact match.
	TeamID *components.StringFieldEqualsFilter `queryParam:"name=team_id"`
	// Filters on the given string field value by exact match.
	Group *components.StringFieldEqualsFilter `queryParam:"name=group"`
}

func (l *ListPortalIdpTeamGroupMappingsQueryParamFilter) GetTeamID() *components.StringFieldEqualsFilter {
	if l == nil {
		return nil
	}
	return l.TeamID
}

func (l *ListPortalIdpTeamGroupMappingsQueryParamFilter) GetGroup() *components.StringFieldEqualsFilter {
	if l == nil {
		return nil
	}
	return l.Group
}

type ListPortalIdpTeamGroupMappingsRequest struct {
	// ID of the portal.
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
	// ID of the identity provider.
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The maximum number of items to include per page. The last page of a collection may include fewer items.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
	// Request the next page of data, starting with the item after this parameter.
	PageAfter *string `queryParam:"style=form,explode=true,name=page[after]"`
	// Request the next page of data, starting with the item before this parameter.
	PageBefore *string `queryParam:"style=form,explode=true,name=page[before]"`
	// Filter mappings by team ID or group name.
	Filter *ListPortalIdpTeamGroupMappingsQueryParamFilter `queryParam:"style=deepObject,explode=true,name=filter"`
}

func (l *ListPortalIdpTeamGroupMappingsRequest) GetPortalID() string {
	if l == nil {
		return ""
	}
	return l.PortalID
}

func (l *ListPortalIdpTeamGroupMappingsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListPortalIdpTeamGroupMappingsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListPortalIdpTeamGroupMappingsRequest) GetPageAfter() *string {
	if l == nil {
		return nil
	}
	return l.PageAfter
}

func (l *ListPortalIdpTeamGroupMappingsRequest) GetPageBefore() *string {
	if l == nil {
		return nil
	}
	return l.PageBefore
}

func (l *ListPortalIdpTeamGroupMappingsRequest) GetFilter() *ListPortalIdpTeamGroupMappingsQueryParamFilter {
	if l == nil {
		return nil
	}
	return l.Filter
}

type ListPortalIdpTeamGroupMappingsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A paginated collection of team group mappings.
	PortalIdpTeamGroupMappingCollectionResponse *components.PortalIdpTeamGroupMappingCollectionResponse
}

func (l *ListPortalIdpTeamGroupMappingsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPortalIdpTeamGroupMappingsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPortalIdpTeamGroupMappingsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPortalIdpTeamGroupMappingsResponse) GetPortalIdpTeamGroupMappingCollectionResponse() *components.PortalIdpTeamGroupMappingCollectionResponse {
	if l == nil {
		return nil
	}
	return l.PortalIdpTeamGroupMappingCollectionResponse
}
