// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b5b17fea7523

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type MoveCatalogServiceDocumentRequest struct {
	// The `id` of the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=serviceId"`
	// The `id` of the document.
	DocumentID                 string                                `pathParam:"style=simple,explode=false,name=documentId"`
	MoveDocumentRequestPayload components.MoveDocumentRequestPayload `request:"mediaType=application/json"`
}

func (m *MoveCatalogServiceDocumentRequest) GetServiceID() string {
	if m == nil {
		return ""
	}
	return m.ServiceID
}

func (m *MoveCatalogServiceDocumentRequest) GetDocumentID() string {
	if m == nil {
		return ""
	}
	return m.DocumentID
}

func (m *MoveCatalogServiceDocumentRequest) GetMoveDocumentRequestPayload() components.MoveDocumentRequestPayload {
	if m == nil {
		return components.MoveDocumentRequestPayload{}
	}
	return m.MoveDocumentRequestPayload
}

type MoveCatalogServiceDocumentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (m *MoveCatalogServiceDocumentResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MoveCatalogServiceDocumentResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MoveCatalogServiceDocumentResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}
