// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type MoveEventGatewayListenerPolicyRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the Event Gateway Listener.
	ListenerID string `pathParam:"style=simple,explode=false,name=eventGatewayListenerId"`
	// The UUID of the policy.
	PolicyID               string                            `pathParam:"style=simple,explode=false,name=policyId"`
	MoveEventGatewayPolicy components.MoveEventGatewayPolicy `request:"mediaType=application/json"`
}

func (m *MoveEventGatewayListenerPolicyRequest) GetGatewayID() string {
	if m == nil {
		return ""
	}
	return m.GatewayID
}

func (m *MoveEventGatewayListenerPolicyRequest) GetListenerID() string {
	if m == nil {
		return ""
	}
	return m.ListenerID
}

func (m *MoveEventGatewayListenerPolicyRequest) GetPolicyID() string {
	if m == nil {
		return ""
	}
	return m.PolicyID
}

func (m *MoveEventGatewayListenerPolicyRequest) GetMoveEventGatewayPolicy() components.MoveEventGatewayPolicy {
	if m == nil {
		return components.MoveEventGatewayPolicy{}
	}
	return m.MoveEventGatewayPolicy
}

type MoveEventGatewayListenerPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (m *MoveEventGatewayListenerPolicyResponse) GetContentType() string {
	if m == nil {
		return ""
	}
	return m.ContentType
}

func (m *MoveEventGatewayListenerPolicyResponse) GetStatusCode() int {
	if m == nil {
		return 0
	}
	return m.StatusCode
}

func (m *MoveEventGatewayListenerPolicyResponse) GetRawResponse() *http.Response {
	if m == nil {
		return nil
	}
	return m.RawResponse
}
