// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/metering"
	"net/http"
)

type QueryFeatureCostRequest struct {
	FeatureID         string                      `pathParam:"style=simple,explode=false,name=featureId"`
	MeterQueryRequest *metering.MeterQueryRequest `request:"mediaType=application/json"`
}

func (q *QueryFeatureCostRequest) GetFeatureID() string {
	if q == nil {
		return ""
	}
	return q.FeatureID
}

func (q *QueryFeatureCostRequest) GetMeterQueryRequest() *metering.MeterQueryRequest {
	if q == nil {
		return nil
	}
	return q.MeterQueryRequest
}

type QueryFeatureCostResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The request has succeeded.
	FeatureCostQueryResult *metering.FeatureCostQueryResult
}

func (q *QueryFeatureCostResponse) GetContentType() string {
	if q == nil {
		return ""
	}
	return q.ContentType
}

func (q *QueryFeatureCostResponse) GetStatusCode() int {
	if q == nil {
		return 0
	}
	return q.StatusCode
}

func (q *QueryFeatureCostResponse) GetRawResponse() *http.Response {
	if q == nil {
		return nil
	}
	return q.RawResponse
}

func (q *QueryFeatureCostResponse) GetFeatureCostQueryResult() *metering.FeatureCostQueryResult {
	if q == nil {
		return nil
	}
	return q.FeatureCostQueryResult
}
