// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type UpdateConfigStoreSecretRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Config Store identifier
	ConfigStoreID string `pathParam:"style=simple,explode=false,name=configStoreId"`
	// Config Store Secret key
	Key                     string                             `pathParam:"style=simple,explode=false,name=key"`
	UpdateConfigStoreSecret components.UpdateConfigStoreSecret `request:"mediaType=application/json"`
}

func (u *UpdateConfigStoreSecretRequest) GetControlPlaneID() string {
	if u == nil {
		return ""
	}
	return u.ControlPlaneID
}

func (u *UpdateConfigStoreSecretRequest) GetConfigStoreID() string {
	if u == nil {
		return ""
	}
	return u.ConfigStoreID
}

func (u *UpdateConfigStoreSecretRequest) GetKey() string {
	if u == nil {
		return ""
	}
	return u.Key
}

func (u *UpdateConfigStoreSecretRequest) GetUpdateConfigStoreSecret() components.UpdateConfigStoreSecret {
	if u == nil {
		return components.UpdateConfigStoreSecret{}
	}
	return u.UpdateConfigStoreSecret
}

type UpdateConfigStoreSecretResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Config Store Secret
	ConfigStoreSecret *components.ConfigStoreSecret
}

func (u *UpdateConfigStoreSecretResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateConfigStoreSecretResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateConfigStoreSecretResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateConfigStoreSecretResponse) GetConfigStoreSecret() *components.ConfigStoreSecret {
	if u == nil {
		return nil
	}
	return u.ConfigStoreSecret
}
