// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/Kong/sdk-konnect-go/models/components"
	"net/http"
)

type UpdateEventGatewayListenerPolicyRequest struct {
	// The UUID of your Gateway.
	GatewayID string `pathParam:"style=simple,explode=false,name=gatewayId"`
	// The ID of the Event Gateway Listener.
	ListenerID string `pathParam:"style=simple,explode=false,name=eventGatewayListenerId"`
	// The UUID of the policy.
	PolicyID string `pathParam:"style=simple,explode=false,name=policyId"`
	// The request schema for updating a listener policy.
	EventGatewayListenerPolicyUpdate components.EventGatewayListenerPolicyUpdate `request:"mediaType=application/json"`
}

func (u *UpdateEventGatewayListenerPolicyRequest) GetGatewayID() string {
	if u == nil {
		return ""
	}
	return u.GatewayID
}

func (u *UpdateEventGatewayListenerPolicyRequest) GetListenerID() string {
	if u == nil {
		return ""
	}
	return u.ListenerID
}

func (u *UpdateEventGatewayListenerPolicyRequest) GetPolicyID() string {
	if u == nil {
		return ""
	}
	return u.PolicyID
}

func (u *UpdateEventGatewayListenerPolicyRequest) GetEventGatewayListenerPolicyUpdate() components.EventGatewayListenerPolicyUpdate {
	if u == nil {
		return components.EventGatewayListenerPolicyUpdate{}
	}
	return u.EventGatewayListenerPolicyUpdate
}

func (u *UpdateEventGatewayListenerPolicyRequest) GetEventGatewayListenerPolicyUpdateTLSServer() *components.EventGatewayTLSListenerSensitiveDataAwarePolicy {
	return u.GetEventGatewayListenerPolicyUpdate().EventGatewayTLSListenerSensitiveDataAwarePolicy
}

func (u *UpdateEventGatewayListenerPolicyRequest) GetEventGatewayListenerPolicyUpdateForwardToVirtualCluster() *components.ForwardToVirtualClusterPolicy {
	return u.GetEventGatewayListenerPolicyUpdate().ForwardToVirtualClusterPolicy
}

type UpdateEventGatewayListenerPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated policy object.
	EventGatewayListenerPolicy *components.EventGatewayListenerPolicy
}

func (u *UpdateEventGatewayListenerPolicyResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateEventGatewayListenerPolicyResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateEventGatewayListenerPolicyResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateEventGatewayListenerPolicyResponse) GetEventGatewayListenerPolicy() *components.EventGatewayListenerPolicy {
	if u == nil {
		return nil
	}
	return u.EventGatewayListenerPolicy
}
