// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"net/http"
)

// KonnectCPLegacyConflictError - standard error
type KonnectCPLegacyConflictError struct {
	// A short summary of the problem.
	//
	Message *string `json:"message,omitempty"`
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response `json:"-"`
}

var _ error = &KonnectCPLegacyConflictError{}

func (e *KonnectCPLegacyConflictError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
