// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// AIGatewayDatastoreRef - A reference to an existing datastore
type AIGatewayDatastoreRef struct {
	// An immutable user-defined identifier for this resource.
	Name *string `json:"name,omitempty"`
}

func (a AIGatewayDatastoreRef) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayDatastoreRef) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayDatastoreRef) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}
