// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 32d5c6f951d0

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

type AIGatewayAllowACL struct {
	// List of Consumers, Consumer Groups, or Authenticated Groups that are permitted access.
	Allow []string `json:"allow"`
}

func (a AIGatewayAllowACL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayAllowACL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"allow"}); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayAllowACL) GetAllow() []string {
	if a == nil {
		return []string{}
	}
	return a.Allow
}
