// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0602dbea1cce

package components

import (
	"encoding/json"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

type AIGatewayMCPServerPassthroughListenerType string

const (
	AIGatewayMCPServerPassthroughListenerTypePassthroughListener AIGatewayMCPServerPassthroughListenerType = "passthrough-listener"
)

func (e AIGatewayMCPServerPassthroughListenerType) ToPointer() *AIGatewayMCPServerPassthroughListenerType {
	return &e
}
func (e *AIGatewayMCPServerPassthroughListenerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "passthrough-listener":
		*e = AIGatewayMCPServerPassthroughListenerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AIGatewayMCPServerPassthroughListenerType: %v", v)
	}
}

// AIGatewayMCPServerPassthroughListener - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
type AIGatewayMCPServerPassthroughListener struct {
	Type AIGatewayMCPServerPassthroughListenerType `json:"type"`
	// **Pre-release Feature**
	// This feature is currently in beta and is subject to change.
	//
	// Routing, logging, and server configuration for the MCP Server.
	Config AIGatewayMCPServerWithUpstreamConfig `json:"config"`
	// List of tools exposed by this MCP Server.
	Tools []AIGatewayMCPToolBase `json:"tools,omitempty"`
	// **Pre-release Feature**
	// This feature is currently in beta and is subject to change.
	Access *AIGatewayMCPServerBaseACLProperties `json:"access,omitempty"`
	// The display name for the MCP Server.
	DisplayName string `json:"display_name"`
	// **Pre-release Feature**
	// This feature is currently in beta and is subject to change.
	//
	// A user-defined unique identifier for this MCP server, used as a stable human-readable reference. This value is immutable after creation.
	Name string `json:"name"`
	// Whether the MCP Server is enabled.
	Enabled *bool `default:"true" json:"enabled"`
	// List of policy references.
	Policies []string `json:"policies,omitempty"`
	// Public labels store information about an entity that can be used for filtering a list of objects.
	//
	// Public labels are intended to store **PUBLIC** metadata.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels,omitempty"`
	// Stores information about what manages this entity, such as the tool or system responsible for its lifecycle (for example, `terraform`).
	//
	// Keys must be 1–63 characters long and start with an alphanumeric character.
	//
	ManagedBy            map[string]string `json:"managed_by,omitempty"`
	AdditionalProperties map[string]any    `additionalProperties:"true" json:"-"`
}

func (a AIGatewayMCPServerPassthroughListener) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayMCPServerPassthroughListener) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"type", "config", "display_name", "name"}); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayMCPServerPassthroughListener) GetType() AIGatewayMCPServerPassthroughListenerType {
	if a == nil {
		return AIGatewayMCPServerPassthroughListenerType("")
	}
	return a.Type
}

func (a *AIGatewayMCPServerPassthroughListener) GetConfig() AIGatewayMCPServerWithUpstreamConfig {
	if a == nil {
		return AIGatewayMCPServerWithUpstreamConfig{}
	}
	return a.Config
}

func (a *AIGatewayMCPServerPassthroughListener) GetTools() []AIGatewayMCPToolBase {
	if a == nil {
		return nil
	}
	return a.Tools
}

func (a *AIGatewayMCPServerPassthroughListener) GetAccess() *AIGatewayMCPServerBaseACLProperties {
	if a == nil {
		return nil
	}
	return a.Access
}

func (a *AIGatewayMCPServerPassthroughListener) GetAccessConsumer() *AIGatewayMCPServerBaseACLPropertiesConsumer {
	if v := a.GetAccess(); v != nil {
		return v.AIGatewayMCPServerBaseACLPropertiesConsumer
	}
	return nil
}

func (a *AIGatewayMCPServerPassthroughListener) GetAccessOauthAccessToken() *AIGatewayMCPServerBaseACLPropertiesOauth {
	if v := a.GetAccess(); v != nil {
		return v.AIGatewayMCPServerBaseACLPropertiesOauth
	}
	return nil
}

func (a *AIGatewayMCPServerPassthroughListener) GetDisplayName() string {
	if a == nil {
		return ""
	}
	return a.DisplayName
}

func (a *AIGatewayMCPServerPassthroughListener) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AIGatewayMCPServerPassthroughListener) GetEnabled() *bool {
	if a == nil {
		return nil
	}
	return a.Enabled
}

func (a *AIGatewayMCPServerPassthroughListener) GetPolicies() []string {
	if a == nil {
		return nil
	}
	return a.Policies
}

func (a *AIGatewayMCPServerPassthroughListener) GetLabels() map[string]string {
	if a == nil {
		return nil
	}
	return a.Labels
}

func (a *AIGatewayMCPServerPassthroughListener) GetManagedBy() map[string]string {
	if a == nil {
		return nil
	}
	return a.ManagedBy
}

func (a *AIGatewayMCPServerPassthroughListener) GetAdditionalProperties() map[string]any {
	if a == nil {
		return nil
	}
	return a.AdditionalProperties
}
