// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ea8bda6e64d9

package components

// AIGatewayAgentAccess - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
//
// Access control configuration for an agent.
type AIGatewayAgentAccess struct {
	// **Pre-release Feature**
	// This feature is currently in beta and is subject to change.
	//
	// Access control rules. Configure exactly one of `allow` or `deny`.
	Acls *AIGatewayACLS `json:"acls,omitempty"`
}

func (a *AIGatewayAgentAccess) GetAcls() *AIGatewayACLS {
	if a == nil {
		return nil
	}
	return a.Acls
}
