// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

type AIGatewayTargetModelOllamaConfigType string

const (
	AIGatewayTargetModelOllamaConfigTypeOllama AIGatewayTargetModelOllamaConfigType = "ollama"
)

func (e AIGatewayTargetModelOllamaConfigType) ToPointer() *AIGatewayTargetModelOllamaConfigType {
	return &e
}
func (e *AIGatewayTargetModelOllamaConfigType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ollama":
		*e = AIGatewayTargetModelOllamaConfigType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AIGatewayTargetModelOllamaConfigType: %v", v)
	}
}

// AIGatewayTargetModelOllamaConfig - Ollama-specific configuration for a model.
type AIGatewayTargetModelOllamaConfig struct {
	// The number of dimensions for embedding outputs.
	EmbeddingsDimensions *int64 `json:"embeddings_dimensions,omitempty"`
	// The maximum number of tokens to generate in the response.
	MaxTokens *int64 `json:"max_tokens,omitempty"`
	// Cost per input token for billing and cost tracking.
	InputCost *float64 `json:"input_cost,omitempty"`
	// Cost per output token for billing and cost tracking.
	OutputCost *float64 `json:"output_cost,omitempty"`
	// Controls randomness in the model output. Higher values produce more varied responses.
	Temperature *float64 `json:"temperature,omitempty"`
	// Limits the number of highest-probability tokens considered during generation.
	TopK *int64 `json:"top_k,omitempty"`
	// Nucleus sampling probability mass. Tokens with cumulative probability up to top_p are considered.
	TopP *float64 `json:"top_p,omitempty"`
	// The upstream URL for the model endpoint.
	UpstreamURL *string                              `json:"upstream_url,omitempty"`
	Type        AIGatewayTargetModelOllamaConfigType `json:"type"`
}

func (a AIGatewayTargetModelOllamaConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AIGatewayTargetModelOllamaConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (a *AIGatewayTargetModelOllamaConfig) GetEmbeddingsDimensions() *int64 {
	if a == nil {
		return nil
	}
	return a.EmbeddingsDimensions
}

func (a *AIGatewayTargetModelOllamaConfig) GetMaxTokens() *int64 {
	if a == nil {
		return nil
	}
	return a.MaxTokens
}

func (a *AIGatewayTargetModelOllamaConfig) GetInputCost() *float64 {
	if a == nil {
		return nil
	}
	return a.InputCost
}

func (a *AIGatewayTargetModelOllamaConfig) GetOutputCost() *float64 {
	if a == nil {
		return nil
	}
	return a.OutputCost
}

func (a *AIGatewayTargetModelOllamaConfig) GetTemperature() *float64 {
	if a == nil {
		return nil
	}
	return a.Temperature
}

func (a *AIGatewayTargetModelOllamaConfig) GetTopK() *int64 {
	if a == nil {
		return nil
	}
	return a.TopK
}

func (a *AIGatewayTargetModelOllamaConfig) GetTopP() *float64 {
	if a == nil {
		return nil
	}
	return a.TopP
}

func (a *AIGatewayTargetModelOllamaConfig) GetUpstreamURL() *string {
	if a == nil {
		return nil
	}
	return a.UpstreamURL
}

func (a *AIGatewayTargetModelOllamaConfig) GetType() AIGatewayTargetModelOllamaConfigType {
	if a == nil {
		return AIGatewayTargetModelOllamaConfigType("")
	}
	return a.Type
}
