// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
	"time"
)

// BillingUsageBasedChargeType - The type of the charge.
type BillingUsageBasedChargeType string

const (
	BillingUsageBasedChargeTypeUsageBased BillingUsageBasedChargeType = "usage_based"
)

func (e BillingUsageBasedChargeType) ToPointer() *BillingUsageBasedChargeType {
	return &e
}
func (e *BillingUsageBasedChargeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "usage_based":
		*e = BillingUsageBasedChargeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingUsageBasedChargeType: %v", v)
	}
}

// BillingUsageBasedChargeCustomer - The customer owning the charge.
type BillingUsageBasedChargeCustomer struct {
	// The ID of the customer.
	ID string `json:"id"`
}

func (b BillingUsageBasedChargeCustomer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeCustomer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeCustomer) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

// BillingUsageBasedChargeManagedBy - The charge is managed by the following entity.
type BillingUsageBasedChargeManagedBy string

const (
	BillingUsageBasedChargeManagedByManual       BillingUsageBasedChargeManagedBy = "manual"
	BillingUsageBasedChargeManagedBySystem       BillingUsageBasedChargeManagedBy = "system"
	BillingUsageBasedChargeManagedBySubscription BillingUsageBasedChargeManagedBy = "subscription"
)

func (e BillingUsageBasedChargeManagedBy) ToPointer() *BillingUsageBasedChargeManagedBy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillingUsageBasedChargeManagedBy) IsExact() bool {
	if e != nil {
		switch *e {
		case "manual", "system", "subscription":
			return true
		}
	}
	return false
}

// BillingUsageBasedChargeItemID - The item of the phase.
type BillingUsageBasedChargeItemID struct {
	// The ID of the item.
	ID string `json:"id"`
}

func (b BillingUsageBasedChargeItemID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeItemID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeItemID) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

// BillingUsageBasedChargePhaseID - The phase of the subscription.
type BillingUsageBasedChargePhaseID struct {
	// The ID of the phase.
	ID string `json:"id"`
	// The item of the phase.
	Item BillingUsageBasedChargeItemID `json:"item"`
}

func (b BillingUsageBasedChargePhaseID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargePhaseID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "item"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargePhaseID) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BillingUsageBasedChargePhaseID) GetItem() BillingUsageBasedChargeItemID {
	if b == nil {
		return BillingUsageBasedChargeItemID{}
	}
	return b.Item
}

// BillingUsageBasedChargeSubscription - The subscription that originated the charge, when the charge was created from a
// subscription item.
type BillingUsageBasedChargeSubscription struct {
	// The ID of the subscription.
	ID string `json:"id"`
	// The phase of the subscription.
	Phase BillingUsageBasedChargePhaseID `json:"phase"`
}

func (b BillingUsageBasedChargeSubscription) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeSubscription) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "phase"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeSubscription) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BillingUsageBasedChargeSubscription) GetPhase() BillingUsageBasedChargePhaseID {
	if b == nil {
		return BillingUsageBasedChargePhaseID{}
	}
	return b.Phase
}

// BillingUsageBasedChargeStatus - The lifecycle status of the charge.
type BillingUsageBasedChargeStatus string

const (
	BillingUsageBasedChargeStatusCreated BillingUsageBasedChargeStatus = "created"
	BillingUsageBasedChargeStatusActive  BillingUsageBasedChargeStatus = "active"
	BillingUsageBasedChargeStatusFinal   BillingUsageBasedChargeStatus = "final"
	BillingUsageBasedChargeStatusDeleted BillingUsageBasedChargeStatus = "deleted"
)

func (e BillingUsageBasedChargeStatus) ToPointer() *BillingUsageBasedChargeStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillingUsageBasedChargeStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "created", "active", "final", "deleted":
			return true
		}
	}
	return false
}

// BillingUsageBasedChargeServicePeriod - The effective service period covered by the charge.
type BillingUsageBasedChargeServicePeriod struct {
	// The start of the period.
	//
	// The period is inclusive at the start.
	From time.Time `json:"from"`
	// The end of the period.
	//
	// The period is exclusive at the end.
	To time.Time `json:"to"`
}

func (b BillingUsageBasedChargeServicePeriod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeServicePeriod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"from", "to"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeServicePeriod) GetFrom() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.From
}

func (b *BillingUsageBasedChargeServicePeriod) GetTo() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.To
}

// BillingUsageBasedChargeFullServicePeriod - The full, unprorated service period of the charge.
type BillingUsageBasedChargeFullServicePeriod struct {
	// The start of the period.
	//
	// The period is inclusive at the start.
	From time.Time `json:"from"`
	// The end of the period.
	//
	// The period is exclusive at the end.
	To time.Time `json:"to"`
}

func (b BillingUsageBasedChargeFullServicePeriod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeFullServicePeriod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"from", "to"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeFullServicePeriod) GetFrom() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.From
}

func (b *BillingUsageBasedChargeFullServicePeriod) GetTo() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.To
}

// BillingUsageBasedChargeBillingPeriod - The billing period the charge belongs to.
type BillingUsageBasedChargeBillingPeriod struct {
	// The start of the period.
	//
	// The period is inclusive at the start.
	From time.Time `json:"from"`
	// The end of the period.
	//
	// The period is exclusive at the end.
	To time.Time `json:"to"`
}

func (b BillingUsageBasedChargeBillingPeriod) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeBillingPeriod) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"from", "to"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeBillingPeriod) GetFrom() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.From
}

func (b *BillingUsageBasedChargeBillingPeriod) GetTo() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.To
}

// BillingPriceVolumePriceBillingUsageBasedChargeType - The type of the price.
type BillingPriceVolumePriceBillingUsageBasedChargeType string

const (
	BillingPriceVolumePriceBillingUsageBasedChargeTypeVolume BillingPriceVolumePriceBillingUsageBasedChargeType = "volume"
)

func (e BillingPriceVolumePriceBillingUsageBasedChargeType) ToPointer() *BillingPriceVolumePriceBillingUsageBasedChargeType {
	return &e
}
func (e *BillingPriceVolumePriceBillingUsageBasedChargeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "volume":
		*e = BillingPriceVolumePriceBillingUsageBasedChargeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPriceVolumePriceBillingUsageBasedChargeType: %v", v)
	}
}

// BillingUsageBasedChargePriceBillingPriceVolume - Volume tiered price.
//
// The maximum quantity within a period determines the per-unit price for all units
// in that period.
//
// When UnitConfig is present on the rate card, tier boundaries (up_to_amount) are
// expressed in converted billing units.
type BillingUsageBasedChargePriceBillingPriceVolume struct {
	// The type of the price.
	Type BillingPriceVolumePriceBillingUsageBasedChargeType `json:"type"`
	// The tiers of the volume price. At least one tier is required.
	Tiers []BillingPriceTier `json:"tiers"`
}

func (b BillingUsageBasedChargePriceBillingPriceVolume) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargePriceBillingPriceVolume) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"type", "tiers"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargePriceBillingPriceVolume) GetType() BillingPriceVolumePriceBillingUsageBasedChargeType {
	if b == nil {
		return BillingPriceVolumePriceBillingUsageBasedChargeType("")
	}
	return b.Type
}

func (b *BillingUsageBasedChargePriceBillingPriceVolume) GetTiers() []BillingPriceTier {
	if b == nil {
		return []BillingPriceTier{}
	}
	return b.Tiers
}

// BillingPriceGraduatedPriceBillingUsageBasedChargeType - The type of the price.
type BillingPriceGraduatedPriceBillingUsageBasedChargeType string

const (
	BillingPriceGraduatedPriceBillingUsageBasedChargeTypeGraduated BillingPriceGraduatedPriceBillingUsageBasedChargeType = "graduated"
)

func (e BillingPriceGraduatedPriceBillingUsageBasedChargeType) ToPointer() *BillingPriceGraduatedPriceBillingUsageBasedChargeType {
	return &e
}
func (e *BillingPriceGraduatedPriceBillingUsageBasedChargeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "graduated":
		*e = BillingPriceGraduatedPriceBillingUsageBasedChargeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPriceGraduatedPriceBillingUsageBasedChargeType: %v", v)
	}
}

// BillingUsageBasedChargePriceBillingPriceGraduated - Graduated tiered price.
//
// Each tier's rate applies only to the usage within that tier. Pricing can change
// as cumulative usage crosses tier boundaries.
//
// When UnitConfig is present on the rate card, tier boundaries (up_to_amount) are
// expressed in converted billing units.
type BillingUsageBasedChargePriceBillingPriceGraduated struct {
	// The type of the price.
	Type BillingPriceGraduatedPriceBillingUsageBasedChargeType `json:"type"`
	// The tiers of the graduated price. At least one tier is required.
	Tiers []BillingPriceTier `json:"tiers"`
}

func (b BillingUsageBasedChargePriceBillingPriceGraduated) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargePriceBillingPriceGraduated) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"type", "tiers"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargePriceBillingPriceGraduated) GetType() BillingPriceGraduatedPriceBillingUsageBasedChargeType {
	if b == nil {
		return BillingPriceGraduatedPriceBillingUsageBasedChargeType("")
	}
	return b.Type
}

func (b *BillingUsageBasedChargePriceBillingPriceGraduated) GetTiers() []BillingPriceTier {
	if b == nil {
		return []BillingPriceTier{}
	}
	return b.Tiers
}

// BillingPriceUnitPriceBillingUsageBasedChargeType - The type of the price.
type BillingPriceUnitPriceBillingUsageBasedChargeType string

const (
	BillingPriceUnitPriceBillingUsageBasedChargeTypeUnit BillingPriceUnitPriceBillingUsageBasedChargeType = "unit"
)

func (e BillingPriceUnitPriceBillingUsageBasedChargeType) ToPointer() *BillingPriceUnitPriceBillingUsageBasedChargeType {
	return &e
}
func (e *BillingPriceUnitPriceBillingUsageBasedChargeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unit":
		*e = BillingPriceUnitPriceBillingUsageBasedChargeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPriceUnitPriceBillingUsageBasedChargeType: %v", v)
	}
}

// BillingUsageBasedChargePriceBillingPriceUnit - Unit price.
//
// Charges a fixed rate per billing unit. When UnitConfig is present on the rate
// card, billing units are the converted quantities (e.g. GB instead of bytes).
type BillingUsageBasedChargePriceBillingPriceUnit struct {
	// The type of the price.
	Type BillingPriceUnitPriceBillingUsageBasedChargeType `json:"type"`
	// The amount of the unit price.
	Amount string `json:"amount"`
}

func (b BillingUsageBasedChargePriceBillingPriceUnit) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargePriceBillingPriceUnit) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"type", "amount"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargePriceBillingPriceUnit) GetType() BillingPriceUnitPriceBillingUsageBasedChargeType {
	if b == nil {
		return BillingPriceUnitPriceBillingUsageBasedChargeType("")
	}
	return b.Type
}

func (b *BillingUsageBasedChargePriceBillingPriceUnit) GetAmount() string {
	if b == nil {
		return ""
	}
	return b.Amount
}

// BillingPriceFlatPriceBillingUsageBasedChargeType - The type of the price.
type BillingPriceFlatPriceBillingUsageBasedChargeType string

const (
	BillingPriceFlatPriceBillingUsageBasedChargeTypeFlat BillingPriceFlatPriceBillingUsageBasedChargeType = "flat"
)

func (e BillingPriceFlatPriceBillingUsageBasedChargeType) ToPointer() *BillingPriceFlatPriceBillingUsageBasedChargeType {
	return &e
}
func (e *BillingPriceFlatPriceBillingUsageBasedChargeType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "flat":
		*e = BillingPriceFlatPriceBillingUsageBasedChargeType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPriceFlatPriceBillingUsageBasedChargeType: %v", v)
	}
}

// BillingUsageBasedChargePriceBillingPriceFlat - Flat price.
type BillingUsageBasedChargePriceBillingPriceFlat struct {
	// The type of the price.
	Type BillingPriceFlatPriceBillingUsageBasedChargeType `json:"type"`
	// The amount of the flat price.
	Amount string `json:"amount"`
}

func (b BillingUsageBasedChargePriceBillingPriceFlat) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargePriceBillingPriceFlat) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"type", "amount"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargePriceBillingPriceFlat) GetType() BillingPriceFlatPriceBillingUsageBasedChargeType {
	if b == nil {
		return BillingPriceFlatPriceBillingUsageBasedChargeType("")
	}
	return b.Type
}

func (b *BillingUsageBasedChargePriceBillingPriceFlat) GetAmount() string {
	if b == nil {
		return ""
	}
	return b.Amount
}

// BillingPriceFreePriceType - The type of the price.
type BillingPriceFreePriceType string

const (
	BillingPriceFreePriceTypeFree BillingPriceFreePriceType = "free"
)

func (e BillingPriceFreePriceType) ToPointer() *BillingPriceFreePriceType {
	return &e
}
func (e *BillingPriceFreePriceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "free":
		*e = BillingPriceFreePriceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPriceFreePriceType: %v", v)
	}
}

// BillingUsageBasedChargePriceBillingPriceFree - Free price.
type BillingUsageBasedChargePriceBillingPriceFree struct {
	// The type of the price.
	Type BillingPriceFreePriceType `json:"type"`
}

func (b BillingUsageBasedChargePriceBillingPriceFree) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargePriceBillingPriceFree) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargePriceBillingPriceFree) GetType() BillingPriceFreePriceType {
	if b == nil {
		return BillingPriceFreePriceType("")
	}
	return b.Type
}

type BillingUsageBasedChargePriceType string

const (
	BillingUsageBasedChargePriceTypeFree      BillingUsageBasedChargePriceType = "free"
	BillingUsageBasedChargePriceTypeFlat      BillingUsageBasedChargePriceType = "flat"
	BillingUsageBasedChargePriceTypeUnit      BillingUsageBasedChargePriceType = "unit"
	BillingUsageBasedChargePriceTypeGraduated BillingUsageBasedChargePriceType = "graduated"
	BillingUsageBasedChargePriceTypeVolume    BillingUsageBasedChargePriceType = "volume"
)

// BillingUsageBasedChargePrice - The price of the charge.
type BillingUsageBasedChargePrice struct {
	BillingUsageBasedChargePriceBillingPriceFree      *BillingUsageBasedChargePriceBillingPriceFree      `queryParam:"inline" union:"member"`
	BillingUsageBasedChargePriceBillingPriceFlat      *BillingUsageBasedChargePriceBillingPriceFlat      `queryParam:"inline" union:"member"`
	BillingUsageBasedChargePriceBillingPriceUnit      *BillingUsageBasedChargePriceBillingPriceUnit      `queryParam:"inline" union:"member"`
	BillingUsageBasedChargePriceBillingPriceGraduated *BillingUsageBasedChargePriceBillingPriceGraduated `queryParam:"inline" union:"member"`
	BillingUsageBasedChargePriceBillingPriceVolume    *BillingUsageBasedChargePriceBillingPriceVolume    `queryParam:"inline" union:"member"`

	Type BillingUsageBasedChargePriceType
}

func CreateBillingUsageBasedChargePriceFree(free BillingUsageBasedChargePriceBillingPriceFree) BillingUsageBasedChargePrice {
	typ := BillingUsageBasedChargePriceTypeFree

	typStr := BillingPriceFreePriceType(typ)
	free.Type = typStr

	return BillingUsageBasedChargePrice{
		BillingUsageBasedChargePriceBillingPriceFree: &free,
		Type: typ,
	}
}

func CreateBillingUsageBasedChargePriceFlat(flat BillingUsageBasedChargePriceBillingPriceFlat) BillingUsageBasedChargePrice {
	typ := BillingUsageBasedChargePriceTypeFlat

	typStr := BillingPriceFlatPriceBillingUsageBasedChargeType(typ)
	flat.Type = typStr

	return BillingUsageBasedChargePrice{
		BillingUsageBasedChargePriceBillingPriceFlat: &flat,
		Type: typ,
	}
}

func CreateBillingUsageBasedChargePriceUnit(unit BillingUsageBasedChargePriceBillingPriceUnit) BillingUsageBasedChargePrice {
	typ := BillingUsageBasedChargePriceTypeUnit

	typStr := BillingPriceUnitPriceBillingUsageBasedChargeType(typ)
	unit.Type = typStr

	return BillingUsageBasedChargePrice{
		BillingUsageBasedChargePriceBillingPriceUnit: &unit,
		Type: typ,
	}
}

func CreateBillingUsageBasedChargePriceGraduated(graduated BillingUsageBasedChargePriceBillingPriceGraduated) BillingUsageBasedChargePrice {
	typ := BillingUsageBasedChargePriceTypeGraduated

	typStr := BillingPriceGraduatedPriceBillingUsageBasedChargeType(typ)
	graduated.Type = typStr

	return BillingUsageBasedChargePrice{
		BillingUsageBasedChargePriceBillingPriceGraduated: &graduated,
		Type: typ,
	}
}

func CreateBillingUsageBasedChargePriceVolume(volume BillingUsageBasedChargePriceBillingPriceVolume) BillingUsageBasedChargePrice {
	typ := BillingUsageBasedChargePriceTypeVolume

	typStr := BillingPriceVolumePriceBillingUsageBasedChargeType(typ)
	volume.Type = typStr

	return BillingUsageBasedChargePrice{
		BillingUsageBasedChargePriceBillingPriceVolume: &volume,
		Type: typ,
	}
}

func (u *BillingUsageBasedChargePrice) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "free":
		billingUsageBasedChargePriceBillingPriceFree := new(BillingUsageBasedChargePriceBillingPriceFree)
		if err := utils.UnmarshalJSON(data, &billingUsageBasedChargePriceBillingPriceFree, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == free) type BillingUsageBasedChargePriceBillingPriceFree within BillingUsageBasedChargePrice: %w", string(data), err)
		}

		u.BillingUsageBasedChargePriceBillingPriceFree = billingUsageBasedChargePriceBillingPriceFree
		u.Type = BillingUsageBasedChargePriceTypeFree
		return nil
	case "flat":
		billingUsageBasedChargePriceBillingPriceFlat := new(BillingUsageBasedChargePriceBillingPriceFlat)
		if err := utils.UnmarshalJSON(data, &billingUsageBasedChargePriceBillingPriceFlat, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == flat) type BillingUsageBasedChargePriceBillingPriceFlat within BillingUsageBasedChargePrice: %w", string(data), err)
		}

		u.BillingUsageBasedChargePriceBillingPriceFlat = billingUsageBasedChargePriceBillingPriceFlat
		u.Type = BillingUsageBasedChargePriceTypeFlat
		return nil
	case "unit":
		billingUsageBasedChargePriceBillingPriceUnit := new(BillingUsageBasedChargePriceBillingPriceUnit)
		if err := utils.UnmarshalJSON(data, &billingUsageBasedChargePriceBillingPriceUnit, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == unit) type BillingUsageBasedChargePriceBillingPriceUnit within BillingUsageBasedChargePrice: %w", string(data), err)
		}

		u.BillingUsageBasedChargePriceBillingPriceUnit = billingUsageBasedChargePriceBillingPriceUnit
		u.Type = BillingUsageBasedChargePriceTypeUnit
		return nil
	case "graduated":
		billingUsageBasedChargePriceBillingPriceGraduated := new(BillingUsageBasedChargePriceBillingPriceGraduated)
		if err := utils.UnmarshalJSON(data, &billingUsageBasedChargePriceBillingPriceGraduated, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == graduated) type BillingUsageBasedChargePriceBillingPriceGraduated within BillingUsageBasedChargePrice: %w", string(data), err)
		}

		u.BillingUsageBasedChargePriceBillingPriceGraduated = billingUsageBasedChargePriceBillingPriceGraduated
		u.Type = BillingUsageBasedChargePriceTypeGraduated
		return nil
	case "volume":
		billingUsageBasedChargePriceBillingPriceVolume := new(BillingUsageBasedChargePriceBillingPriceVolume)
		if err := utils.UnmarshalJSON(data, &billingUsageBasedChargePriceBillingPriceVolume, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == volume) type BillingUsageBasedChargePriceBillingPriceVolume within BillingUsageBasedChargePrice: %w", string(data), err)
		}

		u.BillingUsageBasedChargePriceBillingPriceVolume = billingUsageBasedChargePriceBillingPriceVolume
		u.Type = BillingUsageBasedChargePriceTypeVolume
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BillingUsageBasedChargePrice", string(data))
}

func (u BillingUsageBasedChargePrice) MarshalJSON() ([]byte, error) {
	if u.BillingUsageBasedChargePriceBillingPriceFree != nil {
		return utils.MarshalJSON(u.BillingUsageBasedChargePriceBillingPriceFree, "", true)
	}

	if u.BillingUsageBasedChargePriceBillingPriceFlat != nil {
		return utils.MarshalJSON(u.BillingUsageBasedChargePriceBillingPriceFlat, "", true)
	}

	if u.BillingUsageBasedChargePriceBillingPriceUnit != nil {
		return utils.MarshalJSON(u.BillingUsageBasedChargePriceBillingPriceUnit, "", true)
	}

	if u.BillingUsageBasedChargePriceBillingPriceGraduated != nil {
		return utils.MarshalJSON(u.BillingUsageBasedChargePriceBillingPriceGraduated, "", true)
	}

	if u.BillingUsageBasedChargePriceBillingPriceVolume != nil {
		return utils.MarshalJSON(u.BillingUsageBasedChargePriceBillingPriceVolume, "", true)
	}

	return nil, errors.New("could not marshal union type BillingUsageBasedChargePrice: all fields are null")
}

// BillingUsageBasedChargeSettlementMode - Settlement mode of the charge.
type BillingUsageBasedChargeSettlementMode string

const (
	BillingUsageBasedChargeSettlementModeCreditThenInvoice BillingUsageBasedChargeSettlementMode = "credit_then_invoice"
	BillingUsageBasedChargeSettlementModeCreditOnly        BillingUsageBasedChargeSettlementMode = "credit_only"
)

func (e BillingUsageBasedChargeSettlementMode) ToPointer() *BillingUsageBasedChargeSettlementMode {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillingUsageBasedChargeSettlementMode) IsExact() bool {
	if e != nil {
		switch *e {
		case "credit_then_invoice", "credit_only":
			return true
		}
	}
	return false
}

// BillingUsageBasedChargeTaxBehavior - Tax behavior.
//
// If not specified the billing profile is used to determine the tax behavior. If
// not specified in the billing profile, the provider's default behavior is used.
type BillingUsageBasedChargeTaxBehavior string

const (
	BillingUsageBasedChargeTaxBehaviorInclusive BillingUsageBasedChargeTaxBehavior = "inclusive"
	BillingUsageBasedChargeTaxBehaviorExclusive BillingUsageBasedChargeTaxBehavior = "exclusive"
)

func (e BillingUsageBasedChargeTaxBehavior) ToPointer() *BillingUsageBasedChargeTaxBehavior {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BillingUsageBasedChargeTaxBehavior) IsExact() bool {
	if e != nil {
		switch *e {
		case "inclusive", "exclusive":
			return true
		}
	}
	return false
}

// BillingUsageBasedChargeStripeTaxConfig - Stripe tax config.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type BillingUsageBasedChargeStripeTaxConfig struct {
	// Product [tax code](https://docs.stripe.com/tax/tax-codes).
	Code string `json:"code"`
}

func (b BillingUsageBasedChargeStripeTaxConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeStripeTaxConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"code"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeStripeTaxConfig) GetCode() string {
	if b == nil {
		return ""
	}
	return b.Code
}

// BillingUsageBasedChargeExternalInvoicingTaxConfig - External invoicing tax config.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type BillingUsageBasedChargeExternalInvoicingTaxConfig struct {
	// The tax code should be interpreted by the external invoicing provider.
	Code string `json:"code"`
}

func (b BillingUsageBasedChargeExternalInvoicingTaxConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeExternalInvoicingTaxConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"code"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeExternalInvoicingTaxConfig) GetCode() string {
	if b == nil {
		return ""
	}
	return b.Code
}

// BillingUsageBasedChargeTaxCode - Tax code reference.
//
// When both `tax_code` and `tax_code_id` are provided, `tax_code` takes
// precedence. When `stripe.code` is also provided, `tax_code` still wins and
// `stripe.code` is ignored.
type BillingUsageBasedChargeTaxCode struct {
	// ULID (Universally Unique Lexicographically Sortable Identifier).
	ID string `json:"id"`
}

func (b BillingUsageBasedChargeTaxCode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeTaxCode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeTaxCode) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

// BillingUsageBasedChargeTaxConfiguration - Tax configuration of the charge.
type BillingUsageBasedChargeTaxConfiguration struct {
	// Tax behavior.
	//
	// If not specified the billing profile is used to determine the tax behavior. If
	// not specified in the billing profile, the provider's default behavior is used.
	Behavior *BillingUsageBasedChargeTaxBehavior `json:"behavior,omitempty"`
	// Stripe tax config.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Stripe *BillingUsageBasedChargeStripeTaxConfig `json:"stripe,omitempty"`
	// External invoicing tax config.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ExternalInvoicing *BillingUsageBasedChargeExternalInvoicingTaxConfig `json:"external_invoicing,omitempty"`
	// Tax code ID.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TaxCodeID *string `json:"tax_code_id,omitempty"`
	// Tax code reference.
	//
	// When both `tax_code` and `tax_code_id` are provided, `tax_code` takes
	// precedence. When `stripe.code` is also provided, `tax_code` still wins and
	// `stripe.code` is ignored.
	TaxCode *BillingUsageBasedChargeTaxCode `json:"tax_code,omitempty"`
}

func (b BillingUsageBasedChargeTaxConfiguration) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeTaxConfiguration) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeTaxConfiguration) GetBehavior() *BillingUsageBasedChargeTaxBehavior {
	if b == nil {
		return nil
	}
	return b.Behavior
}

func (b *BillingUsageBasedChargeTaxConfiguration) GetStripe() *BillingUsageBasedChargeStripeTaxConfig {
	if b == nil {
		return nil
	}
	return b.Stripe
}

func (b *BillingUsageBasedChargeTaxConfiguration) GetExternalInvoicing() *BillingUsageBasedChargeExternalInvoicingTaxConfig {
	if b == nil {
		return nil
	}
	return b.ExternalInvoicing
}

func (b *BillingUsageBasedChargeTaxConfiguration) GetTaxCodeID() *string {
	if b == nil {
		return nil
	}
	return b.TaxCodeID
}

func (b *BillingUsageBasedChargeTaxConfiguration) GetTaxCode() *BillingUsageBasedChargeTaxCode {
	if b == nil {
		return nil
	}
	return b.TaxCode
}

// BillingUsageBasedChargeDiscounts - Discounts applied to the usage-based charge.
type BillingUsageBasedChargeDiscounts struct {
	// Percentage discount applied to the price (0–100).
	Percentage *float64 `json:"percentage,omitempty"`
	// Number of usage units granted free before billing starts. Only applies to
	// usage-based lines (not flat fees). Usage is treated as zero until this amount is
	// exhausted.
	Usage *string `json:"usage,omitempty"`
}

func (b BillingUsageBasedChargeDiscounts) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedChargeDiscounts) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedChargeDiscounts) GetPercentage() *float64 {
	if b == nil {
		return nil
	}
	return b.Percentage
}

func (b *BillingUsageBasedChargeDiscounts) GetUsage() *string {
	if b == nil {
		return nil
	}
	return b.Usage
}

// Booked - The amount of the charge already booked to the internal accounting system.
type Booked struct {
	// The total value of the resource before taxes, discounts and commitments.
	Amount string `json:"amount"`
	// The total tax amount applied to the resource.
	TaxesTotal string `json:"taxes_total"`
	// The total tax amount already included in the resource amount.
	TaxesInclusiveTotal string `json:"taxes_inclusive_total"`
	// The total tax amount added on top of the resource amount.
	TaxesExclusiveTotal string `json:"taxes_exclusive_total"`
	// The total amount contributed by additional charges.
	ChargesTotal string `json:"charges_total"`
	// The total amount deducted through discounts.
	DiscountsTotal string `json:"discounts_total"`
	// The total amount deducted through credits before taxes are applied.
	CreditsTotal string `json:"credits_total"`
	// The final total value of the resource after taxes, discounts and commitments.
	Total string `json:"total"`
}

func (b Booked) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Booked) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"amount", "taxes_total", "taxes_inclusive_total", "taxes_exclusive_total", "charges_total", "discounts_total", "credits_total", "total"}); err != nil {
		return err
	}
	return nil
}

func (b *Booked) GetAmount() string {
	if b == nil {
		return ""
	}
	return b.Amount
}

func (b *Booked) GetTaxesTotal() string {
	if b == nil {
		return ""
	}
	return b.TaxesTotal
}

func (b *Booked) GetTaxesInclusiveTotal() string {
	if b == nil {
		return ""
	}
	return b.TaxesInclusiveTotal
}

func (b *Booked) GetTaxesExclusiveTotal() string {
	if b == nil {
		return ""
	}
	return b.TaxesExclusiveTotal
}

func (b *Booked) GetChargesTotal() string {
	if b == nil {
		return ""
	}
	return b.ChargesTotal
}

func (b *Booked) GetDiscountsTotal() string {
	if b == nil {
		return ""
	}
	return b.DiscountsTotal
}

func (b *Booked) GetCreditsTotal() string {
	if b == nil {
		return ""
	}
	return b.CreditsTotal
}

func (b *Booked) GetTotal() string {
	if b == nil {
		return ""
	}
	return b.Total
}

// RealtimeTotals - The realtime amount of the charge.
//
// Requires the `realtime_usage` expand.
type RealtimeTotals struct {
	// The total value of the resource before taxes, discounts and commitments.
	Amount string `json:"amount"`
	// The total tax amount applied to the resource.
	TaxesTotal string `json:"taxes_total"`
	// The total tax amount already included in the resource amount.
	TaxesInclusiveTotal string `json:"taxes_inclusive_total"`
	// The total tax amount added on top of the resource amount.
	TaxesExclusiveTotal string `json:"taxes_exclusive_total"`
	// The total amount contributed by additional charges.
	ChargesTotal string `json:"charges_total"`
	// The total amount deducted through discounts.
	DiscountsTotal string `json:"discounts_total"`
	// The total amount deducted through credits before taxes are applied.
	CreditsTotal string `json:"credits_total"`
	// The final total value of the resource after taxes, discounts and commitments.
	Total string `json:"total"`
}

func (r RealtimeTotals) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RealtimeTotals) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"amount", "taxes_total", "taxes_inclusive_total", "taxes_exclusive_total", "charges_total", "discounts_total", "credits_total", "total"}); err != nil {
		return err
	}
	return nil
}

func (r *RealtimeTotals) GetAmount() string {
	if r == nil {
		return ""
	}
	return r.Amount
}

func (r *RealtimeTotals) GetTaxesTotal() string {
	if r == nil {
		return ""
	}
	return r.TaxesTotal
}

func (r *RealtimeTotals) GetTaxesInclusiveTotal() string {
	if r == nil {
		return ""
	}
	return r.TaxesInclusiveTotal
}

func (r *RealtimeTotals) GetTaxesExclusiveTotal() string {
	if r == nil {
		return ""
	}
	return r.TaxesExclusiveTotal
}

func (r *RealtimeTotals) GetChargesTotal() string {
	if r == nil {
		return ""
	}
	return r.ChargesTotal
}

func (r *RealtimeTotals) GetDiscountsTotal() string {
	if r == nil {
		return ""
	}
	return r.DiscountsTotal
}

func (r *RealtimeTotals) GetCreditsTotal() string {
	if r == nil {
		return ""
	}
	return r.CreditsTotal
}

func (r *RealtimeTotals) GetTotal() string {
	if r == nil {
		return ""
	}
	return r.Total
}

// TotalsForTheCharge - Aggregated booked and realtime totals for the charge.
type TotalsForTheCharge struct {
	// The amount of the charge already booked to the internal accounting system.
	Booked Booked `json:"booked"`
	// The realtime amount of the charge.
	//
	// Requires the `realtime_usage` expand.
	Realtime *RealtimeTotals `json:"realtime,omitempty"`
}

func (t TotalsForTheCharge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TotalsForTheCharge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"booked"}); err != nil {
		return err
	}
	return nil
}

func (t *TotalsForTheCharge) GetBooked() Booked {
	if t == nil {
		return Booked{}
	}
	return t.Booked
}

func (t *TotalsForTheCharge) GetRealtime() *RealtimeTotals {
	if t == nil {
		return nil
	}
	return t.Realtime
}

// BillingUsageBasedCharge - A usage-based charge for a customer.
type BillingUsageBasedCharge struct {
	// ULID (Universally Unique Lexicographically Sortable Identifier).
	ID string `json:"id"`
	// Display name of the resource.
	//
	// Between 1 and 256 characters.
	Name string `json:"name"`
	// Optional description of the resource.
	//
	// Maximum 1024 characters.
	Description *string `json:"description,omitempty"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels,omitempty"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// An ISO-8601 timestamp representation of entity last update date.
	UpdatedAt time.Time `json:"updated_at"`
	// An ISO-8601 timestamp representation of entity deletion date.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// The type of the charge.
	Type BillingUsageBasedChargeType `json:"type"`
	// The customer owning the charge.
	Customer BillingUsageBasedChargeCustomer `json:"customer"`
	// The charge is managed by the following entity.
	ManagedBy BillingUsageBasedChargeManagedBy `json:"managed_by"`
	// The subscription that originated the charge, when the charge was created from a
	// subscription item.
	Subscription *BillingUsageBasedChargeSubscription `json:"subscription,omitempty"`
	// The currency of the charge.
	Currency string `json:"currency"`
	// The lifecycle status of the charge.
	Status BillingUsageBasedChargeStatus `json:"status"`
	// The timestamp when the charge is intended to be invoiced.
	InvoiceAt time.Time `json:"invoice_at"`
	// The effective service period covered by the charge.
	ServicePeriod BillingUsageBasedChargeServicePeriod `json:"service_period"`
	// The full, unprorated service period of the charge.
	FullServicePeriod BillingUsageBasedChargeFullServicePeriod `json:"full_service_period"`
	// The billing period the charge belongs to.
	BillingPeriod BillingUsageBasedChargeBillingPeriod `json:"billing_period"`
	// The earliest time when the charge should be advanced again by background
	// processing.
	AdvanceAfter *time.Time `json:"advance_after,omitempty"`
	// The price of the charge.
	Price BillingUsageBasedChargePrice `json:"price"`
	// Unique reference ID of the charge.
	UniqueReferenceID *string `json:"unique_reference_id,omitempty"`
	// Settlement mode of the charge.
	SettlementMode BillingUsageBasedChargeSettlementMode `json:"settlement_mode"`
	// Tax configuration of the charge.
	TaxConfig *BillingUsageBasedChargeTaxConfiguration `json:"tax_config,omitempty"`
	// Discounts applied to the usage-based charge.
	Discounts *BillingUsageBasedChargeDiscounts `json:"discounts,omitempty"`
	// The feature associated with the charge.
	FeatureKey string `json:"feature_key"`
	// Aggregated booked and realtime totals for the charge.
	Totals TotalsForTheCharge `json:"totals"`
}

func (b BillingUsageBasedCharge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingUsageBasedCharge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "name", "created_at", "updated_at", "type", "customer", "managed_by", "currency", "status", "invoice_at", "service_period", "full_service_period", "billing_period", "price", "settlement_mode", "feature_key", "totals"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingUsageBasedCharge) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BillingUsageBasedCharge) GetName() string {
	if b == nil {
		return ""
	}
	return b.Name
}

func (b *BillingUsageBasedCharge) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *BillingUsageBasedCharge) GetLabels() map[string]string {
	if b == nil {
		return nil
	}
	return b.Labels
}

func (b *BillingUsageBasedCharge) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}

func (b *BillingUsageBasedCharge) GetUpdatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.UpdatedAt
}

func (b *BillingUsageBasedCharge) GetDeletedAt() *time.Time {
	if b == nil {
		return nil
	}
	return b.DeletedAt
}

func (b *BillingUsageBasedCharge) GetType() BillingUsageBasedChargeType {
	if b == nil {
		return BillingUsageBasedChargeType("")
	}
	return b.Type
}

func (b *BillingUsageBasedCharge) GetCustomer() BillingUsageBasedChargeCustomer {
	if b == nil {
		return BillingUsageBasedChargeCustomer{}
	}
	return b.Customer
}

func (b *BillingUsageBasedCharge) GetManagedBy() BillingUsageBasedChargeManagedBy {
	if b == nil {
		return BillingUsageBasedChargeManagedBy("")
	}
	return b.ManagedBy
}

func (b *BillingUsageBasedCharge) GetSubscription() *BillingUsageBasedChargeSubscription {
	if b == nil {
		return nil
	}
	return b.Subscription
}

func (b *BillingUsageBasedCharge) GetCurrency() string {
	if b == nil {
		return ""
	}
	return b.Currency
}

func (b *BillingUsageBasedCharge) GetStatus() BillingUsageBasedChargeStatus {
	if b == nil {
		return BillingUsageBasedChargeStatus("")
	}
	return b.Status
}

func (b *BillingUsageBasedCharge) GetInvoiceAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.InvoiceAt
}

func (b *BillingUsageBasedCharge) GetServicePeriod() BillingUsageBasedChargeServicePeriod {
	if b == nil {
		return BillingUsageBasedChargeServicePeriod{}
	}
	return b.ServicePeriod
}

func (b *BillingUsageBasedCharge) GetFullServicePeriod() BillingUsageBasedChargeFullServicePeriod {
	if b == nil {
		return BillingUsageBasedChargeFullServicePeriod{}
	}
	return b.FullServicePeriod
}

func (b *BillingUsageBasedCharge) GetBillingPeriod() BillingUsageBasedChargeBillingPeriod {
	if b == nil {
		return BillingUsageBasedChargeBillingPeriod{}
	}
	return b.BillingPeriod
}

func (b *BillingUsageBasedCharge) GetAdvanceAfter() *time.Time {
	if b == nil {
		return nil
	}
	return b.AdvanceAfter
}

func (b *BillingUsageBasedCharge) GetPrice() BillingUsageBasedChargePrice {
	if b == nil {
		return BillingUsageBasedChargePrice{}
	}
	return b.Price
}

func (b *BillingUsageBasedCharge) GetPriceFree() *BillingUsageBasedChargePriceBillingPriceFree {
	return b.GetPrice().BillingUsageBasedChargePriceBillingPriceFree
}

func (b *BillingUsageBasedCharge) GetPriceFlat() *BillingUsageBasedChargePriceBillingPriceFlat {
	return b.GetPrice().BillingUsageBasedChargePriceBillingPriceFlat
}

func (b *BillingUsageBasedCharge) GetPriceUnit() *BillingUsageBasedChargePriceBillingPriceUnit {
	return b.GetPrice().BillingUsageBasedChargePriceBillingPriceUnit
}

func (b *BillingUsageBasedCharge) GetPriceGraduated() *BillingUsageBasedChargePriceBillingPriceGraduated {
	return b.GetPrice().BillingUsageBasedChargePriceBillingPriceGraduated
}

func (b *BillingUsageBasedCharge) GetPriceVolume() *BillingUsageBasedChargePriceBillingPriceVolume {
	return b.GetPrice().BillingUsageBasedChargePriceBillingPriceVolume
}

func (b *BillingUsageBasedCharge) GetUniqueReferenceID() *string {
	if b == nil {
		return nil
	}
	return b.UniqueReferenceID
}

func (b *BillingUsageBasedCharge) GetSettlementMode() BillingUsageBasedChargeSettlementMode {
	if b == nil {
		return BillingUsageBasedChargeSettlementMode("")
	}
	return b.SettlementMode
}

func (b *BillingUsageBasedCharge) GetTaxConfig() *BillingUsageBasedChargeTaxConfiguration {
	if b == nil {
		return nil
	}
	return b.TaxConfig
}

func (b *BillingUsageBasedCharge) GetDiscounts() *BillingUsageBasedChargeDiscounts {
	if b == nil {
		return nil
	}
	return b.Discounts
}

func (b *BillingUsageBasedCharge) GetFeatureKey() string {
	if b == nil {
		return ""
	}
	return b.FeatureKey
}

func (b *BillingUsageBasedCharge) GetTotals() TotalsForTheCharge {
	if b == nil {
		return TotalsForTheCharge{}
	}
	return b.Totals
}
