// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

type BillingInvoiceLineType string

const (
	BillingInvoiceLineTypeStandardLine BillingInvoiceLineType = "standard_line"
)

// BillingInvoiceLine - A top-level line item on an invoice.
//
// Each line represents a single charge, typically associated with a rate card from
// a subscription. Detailed (child) lines are nested under `detailed_lines` when
// present.
type BillingInvoiceLine struct {
	BillingInvoiceStandardLine *BillingInvoiceStandardLine `queryParam:"inline" union:"member"`

	Type BillingInvoiceLineType
}

func CreateBillingInvoiceLineStandardLine(standardLine BillingInvoiceStandardLine) BillingInvoiceLine {
	typ := BillingInvoiceLineTypeStandardLine

	typStr := BillingInvoiceStandardLineType(typ)
	standardLine.Type = typStr

	return BillingInvoiceLine{
		BillingInvoiceStandardLine: &standardLine,
		Type:                       typ,
	}
}

func (u *BillingInvoiceLine) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "standard_line":
		billingInvoiceStandardLine := new(BillingInvoiceStandardLine)
		if err := utils.UnmarshalJSON(data, &billingInvoiceStandardLine, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == standard_line) type BillingInvoiceStandardLine within BillingInvoiceLine: %w", string(data), err)
		}

		u.BillingInvoiceStandardLine = billingInvoiceStandardLine
		u.Type = BillingInvoiceLineTypeStandardLine
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for BillingInvoiceLine", string(data))
}

func (u BillingInvoiceLine) MarshalJSON() ([]byte, error) {
	if u.BillingInvoiceStandardLine != nil {
		return utils.MarshalJSON(u.BillingInvoiceStandardLine, "", true)
	}

	return nil, errors.New("could not marshal union type BillingInvoiceLine: all fields are null")
}
