// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
	"time"
)

// BillingCostBasis - Describes currency basis supported by billing system.
type BillingCostBasis struct {
	// ULID (Universally Unique Lexicographically Sortable Identifier).
	ID string `json:"id"`
	// The fiat currency code for the cost basis.
	FiatCode string `json:"fiat_code"`
	// The cost rate for the currency.
	Rate string `json:"rate"`
	// An ISO-8601 timestamp representation of the date from which the cost basis is
	// effective. If not provided, it will be effective immediately and will be set to
	// `now` by the system.
	EffectiveFrom *time.Time `json:"effective_from,omitempty"`
	// An ISO-8601 timestamp representation of the date until which the cost basis is
	// effective. If provided, it must be later than `effective_from`. If not provided,
	// it remains effective until superseded.
	EffectiveTo *time.Time `json:"effective_to,omitempty"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
}

func (b BillingCostBasis) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BillingCostBasis) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, []string{"id", "fiat_code", "rate", "created_at"}); err != nil {
		return err
	}
	return nil
}

func (b *BillingCostBasis) GetID() string {
	if b == nil {
		return ""
	}
	return b.ID
}

func (b *BillingCostBasis) GetFiatCode() string {
	if b == nil {
		return ""
	}
	return b.FiatCode
}

func (b *BillingCostBasis) GetRate() string {
	if b == nil {
		return ""
	}
	return b.Rate
}

func (b *BillingCostBasis) GetEffectiveFrom() *time.Time {
	if b == nil {
		return nil
	}
	return b.EffectiveFrom
}

func (b *BillingCostBasis) GetEffectiveTo() *time.Time {
	if b == nil {
		return nil
	}
	return b.EffectiveTo
}

func (b *BillingCostBasis) GetCreatedAt() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.CreatedAt
}
