// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 18e29a516a4c

package components

// BulkPayload - Request body schema for bulk status update.
type BulkPayload struct {
	Ids []string `json:"ids"`
	// Status of the notification.
	Status NotificationStatus `json:"status"`
}

func (b *BulkPayload) GetIds() []string {
	if b == nil {
		return []string{}
	}
	return b.Ids
}

func (b *BulkPayload) GetStatus() NotificationStatus {
	if b == nil {
		return NotificationStatus("")
	}
	return b.Status
}
