// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

type CapabilityControlsType string

const (
	CapabilityControlsTypeAPI       CapabilityControlsType = "api"
	CapabilityControlsTypeMcpServer CapabilityControlsType = "mcp_server"
)

// CapabilityControls - The capabilities of a mapped MCP resource that the MCP server does not expose.
type CapabilityControls struct {
	APICapabilityControls *APICapabilityControls `queryParam:"inline" union:"member"`
	MCPCapabilityControls *MCPCapabilityControls `queryParam:"inline" union:"member"`

	Type CapabilityControlsType
}

func CreateCapabilityControlsAPI(api APICapabilityControls) CapabilityControls {
	typ := CapabilityControlsTypeAPI

	typStr := APICapabilityControlsType(typ)
	api.Type = typStr

	return CapabilityControls{
		APICapabilityControls: &api,
		Type:                  typ,
	}
}

func CreateCapabilityControlsMcpServer(mcpServer MCPCapabilityControls) CapabilityControls {
	typ := CapabilityControlsTypeMcpServer

	typStr := MCPCapabilityControlsType(typ)
	mcpServer.Type = typStr

	return CapabilityControls{
		MCPCapabilityControls: &mcpServer,
		Type:                  typ,
	}
}

func (u *CapabilityControls) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = CapabilityControls{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "api":
		apiCapabilityControls := new(APICapabilityControls)
		if err := utils.UnmarshalJSON(data, &apiCapabilityControls, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == api) type APICapabilityControls within CapabilityControls: %w", string(data), err)
		}

		u.APICapabilityControls = apiCapabilityControls
		u.Type = CapabilityControlsTypeAPI
		return nil
	case "mcp_server":
		mcpCapabilityControls := new(MCPCapabilityControls)
		if err := utils.UnmarshalJSON(data, &mcpCapabilityControls, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == mcp_server) type MCPCapabilityControls within CapabilityControls: %w", string(data), err)
		}

		u.MCPCapabilityControls = mcpCapabilityControls
		u.Type = CapabilityControlsTypeMcpServer
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CapabilityControls", string(data))
}

func (u CapabilityControls) MarshalJSON() ([]byte, error) {
	if u.APICapabilityControls != nil {
		return utils.MarshalJSON(u.APICapabilityControls, "", true)
	}

	if u.MCPCapabilityControls != nil {
		return utils.MarshalJSON(u.MCPCapabilityControls, "", true)
	}

	return nil, errors.New("could not marshal union type CapabilityControls: all fields are null")
}
