// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CatalogIntegrationResourceTypes struct {
	// The user-friendly resource type name.
	DisplayName *string      `json:"display_name,omitempty"`
	Schema      SimpleSchema `json:"schema"`
}

func (c *CatalogIntegrationResourceTypes) GetDisplayName() *string {
	if c == nil {
		return nil
	}
	return c.DisplayName
}

func (c *CatalogIntegrationResourceTypes) GetSchema() SimpleSchema {
	if c == nil {
		return SimpleSchema{}
	}
	return c.Schema
}
