// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// ControlPlaneReference - A control plane that implements an API
type ControlPlaneReference struct {
	// A Control plane that implements an API
	ControlPlane *APIImplementationControlPlaneInput `json:"control_plane,omitempty"`
}

func (c ControlPlaneReference) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ControlPlaneReference) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ControlPlaneReference) GetControlPlane() *APIImplementationControlPlaneInput {
	if c == nil {
		return nil
	}
	return c.ControlPlane
}
