// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: efe51107c2bb

package components

type CreateMCPServerRequest struct {
	// The machine name of the MCP server.
	Name string `json:"name"`
	// The human-readable display name of the MCP server.
	DisplayName string `json:"display_name"`
	// A description of the MCP server.
	Description string `json:"description"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels"`
}

func (c *CreateMCPServerRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateMCPServerRequest) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CreateMCPServerRequest) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateMCPServerRequest) GetLabels() map[string]string {
	if c == nil {
		return map[string]string{}
	}
	return c.Labels
}
