// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateSkillRequest struct {
	// The machine name of the skill. Must be unique within the MCP server and must match the name declared in the frontmatter.
	Name string `json:"name"`
	// The human-readable display name of the skill.
	DisplayName string `json:"display_name"`
	// A description of the skill.
	Description string `json:"description"`
	// Where the skill's content comes from, used in create and update requests. The shape of `config` is determined by `type`.
	Source SkillSourcePayload `json:"source"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels"`
}

func (c *CreateSkillRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSkillRequest) GetDisplayName() string {
	if c == nil {
		return ""
	}
	return c.DisplayName
}

func (c *CreateSkillRequest) GetDescription() string {
	if c == nil {
		return ""
	}
	return c.Description
}

func (c *CreateSkillRequest) GetSource() SkillSourcePayload {
	if c == nil {
		return SkillSourcePayload{}
	}
	return c.Source
}

func (c *CreateSkillRequest) GetSourceRaw() *RawSkillSourcePayload {
	return c.GetSource().RawSkillSourcePayload
}

func (c *CreateSkillRequest) GetLabels() map[string]string {
	if c == nil {
		return map[string]string{}
	}
	return c.Labels
}
