// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateMCPServerMCPResourceMappingRequest struct {
	// The ID of the Context Source to map to the Context Interface.
	ContextSourceID string `json:"context_source_id"`
}

func (c *CreateMCPServerMCPResourceMappingRequest) GetContextSourceID() string {
	if c == nil {
		return ""
	}
	return c.ContextSourceID
}
