// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

type CreateAPIVersionRequestProviderType string

const (
	CreateAPIVersionRequestProviderTypeURLAPISpecProvider                             CreateAPIVersionRequestProviderType = "UrlApiSpecProvider"
	CreateAPIVersionRequestProviderTypeIntegrationAPISpecProviderPayload              CreateAPIVersionRequestProviderType = "IntegrationApiSpecProviderPayload"
	CreateAPIVersionRequestProviderTypeResourceBoundIntegrationAPISpecProviderPayload CreateAPIVersionRequestProviderType = "ResourceBoundIntegrationApiSpecProviderPayload"
)

// CreateAPIVersionRequestProvider - Represent spec provider information used for fetching the API spec. For raw, provide the raw content in the `content` property instead of using this provider.
type CreateAPIVersionRequestProvider struct {
	URLAPISpecProvider                             *URLAPISpecProvider                             `queryParam:"inline" union:"member"`
	IntegrationAPISpecProviderPayload              *IntegrationAPISpecProviderPayload              `queryParam:"inline" union:"member"`
	ResourceBoundIntegrationAPISpecProviderPayload *ResourceBoundIntegrationAPISpecProviderPayload `queryParam:"inline" union:"member"`

	Type CreateAPIVersionRequestProviderType
}

func CreateCreateAPIVersionRequestProviderURLAPISpecProvider(urlAPISpecProvider URLAPISpecProvider) CreateAPIVersionRequestProvider {
	typ := CreateAPIVersionRequestProviderTypeURLAPISpecProvider

	return CreateAPIVersionRequestProvider{
		URLAPISpecProvider: &urlAPISpecProvider,
		Type:               typ,
	}
}

func CreateCreateAPIVersionRequestProviderIntegrationAPISpecProviderPayload(integrationAPISpecProviderPayload IntegrationAPISpecProviderPayload) CreateAPIVersionRequestProvider {
	typ := CreateAPIVersionRequestProviderTypeIntegrationAPISpecProviderPayload

	return CreateAPIVersionRequestProvider{
		IntegrationAPISpecProviderPayload: &integrationAPISpecProviderPayload,
		Type:                              typ,
	}
}

func CreateCreateAPIVersionRequestProviderResourceBoundIntegrationAPISpecProviderPayload(resourceBoundIntegrationAPISpecProviderPayload ResourceBoundIntegrationAPISpecProviderPayload) CreateAPIVersionRequestProvider {
	typ := CreateAPIVersionRequestProviderTypeResourceBoundIntegrationAPISpecProviderPayload

	return CreateAPIVersionRequestProvider{
		ResourceBoundIntegrationAPISpecProviderPayload: &resourceBoundIntegrationAPISpecProviderPayload,
		Type: typ,
	}
}

func (u *CreateAPIVersionRequestProvider) UnmarshalJSON(data []byte) error {

	var integrationAPISpecProviderPayload IntegrationAPISpecProviderPayload = IntegrationAPISpecProviderPayload{}
	if err := utils.UnmarshalJSON(data, &integrationAPISpecProviderPayload, "", true, nil); err == nil {
		u.IntegrationAPISpecProviderPayload = &integrationAPISpecProviderPayload
		u.Type = CreateAPIVersionRequestProviderTypeIntegrationAPISpecProviderPayload
		return nil
	}

	var urlAPISpecProvider URLAPISpecProvider = URLAPISpecProvider{}
	if err := utils.UnmarshalJSON(data, &urlAPISpecProvider, "", true, nil); err == nil {
		u.URLAPISpecProvider = &urlAPISpecProvider
		u.Type = CreateAPIVersionRequestProviderTypeURLAPISpecProvider
		return nil
	}

	var resourceBoundIntegrationAPISpecProviderPayload ResourceBoundIntegrationAPISpecProviderPayload = ResourceBoundIntegrationAPISpecProviderPayload{}
	if err := utils.UnmarshalJSON(data, &resourceBoundIntegrationAPISpecProviderPayload, "", true, nil); err == nil {
		u.ResourceBoundIntegrationAPISpecProviderPayload = &resourceBoundIntegrationAPISpecProviderPayload
		u.Type = CreateAPIVersionRequestProviderTypeResourceBoundIntegrationAPISpecProviderPayload
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateAPIVersionRequestProvider", string(data))
}

func (u CreateAPIVersionRequestProvider) MarshalJSON() ([]byte, error) {
	if u.URLAPISpecProvider != nil {
		return utils.MarshalJSON(u.URLAPISpecProvider, "", true)
	}

	if u.IntegrationAPISpecProviderPayload != nil {
		return utils.MarshalJSON(u.IntegrationAPISpecProviderPayload, "", true)
	}

	if u.ResourceBoundIntegrationAPISpecProviderPayload != nil {
		return utils.MarshalJSON(u.ResourceBoundIntegrationAPISpecProviderPayload, "", true)
	}

	return nil, errors.New("could not marshal union type CreateAPIVersionRequestProvider: all fields are null")
}

type CreateAPIVersionRequestSpec struct {
	// The raw content of API specification, in json or yaml format (OpenAPI or AsyncAPI).
	Content *string `json:"content,omitempty"`
	// Represent spec provider information used for fetching the API spec. For raw, provide the raw content in the `content` property instead of using this provider.
	//
	Provider *CreateAPIVersionRequestProvider `json:"provider,omitempty"`
}

func (c *CreateAPIVersionRequestSpec) GetContent() *string {
	if c == nil {
		return nil
	}
	return c.Content
}

func (c *CreateAPIVersionRequestSpec) GetProvider() *CreateAPIVersionRequestProvider {
	if c == nil {
		return nil
	}
	return c.Provider
}

type CreateAPIVersionRequest struct {
	// The version of the api.
	Version *string                     `json:"version,omitempty"`
	Spec    CreateAPIVersionRequestSpec `json:"spec"`
}

func (c *CreateAPIVersionRequest) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}

func (c *CreateAPIVersionRequest) GetSpec() CreateAPIVersionRequestSpec {
	if c == nil {
		return CreateAPIVersionRequestSpec{}
	}
	return c.Spec
}
