// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 27f37adeaffa

package components

// DeviceAuthorizationUserRequest - The request schema for the user device authorization request.
type DeviceAuthorizationUserRequest struct {
	// The end-user device verification code.
	UserCode string `json:"user_code"`
}

func (d *DeviceAuthorizationUserRequest) GetUserCode() string {
	if d == nil {
		return ""
	}
	return d.UserCode
}
