// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 57e15ce353ae

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// EventGatewayParsedRecordMaskFieldsConsumeConfig - The configuration of the mask parsed record fields consume policy.
type EventGatewayParsedRecordMaskFieldsConsumeConfig struct {
	// Describes how to handle a failure in a policy applied to consumed records.
	// * `error` - the batch is not delivered to the client. Use sparingly: erroring on a batch causes clients to get stuck on the problematic offset and requires manual intervention to skip it.
	// * `skip` - the record is not delivered to the client.
	// * `passthrough` - passes the record to the client even though policy execution failed.
	// * `mark` - passes the record to the client but marks it with a `kong/policy-failure-<id>` header whose value is the reason for the policy failure (truncated to 512 characters).
	//
	// **Requires a minimum runtime version of `1.2`**.
	FailureMode ConsumeFailureMode `json:"failure_mode"`
	// Selects which fields to mask and how to mask them.
	MaskFields []EventGatewayParsedRecordMaskSelector `json:"mask_fields"`
}

func (e EventGatewayParsedRecordMaskFieldsConsumeConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EventGatewayParsedRecordMaskFieldsConsumeConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"failure_mode", "mask_fields"}); err != nil {
		return err
	}
	return nil
}

func (e *EventGatewayParsedRecordMaskFieldsConsumeConfig) GetFailureMode() ConsumeFailureMode {
	if e == nil {
		return ConsumeFailureMode("")
	}
	return e.FailureMode
}

func (e *EventGatewayParsedRecordMaskFieldsConsumeConfig) GetMaskFields() []EventGatewayParsedRecordMaskSelector {
	if e == nil {
		return []EventGatewayParsedRecordMaskSelector{}
	}
	return e.MaskFields
}
