// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
	"time"
)

type GatewayNode struct {
	// The node ID.
	ID string `json:"id"`
	// The string representation of the node current version.
	Version string `json:"version"`
	// An ISO-8604 timestamp representation of node last seen date.
	LastSeenAt time.Time `json:"last_seen_at"`
	// An ISO-8604 timestamp representation of node creation date.
	CreatedAt time.Time `json:"created_at"`
	// An ISO-8604 timestamp representation of node update date.
	UpdatedAt time.Time `json:"updated_at"`
	// The time the node succeeds in applying the configuration.
	ConfigAppliedAt *time.Time `json:"config_applied_at,omitempty"`
	// The version number of the configuration applied by the node.
	ConfigVersion *string `json:"config_version,omitempty"`
}

func (g GatewayNode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GatewayNode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GatewayNode) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GatewayNode) GetVersion() string {
	if g == nil {
		return ""
	}
	return g.Version
}

func (g *GatewayNode) GetLastSeenAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.LastSeenAt
}

func (g *GatewayNode) GetCreatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.CreatedAt
}

func (g *GatewayNode) GetUpdatedAt() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.UpdatedAt
}

func (g *GatewayNode) GetConfigAppliedAt() *time.Time {
	if g == nil {
		return nil
	}
	return g.ConfigAppliedAt
}

func (g *GatewayNode) GetConfigVersion() *string {
	if g == nil {
		return nil
	}
	return g.ConfigVersion
}
