// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 71c5773d3812

package components

import (
	"encoding/json"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// Kv - The secrets engine version.
type Kv string

const (
	KvV1 Kv = "v1"
	KvV2 Kv = "v2"
)

func (e Kv) ToPointer() *Kv {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Kv) IsExact() bool {
	if e != nil {
		switch *e {
		case "v1", "v2":
			return true
		}
	}
	return false
}

// Protocol - The protocol to connect with.
type Protocol string

const (
	ProtocolHTTP  Protocol = "http"
	ProtocolHTTPS Protocol = "https"
)

func (e Protocol) ToPointer() *Protocol {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Protocol) IsExact() bool {
	if e != nil {
		switch *e {
		case "http", "https":
			return true
		}
	}
	return false
}

type AuthMethod string

const (
	AuthMethodToken AuthMethod = "token"
)

func (e AuthMethod) ToPointer() *AuthMethod {
	return &e
}
func (e *AuthMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "token":
		*e = AuthMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AuthMethod: %v", v)
	}
}

// HashiCorpVaultTokenConfigOutput - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
type HashiCorpVaultTokenConfigOutput struct {
	// Decode all secrets in this vault as base64. Useful for binary data.
	// If some of the secrets in the vault are not base64-encoded, an error will occur when using them.
	// We recommend creating a separate vault for base64 secrets.
	//
	Base64Decode *bool `json:"base64_decode,omitempty"`
	// Time-to-live (in seconds) for caching failed secret lookups.
	// A value of 0 disables negative caching. Kong will retry fetching the secret after neg_ttl expires.
	//
	NegTTL *int64 `json:"neg_ttl,omitempty"`
	// Time (in seconds) that secrets remain in use after expiration (config.ttl ends).
	// Useful if the vault is unreachable or the secret is deleted but not yet replaced.
	// Kong continues to retry for resurrect_ttl seconds before giving up.
	// The default is ~3 years to support uninterrupted service during outages.
	//
	ResurrectTTL *int64 `json:"resurrect_ttl,omitempty"`
	// Time-to-live (in seconds) for a cached secret. A value of 0 disables rotation.
	// For non-zero values, use a minimum of 60 seconds.
	//
	TTL *int64 `json:"ttl,omitempty"`
	// The hostname of your HashiCorp vault.
	Host string `json:"host"`
	// The port number of your HashiCorp vault.
	Port int64 `json:"port"`
	// The mount point.
	Mount string `json:"mount"`
	// The secrets engine version.
	Kv *Kv `json:"kv,omitempty"`
	// The protocol to connect with.
	Protocol *Protocol `json:"protocol,omitempty"`
	// Whether to verify the TLS certificate of the vault when connecting.
	SslVerify *bool `json:"ssl_verify,omitempty"`
	// Namespace for the Vault. Vault Enterprise requires a namespace to connect successfully.
	Namespace  *string    `json:"namespace,omitempty"`
	AuthMethod AuthMethod `json:"auth_method"`
}

func (h HashiCorpVaultTokenConfigOutput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HashiCorpVaultTokenConfigOutput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, []string{"host", "port", "mount", "auth_method"}); err != nil {
		return err
	}
	return nil
}

func (h *HashiCorpVaultTokenConfigOutput) GetBase64Decode() *bool {
	if h == nil {
		return nil
	}
	return h.Base64Decode
}

func (h *HashiCorpVaultTokenConfigOutput) GetNegTTL() *int64 {
	if h == nil {
		return nil
	}
	return h.NegTTL
}

func (h *HashiCorpVaultTokenConfigOutput) GetResurrectTTL() *int64 {
	if h == nil {
		return nil
	}
	return h.ResurrectTTL
}

func (h *HashiCorpVaultTokenConfigOutput) GetTTL() *int64 {
	if h == nil {
		return nil
	}
	return h.TTL
}

func (h *HashiCorpVaultTokenConfigOutput) GetHost() string {
	if h == nil {
		return ""
	}
	return h.Host
}

func (h *HashiCorpVaultTokenConfigOutput) GetPort() int64 {
	if h == nil {
		return 0
	}
	return h.Port
}

func (h *HashiCorpVaultTokenConfigOutput) GetMount() string {
	if h == nil {
		return ""
	}
	return h.Mount
}

func (h *HashiCorpVaultTokenConfigOutput) GetKv() *Kv {
	if h == nil {
		return nil
	}
	return h.Kv
}

func (h *HashiCorpVaultTokenConfigOutput) GetProtocol() *Protocol {
	if h == nil {
		return nil
	}
	return h.Protocol
}

func (h *HashiCorpVaultTokenConfigOutput) GetSslVerify() *bool {
	if h == nil {
		return nil
	}
	return h.SslVerify
}

func (h *HashiCorpVaultTokenConfigOutput) GetNamespace() *string {
	if h == nil {
		return nil
	}
	return h.Namespace
}

func (h *HashiCorpVaultTokenConfigOutput) GetAuthMethod() AuthMethod {
	if h == nil {
		return AuthMethod("")
	}
	return h.AuthMethod
}

// HashiCorpVaultTokenConfig - **Pre-release Feature**
// This feature is currently in beta and is subject to change.
type HashiCorpVaultTokenConfig struct {
	// Decode all secrets in this vault as base64. Useful for binary data.
	// If some of the secrets in the vault are not base64-encoded, an error will occur when using them.
	// We recommend creating a separate vault for base64 secrets.
	//
	Base64Decode *bool `json:"base64_decode,omitempty"`
	// Time-to-live (in seconds) for caching failed secret lookups.
	// A value of 0 disables negative caching. Kong will retry fetching the secret after neg_ttl expires.
	//
	NegTTL *int64 `json:"neg_ttl,omitempty"`
	// Time (in seconds) that secrets remain in use after expiration (config.ttl ends).
	// Useful if the vault is unreachable or the secret is deleted but not yet replaced.
	// Kong continues to retry for resurrect_ttl seconds before giving up.
	// The default is ~3 years to support uninterrupted service during outages.
	//
	ResurrectTTL *int64 `json:"resurrect_ttl,omitempty"`
	// Time-to-live (in seconds) for a cached secret. A value of 0 disables rotation.
	// For non-zero values, use a minimum of 60 seconds.
	//
	TTL *int64 `json:"ttl,omitempty"`
	// The hostname of your HashiCorp vault.
	Host string `json:"host"`
	// The port number of your HashiCorp vault.
	Port int64 `json:"port"`
	// The mount point.
	Mount string `json:"mount"`
	// The secrets engine version.
	Kv *Kv `json:"kv,omitempty"`
	// The protocol to connect with.
	Protocol *Protocol `json:"protocol,omitempty"`
	// Whether to verify the TLS certificate of the vault when connecting.
	SslVerify *bool `json:"ssl_verify,omitempty"`
	// Namespace for the Vault. Vault Enterprise requires a namespace to connect successfully.
	Namespace  *string    `json:"namespace,omitempty"`
	AuthMethod AuthMethod `json:"auth_method"`
	// The token string to be used for authentication.
	Token *string `json:"token,omitempty"`
}

func (h HashiCorpVaultTokenConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HashiCorpVaultTokenConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, []string{"host", "port", "mount", "auth_method"}); err != nil {
		return err
	}
	return nil
}

func (h *HashiCorpVaultTokenConfig) GetBase64Decode() *bool {
	if h == nil {
		return nil
	}
	return h.Base64Decode
}

func (h *HashiCorpVaultTokenConfig) GetNegTTL() *int64 {
	if h == nil {
		return nil
	}
	return h.NegTTL
}

func (h *HashiCorpVaultTokenConfig) GetResurrectTTL() *int64 {
	if h == nil {
		return nil
	}
	return h.ResurrectTTL
}

func (h *HashiCorpVaultTokenConfig) GetTTL() *int64 {
	if h == nil {
		return nil
	}
	return h.TTL
}

func (h *HashiCorpVaultTokenConfig) GetHost() string {
	if h == nil {
		return ""
	}
	return h.Host
}

func (h *HashiCorpVaultTokenConfig) GetPort() int64 {
	if h == nil {
		return 0
	}
	return h.Port
}

func (h *HashiCorpVaultTokenConfig) GetMount() string {
	if h == nil {
		return ""
	}
	return h.Mount
}

func (h *HashiCorpVaultTokenConfig) GetKv() *Kv {
	if h == nil {
		return nil
	}
	return h.Kv
}

func (h *HashiCorpVaultTokenConfig) GetProtocol() *Protocol {
	if h == nil {
		return nil
	}
	return h.Protocol
}

func (h *HashiCorpVaultTokenConfig) GetSslVerify() *bool {
	if h == nil {
		return nil
	}
	return h.SslVerify
}

func (h *HashiCorpVaultTokenConfig) GetNamespace() *string {
	if h == nil {
		return nil
	}
	return h.Namespace
}

func (h *HashiCorpVaultTokenConfig) GetAuthMethod() AuthMethod {
	if h == nil {
		return AuthMethod("")
	}
	return h.AuthMethod
}

func (h *HashiCorpVaultTokenConfig) GetToken() *string {
	if h == nil {
		return nil
	}
	return h.Token
}
