// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Icon struct {
	// The URL of the icon image. Must be an HTTPS URL.
	URL *string `json:"url,omitempty"`
}

func (i *Icon) GetURL() *string {
	if i == nil {
		return nil
	}
	return i.URL
}

type Images struct {
	Icon *Icon `json:"icon,omitempty"`
}

func (i *Images) GetIcon() *Icon {
	if i == nil {
		return nil
	}
	return i.Icon
}
