// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListPortalTeamsResponse - A paginated list of teams in a portal.
type ListPortalTeamsResponse struct {
	// returns the pagination information
	Meta PaginatedMeta        `json:"meta"`
	Data []PortalTeamResponse `json:"data"`
}

func (l *ListPortalTeamsResponse) GetMeta() PaginatedMeta {
	if l == nil {
		return PaginatedMeta{}
	}
	return l.Meta
}

func (l *ListPortalTeamsResponse) GetData() []PortalTeamResponse {
	if l == nil {
		return []PortalTeamResponse{}
	}
	return l.Data
}
