// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListMCPServersCPInfoResponse - A response to listing MCP servers with CP info.
type ListMCPServersCPInfoResponse struct {
	Data []MCPServerCPInfo `json:"data"`
	// Pagination metadata.
	Meta CursorMeta `json:"meta"`
}

func (l *ListMCPServersCPInfoResponse) GetData() []MCPServerCPInfo {
	if l == nil {
		return []MCPServerCPInfo{}
	}
	return l.Data
}

func (l *ListMCPServersCPInfoResponse) GetMeta() CursorMeta {
	if l == nil {
		return CursorMeta{}
	}
	return l.Meta
}
