// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListSuggestionRuleResponse - A paginated list response for a collection of suggestion rules.
type ListSuggestionRuleResponse struct {
	// returns the pagination information
	Meta PaginatedMeta    `json:"meta"`
	Data []SuggestionRule `json:"data"`
}

func (l *ListSuggestionRuleResponse) GetMeta() PaginatedMeta {
	if l == nil {
		return PaginatedMeta{}
	}
	return l.Meta
}

func (l *ListSuggestionRuleResponse) GetData() []SuggestionRule {
	if l == nil {
		return []SuggestionRule{}
	}
	return l.Data
}
