// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
	"time"
)

// StringFieldNEQFilter - Filter events by ID.
type StringFieldNEQFilter struct {
	Eq        *string `queryParam:"name=eq"`
	Contains  string  `queryParam:"name=contains"`
	Ocontains string  `queryParam:"name=ocontains"`
	Oeq       string  `queryParam:"name=oeq"`
	Neq       string  `queryParam:"name=neq"`
}

func (s *StringFieldNEQFilter) GetEq() *string {
	if s == nil {
		return nil
	}
	return s.Eq
}

func (s *StringFieldNEQFilter) GetContains() string {
	if s == nil {
		return ""
	}
	return s.Contains
}

func (s *StringFieldNEQFilter) GetOcontains() string {
	if s == nil {
		return ""
	}
	return s.Ocontains
}

func (s *StringFieldNEQFilter) GetOeq() string {
	if s == nil {
		return ""
	}
	return s.Oeq
}

func (s *StringFieldNEQFilter) GetNeq() string {
	if s == nil {
		return ""
	}
	return s.Neq
}

// ListEventsParamsFilterStringFieldNEQFilter - Filter events by source.
type ListEventsParamsFilterStringFieldNEQFilter struct {
	Eq        *string `queryParam:"name=eq"`
	Contains  string  `queryParam:"name=contains"`
	Ocontains string  `queryParam:"name=ocontains"`
	Oeq       string  `queryParam:"name=oeq"`
	Neq       string  `queryParam:"name=neq"`
}

func (l *ListEventsParamsFilterStringFieldNEQFilter) GetEq() *string {
	if l == nil {
		return nil
	}
	return l.Eq
}

func (l *ListEventsParamsFilterStringFieldNEQFilter) GetContains() string {
	if l == nil {
		return ""
	}
	return l.Contains
}

func (l *ListEventsParamsFilterStringFieldNEQFilter) GetOcontains() string {
	if l == nil {
		return ""
	}
	return l.Ocontains
}

func (l *ListEventsParamsFilterStringFieldNEQFilter) GetOeq() string {
	if l == nil {
		return ""
	}
	return l.Oeq
}

func (l *ListEventsParamsFilterStringFieldNEQFilter) GetNeq() string {
	if l == nil {
		return ""
	}
	return l.Neq
}

// ListEventsParamsFilterSubjectStringFieldNEQFilter - Filter events by subject.
type ListEventsParamsFilterSubjectStringFieldNEQFilter struct {
	Eq        *string `queryParam:"name=eq"`
	Contains  string  `queryParam:"name=contains"`
	Ocontains string  `queryParam:"name=ocontains"`
	Oeq       string  `queryParam:"name=oeq"`
	Neq       string  `queryParam:"name=neq"`
}

func (l *ListEventsParamsFilterSubjectStringFieldNEQFilter) GetEq() *string {
	if l == nil {
		return nil
	}
	return l.Eq
}

func (l *ListEventsParamsFilterSubjectStringFieldNEQFilter) GetContains() string {
	if l == nil {
		return ""
	}
	return l.Contains
}

func (l *ListEventsParamsFilterSubjectStringFieldNEQFilter) GetOcontains() string {
	if l == nil {
		return ""
	}
	return l.Ocontains
}

func (l *ListEventsParamsFilterSubjectStringFieldNEQFilter) GetOeq() string {
	if l == nil {
		return ""
	}
	return l.Oeq
}

func (l *ListEventsParamsFilterSubjectStringFieldNEQFilter) GetNeq() string {
	if l == nil {
		return ""
	}
	return l.Neq
}

// ListEventsParamsFilterTypeStringFieldNEQFilter - Filter events by type.
type ListEventsParamsFilterTypeStringFieldNEQFilter struct {
	Eq        *string `queryParam:"name=eq"`
	Contains  string  `queryParam:"name=contains"`
	Ocontains string  `queryParam:"name=ocontains"`
	Oeq       string  `queryParam:"name=oeq"`
	Neq       string  `queryParam:"name=neq"`
}

func (l *ListEventsParamsFilterTypeStringFieldNEQFilter) GetEq() *string {
	if l == nil {
		return nil
	}
	return l.Eq
}

func (l *ListEventsParamsFilterTypeStringFieldNEQFilter) GetContains() string {
	if l == nil {
		return ""
	}
	return l.Contains
}

func (l *ListEventsParamsFilterTypeStringFieldNEQFilter) GetOcontains() string {
	if l == nil {
		return ""
	}
	return l.Ocontains
}

func (l *ListEventsParamsFilterTypeStringFieldNEQFilter) GetOeq() string {
	if l == nil {
		return ""
	}
	return l.Oeq
}

func (l *ListEventsParamsFilterTypeStringFieldNEQFilter) GetNeq() string {
	if l == nil {
		return ""
	}
	return l.Neq
}

type ListEventsParamsFilterULIDFieldFilter2 struct {
	// Value strictly equals the given ULID value.
	Eq *string `queryParam:"name=eq"`
	// Returns entities that exact match any of the comma-delimited ULIDs in the filter
	// string.
	Oeq *string `queryParam:"name=oeq"`
	// Value does not equal the given ULID value.
	Neq *string `queryParam:"name=neq"`
}

func (l ListEventsParamsFilterULIDFieldFilter2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterULIDFieldFilter2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterULIDFieldFilter2) GetEq() *string {
	if l == nil {
		return nil
	}
	return l.Eq
}

func (l *ListEventsParamsFilterULIDFieldFilter2) GetOeq() *string {
	if l == nil {
		return nil
	}
	return l.Oeq
}

func (l *ListEventsParamsFilterULIDFieldFilter2) GetNeq() *string {
	if l == nil {
		return nil
	}
	return l.Neq
}

// #region class-body-listeventsparamsfilterulidfieldfilter2
// #endregion class-body-listeventsparamsfilterulidfieldfilter2

type ListEventsParamsFilterULIDFieldFilterType string

const (
	ListEventsParamsFilterULIDFieldFilterTypeStr                                    ListEventsParamsFilterULIDFieldFilterType = "str"
	ListEventsParamsFilterULIDFieldFilterTypeListEventsParamsFilterULIDFieldFilter2 ListEventsParamsFilterULIDFieldFilterType = "ListEventsParamsFilter_ULID Field Filter_2"
)

// ListEventsParamsFilterULIDFieldFilter - Filter events by the associated customer ID.
type ListEventsParamsFilterULIDFieldFilter struct {
	Str                                    *string                                 `queryParam:"inline" union:"member"`
	ListEventsParamsFilterULIDFieldFilter2 *ListEventsParamsFilterULIDFieldFilter2 `queryParam:"inline" union:"member"`

	Type ListEventsParamsFilterULIDFieldFilterType
}

func CreateListEventsParamsFilterULIDFieldFilterStr(str string) ListEventsParamsFilterULIDFieldFilter {
	typ := ListEventsParamsFilterULIDFieldFilterTypeStr

	return ListEventsParamsFilterULIDFieldFilter{
		Str:  &str,
		Type: typ,
	}
}

func CreateListEventsParamsFilterULIDFieldFilterListEventsParamsFilterULIDFieldFilter2(listEventsParamsFilterULIDFieldFilter2 ListEventsParamsFilterULIDFieldFilter2) ListEventsParamsFilterULIDFieldFilter {
	typ := ListEventsParamsFilterULIDFieldFilterTypeListEventsParamsFilterULIDFieldFilter2

	return ListEventsParamsFilterULIDFieldFilter{
		ListEventsParamsFilterULIDFieldFilter2: &listEventsParamsFilterULIDFieldFilter2,
		Type:                                   typ,
	}
}

func (u *ListEventsParamsFilterULIDFieldFilter) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = ListEventsParamsFilterULIDFieldFilterTypeStr
		return nil
	}

	var listEventsParamsFilterULIDFieldFilter2 ListEventsParamsFilterULIDFieldFilter2 = ListEventsParamsFilterULIDFieldFilter2{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterULIDFieldFilter2, "", true, nil); err == nil {
		u.ListEventsParamsFilterULIDFieldFilter2 = &listEventsParamsFilterULIDFieldFilter2
		u.Type = ListEventsParamsFilterULIDFieldFilterTypeListEventsParamsFilterULIDFieldFilter2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ListEventsParamsFilterULIDFieldFilter", string(data))
}

func (u ListEventsParamsFilterULIDFieldFilter) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ListEventsParamsFilterULIDFieldFilter2 != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterULIDFieldFilter2, "", true)
	}

	return nil, errors.New("could not marshal union type ListEventsParamsFilterULIDFieldFilter: all fields are null")
}

type ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter struct {
	// Value is greater than or equal to the given RFC-3339 formatted timestamp in UTC
	Gte time.Time `queryParam:"name=gte"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"gte"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter) GetGte() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Gte
}

type ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter struct {
	// Value is greater than the given RFC-3339 formatted timestamp in UTC
	Gt time.Time `queryParam:"name=gt"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"gt"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter) GetGt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Gt
}

type ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter struct {
	// Value is less than or equal to the given RFC-3339 formatted timestamp in UTC
	Lte time.Time `queryParam:"name=lte"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"lte"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter) GetLte() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Lte
}

type ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter struct {
	// Value is less than the given RFC-3339 formatted timestamp in UTC
	Lt time.Time `queryParam:"name=lt"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"lt"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter) GetLt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Lt
}

type ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter struct {
	// Value strictly equals given RFC-3339 formatted timestamp in UTC
	Eq time.Time `queryParam:"name=eq"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"eq"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter) GetEq() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Eq
}

type ListEventsParamsFilterDateTimeFieldFilterType string

const (
	ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_DateTimeFieldEqualsFilter"
	ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter     ListEventsParamsFilterDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_DateTimeFieldLTFilter"
	ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter    ListEventsParamsFilterDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_DateTimeFieldLTEFilter"
	ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter     ListEventsParamsFilterDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_DateTimeFieldGTFilter"
	ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter    ListEventsParamsFilterDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_DateTimeFieldGTEFilter"
)

// ListEventsParamsFilterDateTimeFieldFilter - Filter events by event time.
type ListEventsParamsFilterDateTimeFieldFilter struct {
	ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter     *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter     `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter    *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter    `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter     *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter     `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter    *ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter    `queryParam:"inline" union:"member"`

	Type ListEventsParamsFilterDateTimeFieldFilterType
}

func CreateListEventsParamsFilterDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter(listEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter) ListEventsParamsFilterDateTimeFieldFilter {
	typ := ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter

	return ListEventsParamsFilterDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter: &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter(listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter) ListEventsParamsFilterDateTimeFieldFilter {
	typ := ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter

	return ListEventsParamsFilterDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter: &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter(listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter) ListEventsParamsFilterDateTimeFieldFilter {
	typ := ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter

	return ListEventsParamsFilterDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter: &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter(listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter) ListEventsParamsFilterDateTimeFieldFilter {
	typ := ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter

	return ListEventsParamsFilterDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter: &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter(listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter) ListEventsParamsFilterDateTimeFieldFilter {
	typ := ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter

	return ListEventsParamsFilterDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter: &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter,
		Type: typ,
	}
}

func (u *ListEventsParamsFilterDateTimeFieldFilter) UnmarshalJSON(data []byte) error {

	var listEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter = ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter = &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter
		u.Type = ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter = ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter = &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter
		u.Type = ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter = ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter = &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter
		u.Type = ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter = ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter = &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter
		u.Type = ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter = ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter = &listEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter
		u.Type = ListEventsParamsFilterDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ListEventsParamsFilterDateTimeFieldFilter", string(data))
}

func (u ListEventsParamsFilterDateTimeFieldFilter) MarshalJSON() ([]byte, error) {
	if u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldEqualsFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldLTEFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterDateTimeFieldGTEFilter, "", true)
	}

	return nil, errors.New("could not marshal union type ListEventsParamsFilterDateTimeFieldFilter: all fields are null")
}

type ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter struct {
	// Value is greater than or equal to the given RFC-3339 formatted timestamp in UTC
	Gte time.Time `queryParam:"name=gte"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"gte"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter) GetGte() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Gte
}

type ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter struct {
	// Value is greater than the given RFC-3339 formatted timestamp in UTC
	Gt time.Time `queryParam:"name=gt"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"gt"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter) GetGt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Gt
}

type ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter struct {
	// Value is less than or equal to the given RFC-3339 formatted timestamp in UTC
	Lte time.Time `queryParam:"name=lte"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"lte"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter) GetLte() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Lte
}

type ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter struct {
	// Value is less than the given RFC-3339 formatted timestamp in UTC
	Lt time.Time `queryParam:"name=lt"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"lt"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter) GetLt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Lt
}

type ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter struct {
	// Value strictly equals given RFC-3339 formatted timestamp in UTC
	Eq time.Time `queryParam:"name=eq"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"eq"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter) GetEq() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Eq
}

type ListEventsParamsFilterIngestedAtDateTimeFieldFilterType string

const (
	ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter ListEventsParamsFilterIngestedAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_ingested_at_DateTimeFieldEqualsFilter"
	ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter     ListEventsParamsFilterIngestedAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_ingested_at_DateTimeFieldLTFilter"
	ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter    ListEventsParamsFilterIngestedAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_ingested_at_DateTimeFieldLTEFilter"
	ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter     ListEventsParamsFilterIngestedAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_ingested_at_DateTimeFieldGTFilter"
	ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter    ListEventsParamsFilterIngestedAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_ingested_at_DateTimeFieldGTEFilter"
)

// ListEventsParamsFilterIngestedAtDateTimeFieldFilter - Filter events by the time the event was ingested.
type ListEventsParamsFilterIngestedAtDateTimeFieldFilter struct {
	ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter     *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter     `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter    *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter    `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter     *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter     `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter    *ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter    `queryParam:"inline" union:"member"`

	Type ListEventsParamsFilterIngestedAtDateTimeFieldFilterType
}

func CreateListEventsParamsFilterIngestedAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter(listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter) ListEventsParamsFilterIngestedAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter

	return ListEventsParamsFilterIngestedAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter: &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterIngestedAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter(listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter) ListEventsParamsFilterIngestedAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter

	return ListEventsParamsFilterIngestedAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter: &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterIngestedAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter(listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter) ListEventsParamsFilterIngestedAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter

	return ListEventsParamsFilterIngestedAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter: &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterIngestedAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter(listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter) ListEventsParamsFilterIngestedAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter

	return ListEventsParamsFilterIngestedAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter: &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterIngestedAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter(listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter) ListEventsParamsFilterIngestedAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter

	return ListEventsParamsFilterIngestedAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter: &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter,
		Type: typ,
	}
}

func (u *ListEventsParamsFilterIngestedAtDateTimeFieldFilter) UnmarshalJSON(data []byte) error {

	var listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter = ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter = &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter
		u.Type = ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter = ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter = &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter
		u.Type = ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter = ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter = &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter
		u.Type = ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter = ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter = &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter
		u.Type = ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter = ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter = &listEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter
		u.Type = ListEventsParamsFilterIngestedAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ListEventsParamsFilterIngestedAtDateTimeFieldFilter", string(data))
}

func (u ListEventsParamsFilterIngestedAtDateTimeFieldFilter) MarshalJSON() ([]byte, error) {
	if u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldEqualsFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldLTEFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterIngestedAtDateTimeFieldGTEFilter, "", true)
	}

	return nil, errors.New("could not marshal union type ListEventsParamsFilterIngestedAtDateTimeFieldFilter: all fields are null")
}

type ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter struct {
	// Value is greater than or equal to the given RFC-3339 formatted timestamp in UTC
	Gte time.Time `queryParam:"name=gte"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"gte"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter) GetGte() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Gte
}

type ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter struct {
	// Value is greater than the given RFC-3339 formatted timestamp in UTC
	Gt time.Time `queryParam:"name=gt"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"gt"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter) GetGt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Gt
}

type ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter struct {
	// Value is less than or equal to the given RFC-3339 formatted timestamp in UTC
	Lte time.Time `queryParam:"name=lte"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"lte"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter) GetLte() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Lte
}

type ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter struct {
	// Value is less than the given RFC-3339 formatted timestamp in UTC
	Lt time.Time `queryParam:"name=lt"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"lt"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter) GetLt() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Lt
}

type ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter struct {
	// Value strictly equals given RFC-3339 formatted timestamp in UTC
	Eq time.Time `queryParam:"name=eq"`
}

func (l ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"eq"}); err != nil {
		return err
	}
	return nil
}

func (l *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter) GetEq() time.Time {
	if l == nil {
		return time.Time{}
	}
	return l.Eq
}

type ListEventsParamsFilterStoredAtDateTimeFieldFilterType string

const (
	ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter ListEventsParamsFilterStoredAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_stored_at_DateTimeFieldEqualsFilter"
	ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter     ListEventsParamsFilterStoredAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_stored_at_DateTimeFieldLTFilter"
	ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter    ListEventsParamsFilterStoredAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_stored_at_DateTimeFieldLTEFilter"
	ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter     ListEventsParamsFilterStoredAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_stored_at_DateTimeFieldGTFilter"
	ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter    ListEventsParamsFilterStoredAtDateTimeFieldFilterType = "ListEventsParamsFilter_DateTimeFieldFilter_stored_at_DateTimeFieldGTEFilter"
)

// ListEventsParamsFilterStoredAtDateTimeFieldFilter - Filter events by the time the event was stored.
type ListEventsParamsFilterStoredAtDateTimeFieldFilter struct {
	ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter     *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter     `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter    *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter    `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter     *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter     `queryParam:"inline" union:"member"`
	ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter    *ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter    `queryParam:"inline" union:"member"`

	Type ListEventsParamsFilterStoredAtDateTimeFieldFilterType
}

func CreateListEventsParamsFilterStoredAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter(listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter) ListEventsParamsFilterStoredAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter

	return ListEventsParamsFilterStoredAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter: &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterStoredAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter(listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter) ListEventsParamsFilterStoredAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter

	return ListEventsParamsFilterStoredAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter: &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterStoredAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter(listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter) ListEventsParamsFilterStoredAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter

	return ListEventsParamsFilterStoredAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter: &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterStoredAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter(listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter) ListEventsParamsFilterStoredAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter

	return ListEventsParamsFilterStoredAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter: &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter,
		Type: typ,
	}
}

func CreateListEventsParamsFilterStoredAtDateTimeFieldFilterListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter(listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter) ListEventsParamsFilterStoredAtDateTimeFieldFilter {
	typ := ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter

	return ListEventsParamsFilterStoredAtDateTimeFieldFilter{
		ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter: &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter,
		Type: typ,
	}
}

func (u *ListEventsParamsFilterStoredAtDateTimeFieldFilter) UnmarshalJSON(data []byte) error {

	var listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter = ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter = &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter
		u.Type = ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter = ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter = &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter
		u.Type = ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter = ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter = &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter
		u.Type = ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter = ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter = &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter
		u.Type = ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter
		return nil
	}

	var listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter = ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter{}
	if err := utils.UnmarshalJSON(data, &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter, "", true, nil); err == nil {
		u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter = &listEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter
		u.Type = ListEventsParamsFilterStoredAtDateTimeFieldFilterTypeListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ListEventsParamsFilterStoredAtDateTimeFieldFilter", string(data))
}

func (u ListEventsParamsFilterStoredAtDateTimeFieldFilter) MarshalJSON() ([]byte, error) {
	if u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldEqualsFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldLTEFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTFilter, "", true)
	}

	if u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter != nil {
		return utils.MarshalJSON(u.ListEventsParamsFilterDateTimeFieldFilterStoredAtDateTimeFieldGTEFilter, "", true)
	}

	return nil, errors.New("could not marshal union type ListEventsParamsFilterStoredAtDateTimeFieldFilter: all fields are null")
}

// ListEventsParamsFilter - Filter options for listing ingested events.
type ListEventsParamsFilter struct {
	// Filter events by ID.
	ID *StringFieldNEQFilter `queryParam:"name=id"`
	// Filter events by source.
	Source *ListEventsParamsFilterStringFieldNEQFilter `queryParam:"name=source"`
	// Filter events by subject.
	Subject *ListEventsParamsFilterSubjectStringFieldNEQFilter `queryParam:"name=subject"`
	// Filter events by type.
	Type *ListEventsParamsFilterTypeStringFieldNEQFilter `queryParam:"name=type"`
	// Filter events by the associated customer ID.
	CustomerID *ListEventsParamsFilterULIDFieldFilter `queryParam:"name=customer_id"`
	// Filter events by event time.
	Time *ListEventsParamsFilterDateTimeFieldFilter `queryParam:"name=time"`
	// Filter events by the time the event was ingested.
	IngestedAt *ListEventsParamsFilterIngestedAtDateTimeFieldFilter `queryParam:"name=ingested_at"`
	// Filter events by the time the event was stored.
	StoredAt *ListEventsParamsFilterStoredAtDateTimeFieldFilter `queryParam:"name=stored_at"`
}

func (l *ListEventsParamsFilter) GetID() *StringFieldNEQFilter {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *ListEventsParamsFilter) GetSource() *ListEventsParamsFilterStringFieldNEQFilter {
	if l == nil {
		return nil
	}
	return l.Source
}

func (l *ListEventsParamsFilter) GetSubject() *ListEventsParamsFilterSubjectStringFieldNEQFilter {
	if l == nil {
		return nil
	}
	return l.Subject
}

func (l *ListEventsParamsFilter) GetType() *ListEventsParamsFilterTypeStringFieldNEQFilter {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *ListEventsParamsFilter) GetCustomerID() *ListEventsParamsFilterULIDFieldFilter {
	if l == nil {
		return nil
	}
	return l.CustomerID
}

func (l *ListEventsParamsFilter) GetTime() *ListEventsParamsFilterDateTimeFieldFilter {
	if l == nil {
		return nil
	}
	return l.Time
}

func (l *ListEventsParamsFilter) GetIngestedAt() *ListEventsParamsFilterIngestedAtDateTimeFieldFilter {
	if l == nil {
		return nil
	}
	return l.IngestedAt
}

func (l *ListEventsParamsFilter) GetStoredAt() *ListEventsParamsFilterStoredAtDateTimeFieldFilter {
	if l == nil {
		return nil
	}
	return l.StoredAt
}
