// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// MCPResourceSourceAPICatalogType - The type of the MCP resource source.
type MCPResourceSourceAPICatalogType string

const (
	MCPResourceSourceAPICatalogTypeAPICatalog MCPResourceSourceAPICatalogType = "api_catalog"
	MCPResourceSourceAPICatalogTypeRaw        MCPResourceSourceAPICatalogType = "raw"
)

func (e MCPResourceSourceAPICatalogType) ToPointer() *MCPResourceSourceAPICatalogType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MCPResourceSourceAPICatalogType) IsExact() bool {
	if e != nil {
		switch *e {
		case "api_catalog", "raw":
			return true
		}
	}
	return false
}

// MCPResourceSourceAPICatalog - An MCP resource sourced from an API catalog entry.
type MCPResourceSourceAPICatalog struct {
	Type MCPResourceSourceAPICatalogType `json:"type"`
	// Identifies the API catalog entry the MCP resource was sourced from.
	Config MCPResourceSourceAPICatalogConfig `json:"config"`
}

func (m MCPResourceSourceAPICatalog) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MCPResourceSourceAPICatalog) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"type", "config"}); err != nil {
		return err
	}
	return nil
}

func (m *MCPResourceSourceAPICatalog) GetType() MCPResourceSourceAPICatalogType {
	if m == nil {
		return MCPResourceSourceAPICatalogType("")
	}
	return m.Type
}

func (m *MCPResourceSourceAPICatalog) GetConfig() MCPResourceSourceAPICatalogConfig {
	if m == nil {
		return MCPResourceSourceAPICatalogConfig{}
	}
	return m.Config
}
