// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7c032ab1c2a5

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// ParamLocation - Specify whether the 'param_name' and 'param_value' options go in a query string, or the POST form/JSON body.
type ParamLocation string

const (
	ParamLocationBody  ParamLocation = "body"
	ParamLocationQuery ParamLocation = "query"
)

func (e ParamLocation) ToPointer() *ParamLocation {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ParamLocation) IsExact() bool {
	if e != nil {
		switch *e {
		case "body", "query":
			return true
		}
	}
	return false
}

type Auth struct {
	// If enabled, the authorization header or parameter can be overridden in the request by the value configured in the plugin.
	AllowOverride *bool `default:"false" json:"allow_override"`
	// Set this if you are using an AWS provider (Bedrock) and you are authenticating using static IAM User credentials. Setting this will override the AWS_ACCESS_KEY_ID environment variable for this plugin instance.
	AwsAccessKeyID *string `json:"aws_access_key_id,omitempty"`
	// Set this if you are using an AWS provider (Bedrock) and you are authenticating using static IAM User credentials. Setting this will override the AWS_SECRET_ACCESS_KEY environment variable for this plugin instance.
	AwsSecretAccessKey *string `json:"aws_secret_access_key,omitempty"`
	// If azure_use_managed_identity is set to true, and you need to use a different user-assigned identity for this LLM instance, set the client ID.
	AzureClientID *string `json:"azure_client_id,omitempty"`
	// If azure_use_managed_identity is set to true, and you need to use a different user-assigned identity for this LLM instance, set the client secret.
	AzureClientSecret *string `json:"azure_client_secret,omitempty"`
	// If azure_use_managed_identity is set to true, and you need to use a different user-assigned identity for this LLM instance, set the tenant ID.
	AzureTenantID *string `json:"azure_tenant_id,omitempty"`
	// Set true to use the Azure Cloud Managed Identity (or user-assigned identity) to authenticate with Azure-provider models.
	AzureUseManagedIdentity *bool `default:"false" json:"azure_use_managed_identity"`
	// Custom metadata URL for GCP authentication. Useful for restricted network environments or custom GCP endpoints. If null, Kong will use the default Google metadata endpoint.
	GcpMetadataURL *string `json:"gcp_metadata_url,omitempty"`
	// Custom OAuth token URL for GCP authentication. Useful for restricted network environments or custom GCP endpoints. If null, Kong will use the default Google OAuth token endpoint.
	GcpOauthTokenURL *string `json:"gcp_oauth_token_url,omitempty"`
	// Set this field to the full JSON of the GCP service account to authenticate, if required. If null (and gcp_use_service_account is true), Kong will attempt to read from environment variable `GCP_SERVICE_ACCOUNT`.
	GcpServiceAccountJSON *string `json:"gcp_service_account_json,omitempty"`
	// Use service account auth for GCP-based providers and models.
	GcpUseServiceAccount *bool `default:"false" json:"gcp_use_service_account"`
	// If AI model requires authentication via Authorization or API key header, specify its name here.
	HeaderName *string `json:"header_name,omitempty"`
	// Specify the full auth header value for 'header_name', for example 'Bearer key' or just 'key'.
	HeaderValue *string `json:"header_value,omitempty"`
	// Specify whether the 'param_name' and 'param_value' options go in a query string, or the POST form/JSON body.
	ParamLocation *ParamLocation `json:"param_location,omitempty"`
	// If AI model requires authentication via query parameter, specify its name here.
	ParamName *string `json:"param_name,omitempty"`
	// Specify the full parameter value for 'param_name'.
	ParamValue *string `json:"param_value,omitempty"`
}

func (a Auth) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Auth) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Auth) GetAllowOverride() *bool {
	if a == nil {
		return nil
	}
	return a.AllowOverride
}

func (a *Auth) GetAwsAccessKeyID() *string {
	if a == nil {
		return nil
	}
	return a.AwsAccessKeyID
}

func (a *Auth) GetAwsSecretAccessKey() *string {
	if a == nil {
		return nil
	}
	return a.AwsSecretAccessKey
}

func (a *Auth) GetAzureClientID() *string {
	if a == nil {
		return nil
	}
	return a.AzureClientID
}

func (a *Auth) GetAzureClientSecret() *string {
	if a == nil {
		return nil
	}
	return a.AzureClientSecret
}

func (a *Auth) GetAzureTenantID() *string {
	if a == nil {
		return nil
	}
	return a.AzureTenantID
}

func (a *Auth) GetAzureUseManagedIdentity() *bool {
	if a == nil {
		return nil
	}
	return a.AzureUseManagedIdentity
}

func (a *Auth) GetGcpMetadataURL() *string {
	if a == nil {
		return nil
	}
	return a.GcpMetadataURL
}

func (a *Auth) GetGcpOauthTokenURL() *string {
	if a == nil {
		return nil
	}
	return a.GcpOauthTokenURL
}

func (a *Auth) GetGcpServiceAccountJSON() *string {
	if a == nil {
		return nil
	}
	return a.GcpServiceAccountJSON
}

func (a *Auth) GetGcpUseServiceAccount() *bool {
	if a == nil {
		return nil
	}
	return a.GcpUseServiceAccount
}

func (a *Auth) GetHeaderName() *string {
	if a == nil {
		return nil
	}
	return a.HeaderName
}

func (a *Auth) GetHeaderValue() *string {
	if a == nil {
		return nil
	}
	return a.HeaderValue
}

func (a *Auth) GetParamLocation() *ParamLocation {
	if a == nil {
		return nil
	}
	return a.ParamLocation
}

func (a *Auth) GetParamName() *string {
	if a == nil {
		return nil
	}
	return a.ParamName
}

func (a *Auth) GetParamValue() *string {
	if a == nil {
		return nil
	}
	return a.ParamValue
}

type Azure struct {
	// 'api-version' for Azure OpenAI instances.
	APIVersion *string `default:"2023-05-15" json:"api_version"`
	// Deployment ID for Azure OpenAI instances.
	DeploymentID *string `json:"deployment_id,omitempty"`
	// Instance name for Azure OpenAI hosted models.
	Instance *string `json:"instance,omitempty"`
}

func (a Azure) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *Azure) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *Azure) GetAPIVersion() *string {
	if a == nil {
		return nil
	}
	return a.APIVersion
}

func (a *Azure) GetDeploymentID() *string {
	if a == nil {
		return nil
	}
	return a.DeploymentID
}

func (a *Azure) GetInstance() *string {
	if a == nil {
		return nil
	}
	return a.Instance
}

type Bedrock struct {
	// If using AWS providers (Bedrock) you can assume a different role after authentication with the current IAM context is successful.
	AwsAssumeRoleArn *string `json:"aws_assume_role_arn,omitempty"`
	// If using AWS providers (Bedrock) you can override the `AWS_REGION` environment variable by setting this option.
	AwsRegion *string `json:"aws_region,omitempty"`
	// If using AWS providers (Bedrock), set the identifier of the assumed role session.
	AwsRoleSessionName *string `json:"aws_role_session_name,omitempty"`
	// If using AWS providers (Bedrock), override the STS endpoint URL when assuming a different role.
	AwsStsEndpointURL *string `json:"aws_sts_endpoint_url,omitempty"`
	// S3 URI prefix (s3://bucket/prefix/) where Bedrock will get input files from and store results to for native batch API.
	BatchBucketPrefix *string `json:"batch_bucket_prefix,omitempty"`
	// AWS role arn used for calling batch API. Try to get the value from request if ommited.
	BatchRoleArn *string `json:"batch_role_arn,omitempty"`
	// If using AWS providers (Bedrock), set to true to normalize the embeddings.
	EmbeddingsNormalize *bool `default:"false" json:"embeddings_normalize"`
	// Force the client's performance configuration 'latency' for all requests. Leave empty to let the consumer select the performance configuration.
	PerformanceConfigLatency *string `json:"performance_config_latency,omitempty"`
	// S3 URI (s3://bucket/prefix) where Bedrock will store generated video files. Required for video generation.
	VideoOutputS3URI *string `json:"video_output_s3_uri,omitempty"`
}

func (b Bedrock) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Bedrock) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *Bedrock) GetAwsAssumeRoleArn() *string {
	if b == nil {
		return nil
	}
	return b.AwsAssumeRoleArn
}

func (b *Bedrock) GetAwsRegion() *string {
	if b == nil {
		return nil
	}
	return b.AwsRegion
}

func (b *Bedrock) GetAwsRoleSessionName() *string {
	if b == nil {
		return nil
	}
	return b.AwsRoleSessionName
}

func (b *Bedrock) GetAwsStsEndpointURL() *string {
	if b == nil {
		return nil
	}
	return b.AwsStsEndpointURL
}

func (b *Bedrock) GetBatchBucketPrefix() *string {
	if b == nil {
		return nil
	}
	return b.BatchBucketPrefix
}

func (b *Bedrock) GetBatchRoleArn() *string {
	if b == nil {
		return nil
	}
	return b.BatchRoleArn
}

func (b *Bedrock) GetEmbeddingsNormalize() *bool {
	if b == nil {
		return nil
	}
	return b.EmbeddingsNormalize
}

func (b *Bedrock) GetPerformanceConfigLatency() *string {
	if b == nil {
		return nil
	}
	return b.PerformanceConfigLatency
}

func (b *Bedrock) GetVideoOutputS3URI() *string {
	if b == nil {
		return nil
	}
	return b.VideoOutputS3URI
}

type Gemini struct {
	// If running Gemini on Vertex, specify the regional API endpoint (hostname only).
	APIEndpoint *string `json:"api_endpoint,omitempty"`
	// If running Gemini on Vertex, specify the location ID.
	LocationID *string `json:"location_id,omitempty"`
	// If running Gemini on Vertex, specify the project ID.
	ProjectID *string `json:"project_id,omitempty"`
}

func (g Gemini) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *Gemini) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *Gemini) GetAPIEndpoint() *string {
	if g == nil {
		return nil
	}
	return g.APIEndpoint
}

func (g *Gemini) GetLocationID() *string {
	if g == nil {
		return nil
	}
	return g.LocationID
}

func (g *Gemini) GetProjectID() *string {
	if g == nil {
		return nil
	}
	return g.ProjectID
}

type Huggingface struct {
	// Use the cache layer on the inference API
	UseCache *bool `json:"use_cache,omitempty"`
	// Wait for the model if it is not ready
	WaitForModel *bool `json:"wait_for_model,omitempty"`
}

func (h Huggingface) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *Huggingface) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *Huggingface) GetUseCache() *bool {
	if h == nil {
		return nil
	}
	return h.UseCache
}

func (h *Huggingface) GetWaitForModel() *bool {
	if h == nil {
		return nil
	}
	return h.WaitForModel
}

// OptionsObj - Key/value settings for the model
type OptionsObj struct {
	Azure       *Azure       `json:"azure,omitempty"`
	Bedrock     *Bedrock     `json:"bedrock,omitempty"`
	Gemini      *Gemini      `json:"gemini,omitempty"`
	Huggingface *Huggingface `json:"huggingface,omitempty"`
	// upstream url for the embeddings
	UpstreamURL *string `json:"upstream_url,omitempty"`
}

func (o OptionsObj) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionsObj) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OptionsObj) GetAzure() *Azure {
	if o == nil {
		return nil
	}
	return o.Azure
}

func (o *OptionsObj) GetBedrock() *Bedrock {
	if o == nil {
		return nil
	}
	return o.Bedrock
}

func (o *OptionsObj) GetGemini() *Gemini {
	if o == nil {
		return nil
	}
	return o.Gemini
}

func (o *OptionsObj) GetHuggingface() *Huggingface {
	if o == nil {
		return nil
	}
	return o.Huggingface
}

func (o *OptionsObj) GetUpstreamURL() *string {
	if o == nil {
		return nil
	}
	return o.UpstreamURL
}

// PartialEmbeddingsProvider - AI provider format to use for embeddings API
type PartialEmbeddingsProvider string

const (
	PartialEmbeddingsProviderAzure       PartialEmbeddingsProvider = "azure"
	PartialEmbeddingsProviderBedrock     PartialEmbeddingsProvider = "bedrock"
	PartialEmbeddingsProviderGemini      PartialEmbeddingsProvider = "gemini"
	PartialEmbeddingsProviderHuggingface PartialEmbeddingsProvider = "huggingface"
	PartialEmbeddingsProviderMistral     PartialEmbeddingsProvider = "mistral"
	PartialEmbeddingsProviderOllama      PartialEmbeddingsProvider = "ollama"
	PartialEmbeddingsProviderOpenai      PartialEmbeddingsProvider = "openai"
)

func (e PartialEmbeddingsProvider) ToPointer() *PartialEmbeddingsProvider {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PartialEmbeddingsProvider) IsExact() bool {
	if e != nil {
		switch *e {
		case "azure", "bedrock", "gemini", "huggingface", "mistral", "ollama", "openai":
			return true
		}
	}
	return false
}

type Model struct {
	// Model name to execute.
	Name string `json:"name"`
	// Key/value settings for the model
	Options *OptionsObj `json:"options,omitempty"`
	// AI provider format to use for embeddings API
	Provider PartialEmbeddingsProvider `json:"provider"`
}

func (m Model) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Model) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, []string{"name", "provider"}); err != nil {
		return err
	}
	return nil
}

func (m *Model) GetName() string {
	if m == nil {
		return ""
	}
	return m.Name
}

func (m *Model) GetOptions() *OptionsObj {
	if m == nil {
		return nil
	}
	return m.Options
}

func (m *Model) GetProvider() PartialEmbeddingsProvider {
	if m == nil {
		return PartialEmbeddingsProvider("")
	}
	return m.Provider
}

type PartialEmbeddingsConfig struct {
	Auth  *Auth `json:"auth,omitempty"`
	Model Model `json:"model"`
}

func (p PartialEmbeddingsConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PartialEmbeddingsConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"model"}); err != nil {
		return err
	}
	return nil
}

func (p *PartialEmbeddingsConfig) GetAuth() *Auth {
	if p == nil {
		return nil
	}
	return p.Auth
}

func (p *PartialEmbeddingsConfig) GetModel() Model {
	if p == nil {
		return Model{}
	}
	return p.Model
}

type PartialEmbeddings struct {
	Config PartialEmbeddingsConfig `json:"config"`
	// Unix epoch when the resource was created.
	CreatedAt *int64 `json:"created_at,omitempty"`
	// A string representing a UUID (universally unique identifier).
	ID *string `json:"id,omitempty"`
	// A unique string representing a UTF-8 encoded name.
	Name *string `json:"name,omitempty"`
	// A set of strings representing tags.
	Tags []string `json:"tags,omitempty"`
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	type_ string `const:"embeddings" json:"type"`
	// Unix epoch when the resource was last updated.
	UpdatedAt *int64 `json:"updated_at,omitempty"`
}

func (p PartialEmbeddings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PartialEmbeddings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"config", "type"}); err != nil {
		return err
	}
	return nil
}

func (p *PartialEmbeddings) GetConfig() PartialEmbeddingsConfig {
	if p == nil {
		return PartialEmbeddingsConfig{}
	}
	return p.Config
}

func (p *PartialEmbeddings) GetCreatedAt() *int64 {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PartialEmbeddings) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PartialEmbeddings) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PartialEmbeddings) GetTags() []string {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PartialEmbeddings) GetType() string {
	return "embeddings"
}

func (p *PartialEmbeddings) GetUpdatedAt() *int64 {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
