// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PluginSearchFilter struct {
	// Filter using **one** of the following operators: `eq`, `contains`
	Name *LegacyStringFieldFilter `queryParam:"name=name"`
	// Filter by a boolean value (true/false).
	Enabled *bool `queryParam:"name=enabled"`
	// Filters on the given plugin scope value by exact match.
	Scope *PluginScopeEqualsFilter `queryParam:"name=scope"`
	// Filters on the given string field value by exact match.
	Route *StringFieldEqualsFilter `queryParam:"name=route"`
	// Filters on the given string field value by exact match.
	Service *StringFieldEqualsFilter `queryParam:"name=service"`
	// Filters on the given string field value by exact match.
	Consumer *StringFieldEqualsFilter `queryParam:"name=consumer"`
	// Filters on the given string field value by exact match.
	ConsumerGroup *StringFieldEqualsFilter `queryParam:"name=consumer_group"`
}

func (p *PluginSearchFilter) GetName() *LegacyStringFieldFilter {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PluginSearchFilter) GetEnabled() *bool {
	if p == nil {
		return nil
	}
	return p.Enabled
}

func (p *PluginSearchFilter) GetScope() *PluginScopeEqualsFilter {
	if p == nil {
		return nil
	}
	return p.Scope
}

func (p *PluginSearchFilter) GetRoute() *StringFieldEqualsFilter {
	if p == nil {
		return nil
	}
	return p.Route
}

func (p *PluginSearchFilter) GetService() *StringFieldEqualsFilter {
	if p == nil {
		return nil
	}
	return p.Service
}

func (p *PluginSearchFilter) GetConsumer() *StringFieldEqualsFilter {
	if p == nil {
		return nil
	}
	return p.Consumer
}

func (p *PluginSearchFilter) GetConsumerGroup() *StringFieldEqualsFilter {
	if p == nil {
		return nil
	}
	return p.ConsumerGroup
}
