// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Eq string

const (
	EqRoute         Eq = "route"
	EqService       Eq = "service"
	EqConsumer      Eq = "consumer"
	EqConsumerGroup Eq = "consumer_group"
	EqGlobal        Eq = "global"
)

func (e Eq) ToPointer() *Eq {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Eq) IsExact() bool {
	if e != nil {
		switch *e {
		case "route", "service", "consumer", "consumer_group", "global":
			return true
		}
	}
	return false
}

// PluginScopeEqualsFilter - Filters on the given plugin scope value by exact match.
type PluginScopeEqualsFilter struct {
	Eq *Eq `queryParam:"name=eq"`
}

func (p *PluginScopeEqualsFilter) GetEq() *Eq {
	if p == nil {
		return nil
	}
	return p.Eq
}
