// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Provider - Description of cloud provider that runs cloud gateway instances.
type Provider struct {
	// Name of cloud provider.
	Provider ProviderName `json:"provider"`
	// List of available regions to run cloud gateway instances on for a given cloud provider.
	Regions []ProviderRegion `json:"regions"`
}

func (p *Provider) GetProvider() ProviderName {
	if p == nil {
		return ProviderName("")
	}
	return p.Provider
}

func (p *Provider) GetRegions() []ProviderRegion {
	if p == nil {
		return []ProviderRegion{}
	}
	return p.Regions
}
