// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PublishedStatus - Whether the resource is visible on a given portal. Defaults to unpublished.
type PublishedStatus string

const (
	PublishedStatusPublished   PublishedStatus = "published"
	PublishedStatusUnpublished PublishedStatus = "unpublished"
)

func (e PublishedStatus) ToPointer() *PublishedStatus {
	return &e
}
