// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// ReferenceByName - A static encryption key reference by name.
type ReferenceByName struct {
	// The name of the static key defined in the key source.
	Name string `json:"name"`
}

func (r ReferenceByName) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReferenceByName) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (r *ReferenceByName) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}
