// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
	"time"
)

// ResourceQuota - Object containing information about a resource quota for an organization.
type ResourceQuota struct {
	ID string `json:"id"`
	// Enumeration of resources available for quota enforcement.
	Resource ResourceQuotaQualifier `json:"resource"`
	// The human-readable name of this resource quota.
	Name string `json:"name"`
	// A more verbose description of what this resource quota enforces.
	Description string `json:"description"`
	// The aggregate non-negative integer count of this resource that's allowed for the organization.
	//
	Value int64 `json:"value"`
	// An RFC-3339 timestamp representation of resource quota creation date.
	CreatedAt time.Time `json:"created_at"`
	// An RFC-3339 timestamp representation of resource quota update date.
	UpdatedAt time.Time `json:"updated_at"`
}

func (r ResourceQuota) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResourceQuota) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ResourceQuota) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ResourceQuota) GetResource() ResourceQuotaQualifier {
	if o == nil {
		return ResourceQuotaQualifier("")
	}
	return o.Resource
}

func (o *ResourceQuota) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ResourceQuota) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *ResourceQuota) GetValue() int64 {
	if o == nil {
		return 0
	}
	return o.Value
}

func (o *ResourceQuota) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ResourceQuota) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
