// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d6fdbd1c8bf3

package components

import (
	"encoding/json"
	"fmt"
	"github.com/Kong/sdk-konnect-go/internal/utils"
	"time"
)

// SourceType - The source type of the skill content.
type SourceType string

const (
	SourceTypeRaw SourceType = "raw"
)

func (e SourceType) ToPointer() *SourceType {
	return &e
}
func (e *SourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "raw":
		*e = SourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SourceType: %v", v)
	}
}

// Status - The current validation status of the skill.
type Status string

const (
	StatusValid   Status = "valid"
	StatusInvalid Status = "invalid"
)

func (e Status) ToPointer() *Status {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Status) IsExact() bool {
	if e != nil {
		switch *e {
		case "valid", "invalid":
			return true
		}
	}
	return false
}

type Skill struct {
	// The unique identifier for the skill.
	ID string `json:"id"`
	// The ID of the Context Interface this skill belongs to.
	ContextInterfaceID string `json:"context_interface_id"`
	// The machine name of the skill.
	Name string `json:"name"`
	// The human-readable display name of the skill.
	DisplayName string `json:"display_name"`
	// A description of the skill.
	Description string           `json:"description"`
	Frontmatter SkillFrontmatter `json:"frontmatter"`
	// Labels store metadata of an entity that can be used for filtering an entity list or for searching across entity types.
	//
	// Keys must be of length 1-63 characters, and cannot start with "kong", "konnect", "mesh", "kic", or "_".
	//
	Labels map[string]string `json:"labels"`
	// The source type of the skill content.
	SourceType SourceType `json:"source_type"`
	// The current validation status of the skill.
	Status Status `json:"status"`
	// An ISO-8601 timestamp representation of entity creation date.
	CreatedAt time.Time `json:"created_at"`
	// An ISO-8601 timestamp representation of entity update date.
	UpdatedAt time.Time `json:"updated_at"`
}

func (s Skill) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Skill) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Skill) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Skill) GetContextInterfaceID() string {
	if s == nil {
		return ""
	}
	return s.ContextInterfaceID
}

func (s *Skill) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *Skill) GetDisplayName() string {
	if s == nil {
		return ""
	}
	return s.DisplayName
}

func (s *Skill) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *Skill) GetFrontmatter() SkillFrontmatter {
	if s == nil {
		return SkillFrontmatter{}
	}
	return s.Frontmatter
}

func (s *Skill) GetLabels() map[string]string {
	if s == nil {
		return map[string]string{}
	}
	return s.Labels
}

func (s *Skill) GetSourceType() SourceType {
	if s == nil {
		return SourceType("")
	}
	return s.SourceType
}

func (s *Skill) GetStatus() Status {
	if s == nil {
		return Status("")
	}
	return s.Status
}

func (s *Skill) GetCreatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.CreatedAt
}

func (s *Skill) GetUpdatedAt() time.Time {
	if s == nil {
		return time.Time{}
	}
	return s.UpdatedAt
}
