// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SpecFormatSchema - The format of the returned `spec.content`.
type SpecFormatSchema string

const (
	SpecFormatSchemaJSON SpecFormatSchema = "json"
	SpecFormatSchemaYaml SpecFormatSchema = "yaml"
)

func (e SpecFormatSchema) ToPointer() *SpecFormatSchema {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SpecFormatSchema) IsExact() bool {
	if e != nil {
		switch *e {
		case "json", "yaml":
			return true
		}
	}
	return false
}
