// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StringFieldContainsFilter - Filter a string value field by partial contains.
type StringFieldContainsFilter struct {
	Contains string `queryParam:"name=contains"`
}

func (o *StringFieldContainsFilter) GetContains() string {
	if o == nil {
		return ""
	}
	return o.Contains
}
