// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SubscriptionPagePaginatedResponse - Page paginated response.
type SubscriptionPagePaginatedResponse struct {
	Data []BillingSubscription `json:"data"`
	// returns the pagination information
	Meta PaginatedMeta `json:"meta"`
}

func (s *SubscriptionPagePaginatedResponse) GetData() []BillingSubscription {
	if s == nil {
		return []BillingSubscription{}
	}
	return s.Data
}

func (s *SubscriptionPagePaginatedResponse) GetMeta() PaginatedMeta {
	if s == nil {
		return PaginatedMeta{}
	}
	return s.Meta
}
