// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/Kong/sdk-konnect-go/internal/utils"
)

// TaxCodeReference - TaxCode reference.
type TaxCodeReference struct {
	// ULID (Universally Unique Lexicographically Sortable Identifier).
	ID string `json:"id"`
}

func (t TaxCodeReference) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TaxCodeReference) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (t *TaxCodeReference) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}
