// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UpdateConfigStore - The request schema to update a Config Store.
type UpdateConfigStore struct {
	Name *string `json:"name,omitempty"`
}

func (u *UpdateConfigStore) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}
