// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 156a3db9ac91

package components

// UpdateEventGatewayPolicyChainRequest - The request schema for updating the policy chain.
type UpdateEventGatewayPolicyChainRequest struct {
	Policies []string `json:"policies"`
}

func (u *UpdateEventGatewayPolicyChainRequest) GetPolicies() []string {
	if u == nil {
		return []string{}
	}
	return u.Policies
}
