// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CursorPaginatedMetaWithSizeAndTotal - returns the pagination information
type CursorPaginatedMetaWithSizeAndTotal struct {
	Page CursorMetaWithSizeAndTotal `json:"page"`
}

func (o *CursorPaginatedMetaWithSizeAndTotal) GetPage() CursorMetaWithSizeAndTotal {
	if o == nil {
		return CursorMetaWithSizeAndTotal{}
	}
	return o.Page
}
