// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreatePartialRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Description of the new Partial for creation
	Partial components.Partial `request:"mediaType=application/json"`
}

func (o *CreatePartialRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *CreatePartialRequest) GetPartial() components.Partial {
	if o == nil {
		return components.Partial{}
	}
	return o.Partial
}

type CreatePartialResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully created Partial
	Partial *components.Partial
}

func (o *CreatePartialResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreatePartialResponse) GetPartial() *components.Partial {
	if o == nil {
		return nil
	}
	return o.Partial
}
