// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type CreateMtlsAuthWithConsumerRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Consumer ID for nested entities
	ConsumerIDForNestedEntities string `pathParam:"style=simple,explode=false,name=ConsumerIdForNestedEntities"`
	// Description of new MTLS-auth credential for creation
	MTLSAuthWithoutParents components.MTLSAuthWithoutParents `request:"mediaType=application/json"`
}

func (o *CreateMtlsAuthWithConsumerRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *CreateMtlsAuthWithConsumerRequest) GetConsumerIDForNestedEntities() string {
	if o == nil {
		return ""
	}
	return o.ConsumerIDForNestedEntities
}

func (o *CreateMtlsAuthWithConsumerRequest) GetMTLSAuthWithoutParents() components.MTLSAuthWithoutParents {
	if o == nil {
		return components.MTLSAuthWithoutParents{}
	}
	return o.MTLSAuthWithoutParents
}

type CreateMtlsAuthWithConsumerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully created MTLS-auth credential
	MTLSAuth *components.MTLSAuth
}

func (o *CreateMtlsAuthWithConsumerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateMtlsAuthWithConsumerResponse) GetMTLSAuth() *components.MTLSAuth {
	if o == nil {
		return nil
	}
	return o.MTLSAuth
}
