// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetConfigStoreSecretRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Config Store identifier
	ConfigStoreID string `pathParam:"style=simple,explode=false,name=configStoreId"`
	// Config Store Secret key
	Key string `pathParam:"style=simple,explode=false,name=key"`
}

func (o *GetConfigStoreSecretRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *GetConfigStoreSecretRequest) GetConfigStoreID() string {
	if o == nil {
		return ""
	}
	return o.ConfigStoreID
}

func (o *GetConfigStoreSecretRequest) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

type GetConfigStoreSecretResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Config Store Secret
	ConfigStoreSecret *components.ConfigStoreSecret
}

func (o *GetConfigStoreSecretResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetConfigStoreSecretResponse) GetConfigStoreSecret() *components.ConfigStoreSecret {
	if o == nil {
		return nil
	}
	return o.ConfigStoreSecret
}
