// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

// ListRegistrationsByApplicationFilter - Filter application registrations returned in the response.
type ListRegistrationsByApplicationFilter struct {
	// Filters on the given string field value by either exact or fuzzy match.
	Status *components.StringFieldFilter `queryParam:"name=status"`
}

func (o *ListRegistrationsByApplicationFilter) GetStatus() *components.StringFieldFilter {
	if o == nil {
		return nil
	}
	return o.Status
}

type ListRegistrationsByApplicationRequest struct {
	// ID of the portal.
	PortalID string `pathParam:"style=simple,explode=false,name=portalId"`
	// ID of the application.
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
	// The maximum number of items to include per page. The last page of a collection may include fewer items.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
	// Determines which page of the entities to retrieve.
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page[number]"`
	// Sorts a set of registrations for an application. Supported sort attributes are:
	//
	//
	//
	//   - created_at
	//   - updated_at
	//   - status
	//
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Filter application registrations returned in the response.
	Filter *ListRegistrationsByApplicationFilter `queryParam:"style=deepObject,explode=true,name=filter"`
}

func (o *ListRegistrationsByApplicationRequest) GetPortalID() string {
	if o == nil {
		return ""
	}
	return o.PortalID
}

func (o *ListRegistrationsByApplicationRequest) GetApplicationID() string {
	if o == nil {
		return ""
	}
	return o.ApplicationID
}

func (o *ListRegistrationsByApplicationRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *ListRegistrationsByApplicationRequest) GetPageNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.PageNumber
}

func (o *ListRegistrationsByApplicationRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *ListRegistrationsByApplicationRequest) GetFilter() *ListRegistrationsByApplicationFilter {
	if o == nil {
		return nil
	}
	return o.Filter
}

type ListRegistrationsByApplicationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A paginated list of application registrations.
	ListApplicationRegistrationsResponse *components.ListApplicationRegistrationsResponse
}

func (o *ListRegistrationsByApplicationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListRegistrationsByApplicationResponse) GetListApplicationRegistrationsResponse() *components.ListApplicationRegistrationsResponse {
	if o == nil {
		return nil
	}
	return o.ListApplicationRegistrationsResponse
}
