// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type PatchSystemAccountsIDAccessTokensIDRequest struct {
	// ID of the system account.
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
	// ID of the system account access token.
	TokenID                        string                                     `pathParam:"style=simple,explode=false,name=tokenId"`
	UpdateSystemAccountAccessToken *components.UpdateSystemAccountAccessToken `request:"mediaType=application/json"`
}

func (o *PatchSystemAccountsIDAccessTokensIDRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *PatchSystemAccountsIDAccessTokensIDRequest) GetTokenID() string {
	if o == nil {
		return ""
	}
	return o.TokenID
}

func (o *PatchSystemAccountsIDAccessTokensIDRequest) GetUpdateSystemAccountAccessToken() *components.UpdateSystemAccountAccessToken {
	if o == nil {
		return nil
	}
	return o.UpdateSystemAccountAccessToken
}

type PatchSystemAccountsIDAccessTokensIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A response including a single system account access token.
	SystemAccountAccessToken *components.SystemAccountAccessToken
}

func (o *PatchSystemAccountsIDAccessTokensIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PatchSystemAccountsIDAccessTokensIDResponse) GetSystemAccountAccessToken() *components.SystemAccountAccessToken {
	if o == nil {
		return nil
	}
	return o.SystemAccountAccessToken
}
