// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpdateNotificationRequest struct {
	// ID of the notification.
	NotificationID string `pathParam:"style=simple,explode=false,name=notificationId"`
	// Request body schema for updating notification status.
	NotificationUpdatePayload *components.NotificationUpdatePayload `request:"mediaType=application/json"`
}

func (o *UpdateNotificationRequest) GetNotificationID() string {
	if o == nil {
		return ""
	}
	return o.NotificationID
}

func (o *UpdateNotificationRequest) GetNotificationUpdatePayload() *components.NotificationUpdatePayload {
	if o == nil {
		return nil
	}
	return o.NotificationUpdatePayload
}

type UpdateNotificationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// View a single notification.
	Notification *components.Notification
}

func (o *UpdateNotificationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateNotificationResponse) GetNotification() *components.Notification {
	if o == nil {
		return nil
	}
	return o.Notification
}
