// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpsertCaCertificateRequest struct {
	// ID of the CA Certificate to lookup
	CACertificateID string `pathParam:"style=simple,explode=false,name=CACertificateId"`
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Description of the CA Certificate
	CACertificate components.CACertificate `request:"mediaType=application/json"`
}

func (o *UpsertCaCertificateRequest) GetCACertificateID() string {
	if o == nil {
		return ""
	}
	return o.CACertificateID
}

func (o *UpsertCaCertificateRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *UpsertCaCertificateRequest) GetCACertificate() components.CACertificate {
	if o == nil {
		return components.CACertificate{}
	}
	return o.CACertificate
}

type UpsertCaCertificateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully upserted CA Certificate
	CACertificate *components.CACertificate
}

func (o *UpsertCaCertificateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpsertCaCertificateResponse) GetCACertificate() *components.CACertificate {
	if o == nil {
		return nil
	}
	return o.CACertificate
}
