// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type UpsertACLWithConsumerRequest struct {
	// The UUID of your control plane. This variable is available in the Konnect manager.
	ControlPlaneID string `pathParam:"style=simple,explode=false,name=controlPlaneId"`
	// Consumer ID for nested entities
	ConsumerIDForNestedEntities string `pathParam:"style=simple,explode=false,name=ConsumerIdForNestedEntities"`
	// ID of the ACL to lookup
	ACLID string `pathParam:"style=simple,explode=false,name=ACLId"`
	// Description of the ACL
	ACLWithoutParents components.ACLWithoutParents `request:"mediaType=application/json"`
}

func (o *UpsertACLWithConsumerRequest) GetControlPlaneID() string {
	if o == nil {
		return ""
	}
	return o.ControlPlaneID
}

func (o *UpsertACLWithConsumerRequest) GetConsumerIDForNestedEntities() string {
	if o == nil {
		return ""
	}
	return o.ConsumerIDForNestedEntities
}

func (o *UpsertACLWithConsumerRequest) GetACLID() string {
	if o == nil {
		return ""
	}
	return o.ACLID
}

func (o *UpsertACLWithConsumerRequest) GetACLWithoutParents() components.ACLWithoutParents {
	if o == nil {
		return components.ACLWithoutParents{}
	}
	return o.ACLWithoutParents
}

type UpsertACLWithConsumerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully upserted ACL
	ACL *components.ACL
}

func (o *UpsertACLWithConsumerResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpsertACLWithConsumerResponse) GetACL() *components.ACL {
	if o == nil {
		return nil
	}
	return o.ACL
}
