workflowVersion: 1.0.0
speakeasyVersion: 1.790.2
sources:
    konnect:
        inputs:
            - location: ./openapi.yaml
        overlays:
            - location: ./.speakeasy/overlays/update-portal-patch-defaults.yaml
            - location: ./.speakeasy/overlays/update-portal-audit-log-webhook-patch-defaults.yaml
            - location: ./.speakeasy/overlays/patch-custom-portal-email-template-defaults.yaml
            - location: ./.speakeasy/overlays/update-portal-identity-provider-defaults.yaml
            - location: ./.speakeasy/overlays/update-dcr-config-http-defaults.yaml
        registry:
            location: registry.speakeasyapi.dev/kong/kong/konnect
targets:
    go:
        target: go
        source: konnect
        output: .
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kong/kong/konnect-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
