// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatalogResourcesSDK creates a new instance of MockCatalogResourcesSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogResourcesSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogResourcesSDK {
	mock := &MockCatalogResourcesSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCatalogResourcesSDK is an autogenerated mock type for the CatalogResourcesSDK type
type MockCatalogResourcesSDK struct {
	mock.Mock
}

type MockCatalogResourcesSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogResourcesSDK) EXPECT() *MockCatalogResourcesSDK_Expecter {
	return &MockCatalogResourcesSDK_Expecter{mock: &_m.Mock}
}

// FetchResource provides a mock function for the type MockCatalogResourcesSDK
func (_mock *MockCatalogResourcesSDK) FetchResource(ctx context.Context, id string, opts ...operations.Option) (*operations.FetchResourceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, id, opts)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FetchResource")
	}

	var r0 *operations.FetchResourceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.FetchResourceResponse, error)); ok {
		return returnFunc(ctx, id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.FetchResourceResponse); ok {
		r0 = returnFunc(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.FetchResourceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogResourcesSDK_FetchResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchResource'
type MockCatalogResourcesSDK_FetchResource_Call struct {
	*mock.Call
}

// FetchResource is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...operations.Option
func (_e *MockCatalogResourcesSDK_Expecter) FetchResource(ctx any, id any, opts ...any) *MockCatalogResourcesSDK_FetchResource_Call {
	return &MockCatalogResourcesSDK_FetchResource_Call{Call: _e.mock.On("FetchResource",
		append([]any{ctx, id}, opts...)...)}
}

func (_c *MockCatalogResourcesSDK_FetchResource_Call) Run(run func(ctx context.Context, id string, opts ...operations.Option)) *MockCatalogResourcesSDK_FetchResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCatalogResourcesSDK_FetchResource_Call) Return(fetchResourceResponse *operations.FetchResourceResponse, err error) *MockCatalogResourcesSDK_FetchResource_Call {
	_c.Call.Return(fetchResourceResponse, err)
	return _c
}

func (_c *MockCatalogResourcesSDK_FetchResource_Call) RunAndReturn(run func(ctx context.Context, id string, opts ...operations.Option) (*operations.FetchResourceResponse, error)) *MockCatalogResourcesSDK_FetchResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type MockCatalogResourcesSDK
func (_mock *MockCatalogResourcesSDK) ListResources(ctx context.Context, request operations.ListResourcesRequest, opts ...operations.Option) (*operations.ListResourcesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 *operations.ListResourcesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListResourcesRequest, ...operations.Option) (*operations.ListResourcesResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListResourcesRequest, ...operations.Option) *operations.ListResourcesResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListResourcesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListResourcesRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogResourcesSDK_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockCatalogResourcesSDK_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListResourcesRequest
//   - opts ...operations.Option
func (_e *MockCatalogResourcesSDK_Expecter) ListResources(ctx any, request any, opts ...any) *MockCatalogResourcesSDK_ListResources_Call {
	return &MockCatalogResourcesSDK_ListResources_Call{Call: _e.mock.On("ListResources",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockCatalogResourcesSDK_ListResources_Call) Run(run func(ctx context.Context, request operations.ListResourcesRequest, opts ...operations.Option)) *MockCatalogResourcesSDK_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListResourcesRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListResourcesRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCatalogResourcesSDK_ListResources_Call) Return(listResourcesResponse *operations.ListResourcesResponse, err error) *MockCatalogResourcesSDK_ListResources_Call {
	_c.Call.Return(listResourcesResponse, err)
	return _c
}

func (_c *MockCatalogResourcesSDK_ListResources_Call) RunAndReturn(run func(ctx context.Context, request operations.ListResourcesRequest, opts ...operations.Option) (*operations.ListResourcesResponse, error)) *MockCatalogResourcesSDK_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type MockCatalogResourcesSDK
func (_mock *MockCatalogResourcesSDK) UpdateResource(ctx context.Context, request operations.UpdateResourceRequest, opts ...operations.Option) (*operations.UpdateResourceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *operations.UpdateResourceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateResourceRequest, ...operations.Option) (*operations.UpdateResourceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateResourceRequest, ...operations.Option) *operations.UpdateResourceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpdateResourceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateResourceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogResourcesSDK_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type MockCatalogResourcesSDK_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.UpdateResourceRequest
//   - opts ...operations.Option
func (_e *MockCatalogResourcesSDK_Expecter) UpdateResource(ctx any, request any, opts ...any) *MockCatalogResourcesSDK_UpdateResource_Call {
	return &MockCatalogResourcesSDK_UpdateResource_Call{Call: _e.mock.On("UpdateResource",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockCatalogResourcesSDK_UpdateResource_Call) Run(run func(ctx context.Context, request operations.UpdateResourceRequest, opts ...operations.Option)) *MockCatalogResourcesSDK_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateResourceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateResourceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCatalogResourcesSDK_UpdateResource_Call) Return(updateResourceResponse *operations.UpdateResourceResponse, err error) *MockCatalogResourcesSDK_UpdateResource_Call {
	_c.Call.Return(updateResourceResponse, err)
	return _c
}

func (_c *MockCatalogResourcesSDK_UpdateResource_Call) RunAndReturn(run func(ctx context.Context, request operations.UpdateResourceRequest, opts ...operations.Option) (*operations.UpdateResourceResponse, error)) *MockCatalogResourcesSDK_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}
