// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeysSDK creates a new instance of MockAPIKeysSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeysSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeysSDK {
	mock := &MockAPIKeysSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeysSDK is an autogenerated mock type for the APIKeysSDK type
type MockAPIKeysSDK struct {
	mock.Mock
}

type MockAPIKeysSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeysSDK) EXPECT() *MockAPIKeysSDK_Expecter {
	return &MockAPIKeysSDK_Expecter{mock: &_m.Mock}
}

// CreateKeyAuthWithConsumer provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) CreateKeyAuthWithConsumer(ctx context.Context, request operations.CreateKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.CreateKeyAuthWithConsumerResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateKeyAuthWithConsumer")
	}

	var r0 *operations.CreateKeyAuthWithConsumerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.CreateKeyAuthWithConsumerRequest, ...operations.Option) (*operations.CreateKeyAuthWithConsumerResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.CreateKeyAuthWithConsumerRequest, ...operations.Option) *operations.CreateKeyAuthWithConsumerResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateKeyAuthWithConsumerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.CreateKeyAuthWithConsumerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeyAuthWithConsumer'
type MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call struct {
	*mock.Call
}

// CreateKeyAuthWithConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.CreateKeyAuthWithConsumerRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) CreateKeyAuthWithConsumer(ctx any, request any, opts ...any) *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call {
	return &MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call{Call: _e.mock.On("CreateKeyAuthWithConsumer",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call) Run(run func(ctx context.Context, request operations.CreateKeyAuthWithConsumerRequest, opts ...operations.Option)) *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.CreateKeyAuthWithConsumerRequest
		if args[1] != nil {
			arg1 = args[1].(operations.CreateKeyAuthWithConsumerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call) Return(createKeyAuthWithConsumerResponse *operations.CreateKeyAuthWithConsumerResponse, err error) *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call {
	_c.Call.Return(createKeyAuthWithConsumerResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call) RunAndReturn(run func(ctx context.Context, request operations.CreateKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.CreateKeyAuthWithConsumerResponse, error)) *MockAPIKeysSDK_CreateKeyAuthWithConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKeyAuthWithConsumerInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) CreateKeyAuthWithConsumerInWorkspace(ctx context.Context, request operations.CreateKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.CreateKeyAuthWithConsumerInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateKeyAuthWithConsumerInWorkspace")
	}

	var r0 *operations.CreateKeyAuthWithConsumerInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.CreateKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) (*operations.CreateKeyAuthWithConsumerInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.CreateKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) *operations.CreateKeyAuthWithConsumerInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateKeyAuthWithConsumerInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.CreateKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKeyAuthWithConsumerInWorkspace'
type MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call struct {
	*mock.Call
}

// CreateKeyAuthWithConsumerInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.CreateKeyAuthWithConsumerInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) CreateKeyAuthWithConsumerInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call {
	return &MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call{Call: _e.mock.On("CreateKeyAuthWithConsumerInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call) Run(run func(ctx context.Context, request operations.CreateKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.CreateKeyAuthWithConsumerInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.CreateKeyAuthWithConsumerInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call) Return(createKeyAuthWithConsumerInWorkspaceResponse *operations.CreateKeyAuthWithConsumerInWorkspaceResponse, err error) *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(createKeyAuthWithConsumerInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.CreateKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.CreateKeyAuthWithConsumerInWorkspaceResponse, error)) *MockAPIKeysSDK_CreateKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyAuthWithConsumer provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) DeleteKeyAuthWithConsumer(ctx context.Context, request operations.DeleteKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.DeleteKeyAuthWithConsumerResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyAuthWithConsumer")
	}

	var r0 *operations.DeleteKeyAuthWithConsumerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.DeleteKeyAuthWithConsumerRequest, ...operations.Option) (*operations.DeleteKeyAuthWithConsumerResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.DeleteKeyAuthWithConsumerRequest, ...operations.Option) *operations.DeleteKeyAuthWithConsumerResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteKeyAuthWithConsumerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.DeleteKeyAuthWithConsumerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyAuthWithConsumer'
type MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call struct {
	*mock.Call
}

// DeleteKeyAuthWithConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.DeleteKeyAuthWithConsumerRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) DeleteKeyAuthWithConsumer(ctx any, request any, opts ...any) *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call {
	return &MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call{Call: _e.mock.On("DeleteKeyAuthWithConsumer",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call) Run(run func(ctx context.Context, request operations.DeleteKeyAuthWithConsumerRequest, opts ...operations.Option)) *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.DeleteKeyAuthWithConsumerRequest
		if args[1] != nil {
			arg1 = args[1].(operations.DeleteKeyAuthWithConsumerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call) Return(deleteKeyAuthWithConsumerResponse *operations.DeleteKeyAuthWithConsumerResponse, err error) *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call {
	_c.Call.Return(deleteKeyAuthWithConsumerResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call) RunAndReturn(run func(ctx context.Context, request operations.DeleteKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.DeleteKeyAuthWithConsumerResponse, error)) *MockAPIKeysSDK_DeleteKeyAuthWithConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeyAuthWithConsumerInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) DeleteKeyAuthWithConsumerInWorkspace(ctx context.Context, request operations.DeleteKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.DeleteKeyAuthWithConsumerInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeyAuthWithConsumerInWorkspace")
	}

	var r0 *operations.DeleteKeyAuthWithConsumerInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.DeleteKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) (*operations.DeleteKeyAuthWithConsumerInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.DeleteKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) *operations.DeleteKeyAuthWithConsumerInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteKeyAuthWithConsumerInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.DeleteKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeyAuthWithConsumerInWorkspace'
type MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call struct {
	*mock.Call
}

// DeleteKeyAuthWithConsumerInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.DeleteKeyAuthWithConsumerInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) DeleteKeyAuthWithConsumerInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call {
	return &MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call{Call: _e.mock.On("DeleteKeyAuthWithConsumerInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call) Run(run func(ctx context.Context, request operations.DeleteKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.DeleteKeyAuthWithConsumerInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.DeleteKeyAuthWithConsumerInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call) Return(deleteKeyAuthWithConsumerInWorkspaceResponse *operations.DeleteKeyAuthWithConsumerInWorkspaceResponse, err error) *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(deleteKeyAuthWithConsumerInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.DeleteKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.DeleteKeyAuthWithConsumerInWorkspaceResponse, error)) *MockAPIKeysSDK_DeleteKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyAuth provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) GetKeyAuth(ctx context.Context, keyAuthID string, controlPlaneID string, opts ...operations.Option) (*operations.GetKeyAuthResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, keyAuthID, controlPlaneID, opts)
	} else {
		tmpRet = _mock.Called(ctx, keyAuthID, controlPlaneID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetKeyAuth")
	}

	var r0 *operations.GetKeyAuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) (*operations.GetKeyAuthResponse, error)); ok {
		return returnFunc(ctx, keyAuthID, controlPlaneID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) *operations.GetKeyAuthResponse); ok {
		r0 = returnFunc(ctx, keyAuthID, controlPlaneID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetKeyAuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, keyAuthID, controlPlaneID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_GetKeyAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyAuth'
type MockAPIKeysSDK_GetKeyAuth_Call struct {
	*mock.Call
}

// GetKeyAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - keyAuthID string
//   - controlPlaneID string
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) GetKeyAuth(ctx any, keyAuthID any, controlPlaneID any, opts ...any) *MockAPIKeysSDK_GetKeyAuth_Call {
	return &MockAPIKeysSDK_GetKeyAuth_Call{Call: _e.mock.On("GetKeyAuth",
		append([]any{ctx, keyAuthID, controlPlaneID}, opts...)...)}
}

func (_c *MockAPIKeysSDK_GetKeyAuth_Call) Run(run func(ctx context.Context, keyAuthID string, controlPlaneID string, opts ...operations.Option)) *MockAPIKeysSDK_GetKeyAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuth_Call) Return(getKeyAuthResponse *operations.GetKeyAuthResponse, err error) *MockAPIKeysSDK_GetKeyAuth_Call {
	_c.Call.Return(getKeyAuthResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuth_Call) RunAndReturn(run func(ctx context.Context, keyAuthID string, controlPlaneID string, opts ...operations.Option) (*operations.GetKeyAuthResponse, error)) *MockAPIKeysSDK_GetKeyAuth_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyAuthInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) GetKeyAuthInWorkspace(ctx context.Context, request operations.GetKeyAuthInWorkspaceRequest, opts ...operations.Option) (*operations.GetKeyAuthInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetKeyAuthInWorkspace")
	}

	var r0 *operations.GetKeyAuthInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetKeyAuthInWorkspaceRequest, ...operations.Option) (*operations.GetKeyAuthInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetKeyAuthInWorkspaceRequest, ...operations.Option) *operations.GetKeyAuthInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetKeyAuthInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.GetKeyAuthInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_GetKeyAuthInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyAuthInWorkspace'
type MockAPIKeysSDK_GetKeyAuthInWorkspace_Call struct {
	*mock.Call
}

// GetKeyAuthInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.GetKeyAuthInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) GetKeyAuthInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call {
	return &MockAPIKeysSDK_GetKeyAuthInWorkspace_Call{Call: _e.mock.On("GetKeyAuthInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call) Run(run func(ctx context.Context, request operations.GetKeyAuthInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.GetKeyAuthInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.GetKeyAuthInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call) Return(getKeyAuthInWorkspaceResponse *operations.GetKeyAuthInWorkspaceResponse, err error) *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call {
	_c.Call.Return(getKeyAuthInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.GetKeyAuthInWorkspaceRequest, opts ...operations.Option) (*operations.GetKeyAuthInWorkspaceResponse, error)) *MockAPIKeysSDK_GetKeyAuthInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyAuthWithConsumer provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) GetKeyAuthWithConsumer(ctx context.Context, request operations.GetKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.GetKeyAuthWithConsumerResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetKeyAuthWithConsumer")
	}

	var r0 *operations.GetKeyAuthWithConsumerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetKeyAuthWithConsumerRequest, ...operations.Option) (*operations.GetKeyAuthWithConsumerResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetKeyAuthWithConsumerRequest, ...operations.Option) *operations.GetKeyAuthWithConsumerResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetKeyAuthWithConsumerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.GetKeyAuthWithConsumerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_GetKeyAuthWithConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyAuthWithConsumer'
type MockAPIKeysSDK_GetKeyAuthWithConsumer_Call struct {
	*mock.Call
}

// GetKeyAuthWithConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.GetKeyAuthWithConsumerRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) GetKeyAuthWithConsumer(ctx any, request any, opts ...any) *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call {
	return &MockAPIKeysSDK_GetKeyAuthWithConsumer_Call{Call: _e.mock.On("GetKeyAuthWithConsumer",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call) Run(run func(ctx context.Context, request operations.GetKeyAuthWithConsumerRequest, opts ...operations.Option)) *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.GetKeyAuthWithConsumerRequest
		if args[1] != nil {
			arg1 = args[1].(operations.GetKeyAuthWithConsumerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call) Return(getKeyAuthWithConsumerResponse *operations.GetKeyAuthWithConsumerResponse, err error) *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call {
	_c.Call.Return(getKeyAuthWithConsumerResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call) RunAndReturn(run func(ctx context.Context, request operations.GetKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.GetKeyAuthWithConsumerResponse, error)) *MockAPIKeysSDK_GetKeyAuthWithConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyAuthWithConsumerInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) GetKeyAuthWithConsumerInWorkspace(ctx context.Context, request operations.GetKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.GetKeyAuthWithConsumerInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetKeyAuthWithConsumerInWorkspace")
	}

	var r0 *operations.GetKeyAuthWithConsumerInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) (*operations.GetKeyAuthWithConsumerInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) *operations.GetKeyAuthWithConsumerInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetKeyAuthWithConsumerInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.GetKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyAuthWithConsumerInWorkspace'
type MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call struct {
	*mock.Call
}

// GetKeyAuthWithConsumerInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.GetKeyAuthWithConsumerInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) GetKeyAuthWithConsumerInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call {
	return &MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call{Call: _e.mock.On("GetKeyAuthWithConsumerInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call) Run(run func(ctx context.Context, request operations.GetKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.GetKeyAuthWithConsumerInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.GetKeyAuthWithConsumerInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call) Return(getKeyAuthWithConsumerInWorkspaceResponse *operations.GetKeyAuthWithConsumerInWorkspaceResponse, err error) *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(getKeyAuthWithConsumerInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.GetKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.GetKeyAuthWithConsumerInWorkspaceResponse, error)) *MockAPIKeysSDK_GetKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyAuth provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) ListKeyAuth(ctx context.Context, request operations.ListKeyAuthRequest, opts ...operations.Option) (*operations.ListKeyAuthResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListKeyAuth")
	}

	var r0 *operations.ListKeyAuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthRequest, ...operations.Option) (*operations.ListKeyAuthResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthRequest, ...operations.Option) *operations.ListKeyAuthResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListKeyAuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListKeyAuthRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_ListKeyAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyAuth'
type MockAPIKeysSDK_ListKeyAuth_Call struct {
	*mock.Call
}

// ListKeyAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListKeyAuthRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) ListKeyAuth(ctx any, request any, opts ...any) *MockAPIKeysSDK_ListKeyAuth_Call {
	return &MockAPIKeysSDK_ListKeyAuth_Call{Call: _e.mock.On("ListKeyAuth",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_ListKeyAuth_Call) Run(run func(ctx context.Context, request operations.ListKeyAuthRequest, opts ...operations.Option)) *MockAPIKeysSDK_ListKeyAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListKeyAuthRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListKeyAuthRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuth_Call) Return(listKeyAuthResponse *operations.ListKeyAuthResponse, err error) *MockAPIKeysSDK_ListKeyAuth_Call {
	_c.Call.Return(listKeyAuthResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuth_Call) RunAndReturn(run func(ctx context.Context, request operations.ListKeyAuthRequest, opts ...operations.Option) (*operations.ListKeyAuthResponse, error)) *MockAPIKeysSDK_ListKeyAuth_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyAuthInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) ListKeyAuthInWorkspace(ctx context.Context, request operations.ListKeyAuthInWorkspaceRequest, opts ...operations.Option) (*operations.ListKeyAuthInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListKeyAuthInWorkspace")
	}

	var r0 *operations.ListKeyAuthInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthInWorkspaceRequest, ...operations.Option) (*operations.ListKeyAuthInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthInWorkspaceRequest, ...operations.Option) *operations.ListKeyAuthInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListKeyAuthInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListKeyAuthInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_ListKeyAuthInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyAuthInWorkspace'
type MockAPIKeysSDK_ListKeyAuthInWorkspace_Call struct {
	*mock.Call
}

// ListKeyAuthInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListKeyAuthInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) ListKeyAuthInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call {
	return &MockAPIKeysSDK_ListKeyAuthInWorkspace_Call{Call: _e.mock.On("ListKeyAuthInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call) Run(run func(ctx context.Context, request operations.ListKeyAuthInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListKeyAuthInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListKeyAuthInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call) Return(listKeyAuthInWorkspaceResponse *operations.ListKeyAuthInWorkspaceResponse, err error) *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call {
	_c.Call.Return(listKeyAuthInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.ListKeyAuthInWorkspaceRequest, opts ...operations.Option) (*operations.ListKeyAuthInWorkspaceResponse, error)) *MockAPIKeysSDK_ListKeyAuthInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyAuthWithConsumer provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) ListKeyAuthWithConsumer(ctx context.Context, request operations.ListKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.ListKeyAuthWithConsumerResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListKeyAuthWithConsumer")
	}

	var r0 *operations.ListKeyAuthWithConsumerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthWithConsumerRequest, ...operations.Option) (*operations.ListKeyAuthWithConsumerResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthWithConsumerRequest, ...operations.Option) *operations.ListKeyAuthWithConsumerResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListKeyAuthWithConsumerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListKeyAuthWithConsumerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_ListKeyAuthWithConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyAuthWithConsumer'
type MockAPIKeysSDK_ListKeyAuthWithConsumer_Call struct {
	*mock.Call
}

// ListKeyAuthWithConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListKeyAuthWithConsumerRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) ListKeyAuthWithConsumer(ctx any, request any, opts ...any) *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call {
	return &MockAPIKeysSDK_ListKeyAuthWithConsumer_Call{Call: _e.mock.On("ListKeyAuthWithConsumer",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call) Run(run func(ctx context.Context, request operations.ListKeyAuthWithConsumerRequest, opts ...operations.Option)) *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListKeyAuthWithConsumerRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListKeyAuthWithConsumerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call) Return(listKeyAuthWithConsumerResponse *operations.ListKeyAuthWithConsumerResponse, err error) *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call {
	_c.Call.Return(listKeyAuthWithConsumerResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call) RunAndReturn(run func(ctx context.Context, request operations.ListKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.ListKeyAuthWithConsumerResponse, error)) *MockAPIKeysSDK_ListKeyAuthWithConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeyAuthWithConsumerInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) ListKeyAuthWithConsumerInWorkspace(ctx context.Context, request operations.ListKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.ListKeyAuthWithConsumerInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListKeyAuthWithConsumerInWorkspace")
	}

	var r0 *operations.ListKeyAuthWithConsumerInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) (*operations.ListKeyAuthWithConsumerInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) *operations.ListKeyAuthWithConsumerInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListKeyAuthWithConsumerInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeyAuthWithConsumerInWorkspace'
type MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call struct {
	*mock.Call
}

// ListKeyAuthWithConsumerInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListKeyAuthWithConsumerInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) ListKeyAuthWithConsumerInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call {
	return &MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call{Call: _e.mock.On("ListKeyAuthWithConsumerInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call) Run(run func(ctx context.Context, request operations.ListKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListKeyAuthWithConsumerInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListKeyAuthWithConsumerInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call) Return(listKeyAuthWithConsumerInWorkspaceResponse *operations.ListKeyAuthWithConsumerInWorkspaceResponse, err error) *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(listKeyAuthWithConsumerInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.ListKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.ListKeyAuthWithConsumerInWorkspaceResponse, error)) *MockAPIKeysSDK_ListKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertKeyAuthWithConsumer provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) UpsertKeyAuthWithConsumer(ctx context.Context, request operations.UpsertKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.UpsertKeyAuthWithConsumerResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpsertKeyAuthWithConsumer")
	}

	var r0 *operations.UpsertKeyAuthWithConsumerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpsertKeyAuthWithConsumerRequest, ...operations.Option) (*operations.UpsertKeyAuthWithConsumerResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpsertKeyAuthWithConsumerRequest, ...operations.Option) *operations.UpsertKeyAuthWithConsumerResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpsertKeyAuthWithConsumerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpsertKeyAuthWithConsumerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertKeyAuthWithConsumer'
type MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call struct {
	*mock.Call
}

// UpsertKeyAuthWithConsumer is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.UpsertKeyAuthWithConsumerRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) UpsertKeyAuthWithConsumer(ctx any, request any, opts ...any) *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call {
	return &MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call{Call: _e.mock.On("UpsertKeyAuthWithConsumer",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call) Run(run func(ctx context.Context, request operations.UpsertKeyAuthWithConsumerRequest, opts ...operations.Option)) *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpsertKeyAuthWithConsumerRequest
		if args[1] != nil {
			arg1 = args[1].(operations.UpsertKeyAuthWithConsumerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call) Return(upsertKeyAuthWithConsumerResponse *operations.UpsertKeyAuthWithConsumerResponse, err error) *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call {
	_c.Call.Return(upsertKeyAuthWithConsumerResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call) RunAndReturn(run func(ctx context.Context, request operations.UpsertKeyAuthWithConsumerRequest, opts ...operations.Option) (*operations.UpsertKeyAuthWithConsumerResponse, error)) *MockAPIKeysSDK_UpsertKeyAuthWithConsumer_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertKeyAuthWithConsumerInWorkspace provides a mock function for the type MockAPIKeysSDK
func (_mock *MockAPIKeysSDK) UpsertKeyAuthWithConsumerInWorkspace(ctx context.Context, request operations.UpsertKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.UpsertKeyAuthWithConsumerInWorkspaceResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpsertKeyAuthWithConsumerInWorkspace")
	}

	var r0 *operations.UpsertKeyAuthWithConsumerInWorkspaceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpsertKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) (*operations.UpsertKeyAuthWithConsumerInWorkspaceResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpsertKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) *operations.UpsertKeyAuthWithConsumerInWorkspaceResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpsertKeyAuthWithConsumerInWorkspaceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpsertKeyAuthWithConsumerInWorkspaceRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertKeyAuthWithConsumerInWorkspace'
type MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call struct {
	*mock.Call
}

// UpsertKeyAuthWithConsumerInWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.UpsertKeyAuthWithConsumerInWorkspaceRequest
//   - opts ...operations.Option
func (_e *MockAPIKeysSDK_Expecter) UpsertKeyAuthWithConsumerInWorkspace(ctx any, request any, opts ...any) *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call {
	return &MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call{Call: _e.mock.On("UpsertKeyAuthWithConsumerInWorkspace",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call) Run(run func(ctx context.Context, request operations.UpsertKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option)) *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpsertKeyAuthWithConsumerInWorkspaceRequest
		if args[1] != nil {
			arg1 = args[1].(operations.UpsertKeyAuthWithConsumerInWorkspaceRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call) Return(upsertKeyAuthWithConsumerInWorkspaceResponse *operations.UpsertKeyAuthWithConsumerInWorkspaceResponse, err error) *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(upsertKeyAuthWithConsumerInWorkspaceResponse, err)
	return _c
}

func (_c *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call) RunAndReturn(run func(ctx context.Context, request operations.UpsertKeyAuthWithConsumerInWorkspaceRequest, opts ...operations.Option) (*operations.UpsertKeyAuthWithConsumerInWorkspaceResponse, error)) *MockAPIKeysSDK_UpsertKeyAuthWithConsumerInWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
