// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManagedSystemAccountsRolesSDK creates a new instance of MockManagedSystemAccountsRolesSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagedSystemAccountsRolesSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagedSystemAccountsRolesSDK {
	mock := &MockManagedSystemAccountsRolesSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManagedSystemAccountsRolesSDK is an autogenerated mock type for the ManagedSystemAccountsRolesSDK type
type MockManagedSystemAccountsRolesSDK struct {
	mock.Mock
}

type MockManagedSystemAccountsRolesSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagedSystemAccountsRolesSDK) EXPECT() *MockManagedSystemAccountsRolesSDK_Expecter {
	return &MockManagedSystemAccountsRolesSDK_Expecter{mock: &_m.Mock}
}

// CreateSystemAccountsAssignedRolesInternal provides a mock function for the type MockManagedSystemAccountsRolesSDK
func (_mock *MockManagedSystemAccountsRolesSDK) CreateSystemAccountsAssignedRolesInternal(ctx context.Context, accountID string, assignParameterizedRole *components.AssignParameterizedRole, opts ...operations.Option) (*operations.CreateSystemAccountsAssignedRolesInternalResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accountID, assignParameterizedRole, opts)
	} else {
		tmpRet = _mock.Called(ctx, accountID, assignParameterizedRole)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateSystemAccountsAssignedRolesInternal")
	}

	var r0 *operations.CreateSystemAccountsAssignedRolesInternalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *components.AssignParameterizedRole, ...operations.Option) (*operations.CreateSystemAccountsAssignedRolesInternalResponse, error)); ok {
		return returnFunc(ctx, accountID, assignParameterizedRole, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *components.AssignParameterizedRole, ...operations.Option) *operations.CreateSystemAccountsAssignedRolesInternalResponse); ok {
		r0 = returnFunc(ctx, accountID, assignParameterizedRole, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateSystemAccountsAssignedRolesInternalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *components.AssignParameterizedRole, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, accountID, assignParameterizedRole, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSystemAccountsAssignedRolesInternal'
type MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call struct {
	*mock.Call
}

// CreateSystemAccountsAssignedRolesInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - assignParameterizedRole *components.AssignParameterizedRole
//   - opts ...operations.Option
func (_e *MockManagedSystemAccountsRolesSDK_Expecter) CreateSystemAccountsAssignedRolesInternal(ctx any, accountID any, assignParameterizedRole any, opts ...any) *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call {
	return &MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call{Call: _e.mock.On("CreateSystemAccountsAssignedRolesInternal",
		append([]any{ctx, accountID, assignParameterizedRole}, opts...)...)}
}

func (_c *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call) Run(run func(ctx context.Context, accountID string, assignParameterizedRole *components.AssignParameterizedRole, opts ...operations.Option)) *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *components.AssignParameterizedRole
		if args[2] != nil {
			arg2 = args[2].(*components.AssignParameterizedRole)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call) Return(createSystemAccountsAssignedRolesInternalResponse *operations.CreateSystemAccountsAssignedRolesInternalResponse, err error) *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call {
	_c.Call.Return(createSystemAccountsAssignedRolesInternalResponse, err)
	return _c
}

func (_c *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call) RunAndReturn(run func(ctx context.Context, accountID string, assignParameterizedRole *components.AssignParameterizedRole, opts ...operations.Option) (*operations.CreateSystemAccountsAssignedRolesInternalResponse, error)) *MockManagedSystemAccountsRolesSDK_CreateSystemAccountsAssignedRolesInternal_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemAccountsAssignedRolesInternal provides a mock function for the type MockManagedSystemAccountsRolesSDK
func (_mock *MockManagedSystemAccountsRolesSDK) GetSystemAccountsAssignedRolesInternal(ctx context.Context, accountID string, filter *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter, opts ...operations.Option) (*operations.GetSystemAccountsAssignedRolesInternalResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, accountID, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, accountID, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSystemAccountsAssignedRolesInternal")
	}

	var r0 *operations.GetSystemAccountsAssignedRolesInternalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter, ...operations.Option) (*operations.GetSystemAccountsAssignedRolesInternalResponse, error)); ok {
		return returnFunc(ctx, accountID, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter, ...operations.Option) *operations.GetSystemAccountsAssignedRolesInternalResponse); ok {
		r0 = returnFunc(ctx, accountID, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetSystemAccountsAssignedRolesInternalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, accountID, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemAccountsAssignedRolesInternal'
type MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call struct {
	*mock.Call
}

// GetSystemAccountsAssignedRolesInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - filter *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter
//   - opts ...operations.Option
func (_e *MockManagedSystemAccountsRolesSDK_Expecter) GetSystemAccountsAssignedRolesInternal(ctx any, accountID any, filter any, opts ...any) *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call {
	return &MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call{Call: _e.mock.On("GetSystemAccountsAssignedRolesInternal",
		append([]any{ctx, accountID, filter}, opts...)...)}
}

func (_c *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call) Run(run func(ctx context.Context, accountID string, filter *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter, opts ...operations.Option)) *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter
		if args[2] != nil {
			arg2 = args[2].(*operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call) Return(getSystemAccountsAssignedRolesInternalResponse *operations.GetSystemAccountsAssignedRolesInternalResponse, err error) *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call {
	_c.Call.Return(getSystemAccountsAssignedRolesInternalResponse, err)
	return _c
}

func (_c *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call) RunAndReturn(run func(ctx context.Context, accountID string, filter *operations.GetSystemAccountsAssignedRolesInternalQueryParamFilter, opts ...operations.Option) (*operations.GetSystemAccountsAssignedRolesInternalResponse, error)) *MockManagedSystemAccountsRolesSDK_GetSystemAccountsAssignedRolesInternal_Call {
	_c.Call.Return(run)
	return _c
}
