// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPServersSDK creates a new instance of MockMCPServersSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPServersSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPServersSDK {
	mock := &MockMCPServersSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPServersSDK is an autogenerated mock type for the MCPServersSDK type
type MockMCPServersSDK struct {
	mock.Mock
}

type MockMCPServersSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPServersSDK) EXPECT() *MockMCPServersSDK_Expecter {
	return &MockMCPServersSDK_Expecter{mock: &_m.Mock}
}

// CreateMcpServerConfig provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) CreateMcpServerConfig(ctx context.Context, request components.CreateMCPServerRequest, opts ...operations.Option) (*operations.CreateMcpServerConfigResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateMcpServerConfig")
	}

	var r0 *operations.CreateMcpServerConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.CreateMCPServerRequest, ...operations.Option) (*operations.CreateMcpServerConfigResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, components.CreateMCPServerRequest, ...operations.Option) *operations.CreateMcpServerConfigResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateMcpServerConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, components.CreateMCPServerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_CreateMcpServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMcpServerConfig'
type MockMCPServersSDK_CreateMcpServerConfig_Call struct {
	*mock.Call
}

// CreateMcpServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - request components.CreateMCPServerRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) CreateMcpServerConfig(ctx any, request any, opts ...any) *MockMCPServersSDK_CreateMcpServerConfig_Call {
	return &MockMCPServersSDK_CreateMcpServerConfig_Call{Call: _e.mock.On("CreateMcpServerConfig",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockMCPServersSDK_CreateMcpServerConfig_Call) Run(run func(ctx context.Context, request components.CreateMCPServerRequest, opts ...operations.Option)) *MockMCPServersSDK_CreateMcpServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 components.CreateMCPServerRequest
		if args[1] != nil {
			arg1 = args[1].(components.CreateMCPServerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_CreateMcpServerConfig_Call) Return(createMcpServerConfigResponse *operations.CreateMcpServerConfigResponse, err error) *MockMCPServersSDK_CreateMcpServerConfig_Call {
	_c.Call.Return(createMcpServerConfigResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_CreateMcpServerConfig_Call) RunAndReturn(run func(ctx context.Context, request components.CreateMCPServerRequest, opts ...operations.Option) (*operations.CreateMcpServerConfigResponse, error)) *MockMCPServersSDK_CreateMcpServerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMcpServerConfig provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) DeleteMcpServerConfig(ctx context.Context, mcpServerID string, opts ...operations.Option) (*operations.DeleteMcpServerConfigResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, mcpServerID, opts)
	} else {
		tmpRet = _mock.Called(ctx, mcpServerID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMcpServerConfig")
	}

	var r0 *operations.DeleteMcpServerConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.DeleteMcpServerConfigResponse, error)); ok {
		return returnFunc(ctx, mcpServerID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.DeleteMcpServerConfigResponse); ok {
		r0 = returnFunc(ctx, mcpServerID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteMcpServerConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, mcpServerID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_DeleteMcpServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMcpServerConfig'
type MockMCPServersSDK_DeleteMcpServerConfig_Call struct {
	*mock.Call
}

// DeleteMcpServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - mcpServerID string
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) DeleteMcpServerConfig(ctx any, mcpServerID any, opts ...any) *MockMCPServersSDK_DeleteMcpServerConfig_Call {
	return &MockMCPServersSDK_DeleteMcpServerConfig_Call{Call: _e.mock.On("DeleteMcpServerConfig",
		append([]any{ctx, mcpServerID}, opts...)...)}
}

func (_c *MockMCPServersSDK_DeleteMcpServerConfig_Call) Run(run func(ctx context.Context, mcpServerID string, opts ...operations.Option)) *MockMCPServersSDK_DeleteMcpServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_DeleteMcpServerConfig_Call) Return(deleteMcpServerConfigResponse *operations.DeleteMcpServerConfigResponse, err error) *MockMCPServersSDK_DeleteMcpServerConfig_Call {
	_c.Call.Return(deleteMcpServerConfigResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_DeleteMcpServerConfig_Call) RunAndReturn(run func(ctx context.Context, mcpServerID string, opts ...operations.Option) (*operations.DeleteMcpServerConfigResponse, error)) *MockMCPServersSDK_DeleteMcpServerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetMcpServerByControlPlane provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) GetMcpServerByControlPlane(ctx context.Context, controlPlaneID string, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerByControlPlaneResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, controlPlaneID, mcpServerID, opts)
	} else {
		tmpRet = _mock.Called(ctx, controlPlaneID, mcpServerID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMcpServerByControlPlane")
	}

	var r0 *operations.GetMcpServerByControlPlaneResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) (*operations.GetMcpServerByControlPlaneResponse, error)); ok {
		return returnFunc(ctx, controlPlaneID, mcpServerID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) *operations.GetMcpServerByControlPlaneResponse); ok {
		r0 = returnFunc(ctx, controlPlaneID, mcpServerID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetMcpServerByControlPlaneResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, controlPlaneID, mcpServerID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_GetMcpServerByControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMcpServerByControlPlane'
type MockMCPServersSDK_GetMcpServerByControlPlane_Call struct {
	*mock.Call
}

// GetMcpServerByControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - controlPlaneID string
//   - mcpServerID string
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) GetMcpServerByControlPlane(ctx any, controlPlaneID any, mcpServerID any, opts ...any) *MockMCPServersSDK_GetMcpServerByControlPlane_Call {
	return &MockMCPServersSDK_GetMcpServerByControlPlane_Call{Call: _e.mock.On("GetMcpServerByControlPlane",
		append([]any{ctx, controlPlaneID, mcpServerID}, opts...)...)}
}

func (_c *MockMCPServersSDK_GetMcpServerByControlPlane_Call) Run(run func(ctx context.Context, controlPlaneID string, mcpServerID string, opts ...operations.Option)) *MockMCPServersSDK_GetMcpServerByControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerByControlPlane_Call) Return(getMcpServerByControlPlaneResponse *operations.GetMcpServerByControlPlaneResponse, err error) *MockMCPServersSDK_GetMcpServerByControlPlane_Call {
	_c.Call.Return(getMcpServerByControlPlaneResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerByControlPlane_Call) RunAndReturn(run func(ctx context.Context, controlPlaneID string, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerByControlPlaneResponse, error)) *MockMCPServersSDK_GetMcpServerByControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetMcpServerCode provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) GetMcpServerCode(ctx context.Context, controlPlaneID string, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerCodeResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, controlPlaneID, mcpServerID, opts)
	} else {
		tmpRet = _mock.Called(ctx, controlPlaneID, mcpServerID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMcpServerCode")
	}

	var r0 *operations.GetMcpServerCodeResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) (*operations.GetMcpServerCodeResponse, error)); ok {
		return returnFunc(ctx, controlPlaneID, mcpServerID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) *operations.GetMcpServerCodeResponse); ok {
		r0 = returnFunc(ctx, controlPlaneID, mcpServerID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetMcpServerCodeResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, controlPlaneID, mcpServerID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_GetMcpServerCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMcpServerCode'
type MockMCPServersSDK_GetMcpServerCode_Call struct {
	*mock.Call
}

// GetMcpServerCode is a helper method to define mock.On call
//   - ctx context.Context
//   - controlPlaneID string
//   - mcpServerID string
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) GetMcpServerCode(ctx any, controlPlaneID any, mcpServerID any, opts ...any) *MockMCPServersSDK_GetMcpServerCode_Call {
	return &MockMCPServersSDK_GetMcpServerCode_Call{Call: _e.mock.On("GetMcpServerCode",
		append([]any{ctx, controlPlaneID, mcpServerID}, opts...)...)}
}

func (_c *MockMCPServersSDK_GetMcpServerCode_Call) Run(run func(ctx context.Context, controlPlaneID string, mcpServerID string, opts ...operations.Option)) *MockMCPServersSDK_GetMcpServerCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerCode_Call) Return(getMcpServerCodeResponse *operations.GetMcpServerCodeResponse, err error) *MockMCPServersSDK_GetMcpServerCode_Call {
	_c.Call.Return(getMcpServerCodeResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerCode_Call) RunAndReturn(run func(ctx context.Context, controlPlaneID string, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerCodeResponse, error)) *MockMCPServersSDK_GetMcpServerCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetMcpServerConfig provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) GetMcpServerConfig(ctx context.Context, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerConfigResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, mcpServerID, opts)
	} else {
		tmpRet = _mock.Called(ctx, mcpServerID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMcpServerConfig")
	}

	var r0 *operations.GetMcpServerConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.GetMcpServerConfigResponse, error)); ok {
		return returnFunc(ctx, mcpServerID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.GetMcpServerConfigResponse); ok {
		r0 = returnFunc(ctx, mcpServerID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetMcpServerConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, mcpServerID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_GetMcpServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMcpServerConfig'
type MockMCPServersSDK_GetMcpServerConfig_Call struct {
	*mock.Call
}

// GetMcpServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - mcpServerID string
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) GetMcpServerConfig(ctx any, mcpServerID any, opts ...any) *MockMCPServersSDK_GetMcpServerConfig_Call {
	return &MockMCPServersSDK_GetMcpServerConfig_Call{Call: _e.mock.On("GetMcpServerConfig",
		append([]any{ctx, mcpServerID}, opts...)...)}
}

func (_c *MockMCPServersSDK_GetMcpServerConfig_Call) Run(run func(ctx context.Context, mcpServerID string, opts ...operations.Option)) *MockMCPServersSDK_GetMcpServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerConfig_Call) Return(getMcpServerConfigResponse *operations.GetMcpServerConfigResponse, err error) *MockMCPServersSDK_GetMcpServerConfig_Call {
	_c.Call.Return(getMcpServerConfigResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerConfig_Call) RunAndReturn(run func(ctx context.Context, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerConfigResponse, error)) *MockMCPServersSDK_GetMcpServerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetMcpServerKongEntities provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) GetMcpServerKongEntities(ctx context.Context, request operations.GetMcpServerKongEntitiesRequest, opts ...operations.Option) (*operations.GetMcpServerKongEntitiesResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMcpServerKongEntities")
	}

	var r0 *operations.GetMcpServerKongEntitiesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetMcpServerKongEntitiesRequest, ...operations.Option) (*operations.GetMcpServerKongEntitiesResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.GetMcpServerKongEntitiesRequest, ...operations.Option) *operations.GetMcpServerKongEntitiesResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetMcpServerKongEntitiesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.GetMcpServerKongEntitiesRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_GetMcpServerKongEntities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMcpServerKongEntities'
type MockMCPServersSDK_GetMcpServerKongEntities_Call struct {
	*mock.Call
}

// GetMcpServerKongEntities is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.GetMcpServerKongEntitiesRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) GetMcpServerKongEntities(ctx any, request any, opts ...any) *MockMCPServersSDK_GetMcpServerKongEntities_Call {
	return &MockMCPServersSDK_GetMcpServerKongEntities_Call{Call: _e.mock.On("GetMcpServerKongEntities",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockMCPServersSDK_GetMcpServerKongEntities_Call) Run(run func(ctx context.Context, request operations.GetMcpServerKongEntitiesRequest, opts ...operations.Option)) *MockMCPServersSDK_GetMcpServerKongEntities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.GetMcpServerKongEntitiesRequest
		if args[1] != nil {
			arg1 = args[1].(operations.GetMcpServerKongEntitiesRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerKongEntities_Call) Return(getMcpServerKongEntitiesResponse *operations.GetMcpServerKongEntitiesResponse, err error) *MockMCPServersSDK_GetMcpServerKongEntities_Call {
	_c.Call.Return(getMcpServerKongEntitiesResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerKongEntities_Call) RunAndReturn(run func(ctx context.Context, request operations.GetMcpServerKongEntitiesRequest, opts ...operations.Option) (*operations.GetMcpServerKongEntitiesResponse, error)) *MockMCPServersSDK_GetMcpServerKongEntities_Call {
	_c.Call.Return(run)
	return _c
}

// GetMcpServerSignals provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) GetMcpServerSignals(ctx context.Context, controlPlaneID string, capabilities *components.MCPCapabilitiesMap, opts ...operations.Option) (*operations.GetMcpServerSignalsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, controlPlaneID, capabilities, opts)
	} else {
		tmpRet = _mock.Called(ctx, controlPlaneID, capabilities)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMcpServerSignals")
	}

	var r0 *operations.GetMcpServerSignalsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *components.MCPCapabilitiesMap, ...operations.Option) (*operations.GetMcpServerSignalsResponse, error)); ok {
		return returnFunc(ctx, controlPlaneID, capabilities, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *components.MCPCapabilitiesMap, ...operations.Option) *operations.GetMcpServerSignalsResponse); ok {
		r0 = returnFunc(ctx, controlPlaneID, capabilities, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetMcpServerSignalsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *components.MCPCapabilitiesMap, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, controlPlaneID, capabilities, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_GetMcpServerSignals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMcpServerSignals'
type MockMCPServersSDK_GetMcpServerSignals_Call struct {
	*mock.Call
}

// GetMcpServerSignals is a helper method to define mock.On call
//   - ctx context.Context
//   - controlPlaneID string
//   - capabilities *components.MCPCapabilitiesMap
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) GetMcpServerSignals(ctx any, controlPlaneID any, capabilities any, opts ...any) *MockMCPServersSDK_GetMcpServerSignals_Call {
	return &MockMCPServersSDK_GetMcpServerSignals_Call{Call: _e.mock.On("GetMcpServerSignals",
		append([]any{ctx, controlPlaneID, capabilities}, opts...)...)}
}

func (_c *MockMCPServersSDK_GetMcpServerSignals_Call) Run(run func(ctx context.Context, controlPlaneID string, capabilities *components.MCPCapabilitiesMap, opts ...operations.Option)) *MockMCPServersSDK_GetMcpServerSignals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *components.MCPCapabilitiesMap
		if args[2] != nil {
			arg2 = args[2].(*components.MCPCapabilitiesMap)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerSignals_Call) Return(getMcpServerSignalsResponse *operations.GetMcpServerSignalsResponse, err error) *MockMCPServersSDK_GetMcpServerSignals_Call {
	_c.Call.Return(getMcpServerSignalsResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerSignals_Call) RunAndReturn(run func(ctx context.Context, controlPlaneID string, capabilities *components.MCPCapabilitiesMap, opts ...operations.Option) (*operations.GetMcpServerSignalsResponse, error)) *MockMCPServersSDK_GetMcpServerSignals_Call {
	_c.Call.Return(run)
	return _c
}

// GetMcpServerStatus provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) GetMcpServerStatus(ctx context.Context, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerStatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, mcpServerID, opts)
	} else {
		tmpRet = _mock.Called(ctx, mcpServerID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMcpServerStatus")
	}

	var r0 *operations.GetMcpServerStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.GetMcpServerStatusResponse, error)); ok {
		return returnFunc(ctx, mcpServerID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.GetMcpServerStatusResponse); ok {
		r0 = returnFunc(ctx, mcpServerID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetMcpServerStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, mcpServerID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_GetMcpServerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMcpServerStatus'
type MockMCPServersSDK_GetMcpServerStatus_Call struct {
	*mock.Call
}

// GetMcpServerStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - mcpServerID string
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) GetMcpServerStatus(ctx any, mcpServerID any, opts ...any) *MockMCPServersSDK_GetMcpServerStatus_Call {
	return &MockMCPServersSDK_GetMcpServerStatus_Call{Call: _e.mock.On("GetMcpServerStatus",
		append([]any{ctx, mcpServerID}, opts...)...)}
}

func (_c *MockMCPServersSDK_GetMcpServerStatus_Call) Run(run func(ctx context.Context, mcpServerID string, opts ...operations.Option)) *MockMCPServersSDK_GetMcpServerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerStatus_Call) Return(getMcpServerStatusResponse *operations.GetMcpServerStatusResponse, err error) *MockMCPServersSDK_GetMcpServerStatus_Call {
	_c.Call.Return(getMcpServerStatusResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_GetMcpServerStatus_Call) RunAndReturn(run func(ctx context.Context, mcpServerID string, opts ...operations.Option) (*operations.GetMcpServerStatusResponse, error)) *MockMCPServersSDK_GetMcpServerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListMcpServerConfigs provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) ListMcpServerConfigs(ctx context.Context, request operations.ListMcpServerConfigsRequest, opts ...operations.Option) (*operations.ListMcpServerConfigsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListMcpServerConfigs")
	}

	var r0 *operations.ListMcpServerConfigsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListMcpServerConfigsRequest, ...operations.Option) (*operations.ListMcpServerConfigsResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListMcpServerConfigsRequest, ...operations.Option) *operations.ListMcpServerConfigsResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListMcpServerConfigsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListMcpServerConfigsRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_ListMcpServerConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMcpServerConfigs'
type MockMCPServersSDK_ListMcpServerConfigs_Call struct {
	*mock.Call
}

// ListMcpServerConfigs is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListMcpServerConfigsRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) ListMcpServerConfigs(ctx any, request any, opts ...any) *MockMCPServersSDK_ListMcpServerConfigs_Call {
	return &MockMCPServersSDK_ListMcpServerConfigs_Call{Call: _e.mock.On("ListMcpServerConfigs",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockMCPServersSDK_ListMcpServerConfigs_Call) Run(run func(ctx context.Context, request operations.ListMcpServerConfigsRequest, opts ...operations.Option)) *MockMCPServersSDK_ListMcpServerConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListMcpServerConfigsRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListMcpServerConfigsRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_ListMcpServerConfigs_Call) Return(listMcpServerConfigsResponse *operations.ListMcpServerConfigsResponse, err error) *MockMCPServersSDK_ListMcpServerConfigs_Call {
	_c.Call.Return(listMcpServerConfigsResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_ListMcpServerConfigs_Call) RunAndReturn(run func(ctx context.Context, request operations.ListMcpServerConfigsRequest, opts ...operations.Option) (*operations.ListMcpServerConfigsResponse, error)) *MockMCPServersSDK_ListMcpServerConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// ListMcpServersByControlPlane provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) ListMcpServersByControlPlane(ctx context.Context, request operations.ListMcpServersByControlPlaneRequest, opts ...operations.Option) (*operations.ListMcpServersByControlPlaneResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListMcpServersByControlPlane")
	}

	var r0 *operations.ListMcpServersByControlPlaneResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListMcpServersByControlPlaneRequest, ...operations.Option) (*operations.ListMcpServersByControlPlaneResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListMcpServersByControlPlaneRequest, ...operations.Option) *operations.ListMcpServersByControlPlaneResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListMcpServersByControlPlaneResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListMcpServersByControlPlaneRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_ListMcpServersByControlPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMcpServersByControlPlane'
type MockMCPServersSDK_ListMcpServersByControlPlane_Call struct {
	*mock.Call
}

// ListMcpServersByControlPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListMcpServersByControlPlaneRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) ListMcpServersByControlPlane(ctx any, request any, opts ...any) *MockMCPServersSDK_ListMcpServersByControlPlane_Call {
	return &MockMCPServersSDK_ListMcpServersByControlPlane_Call{Call: _e.mock.On("ListMcpServersByControlPlane",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockMCPServersSDK_ListMcpServersByControlPlane_Call) Run(run func(ctx context.Context, request operations.ListMcpServersByControlPlaneRequest, opts ...operations.Option)) *MockMCPServersSDK_ListMcpServersByControlPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListMcpServersByControlPlaneRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListMcpServersByControlPlaneRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_ListMcpServersByControlPlane_Call) Return(listMcpServersByControlPlaneResponse *operations.ListMcpServersByControlPlaneResponse, err error) *MockMCPServersSDK_ListMcpServersByControlPlane_Call {
	_c.Call.Return(listMcpServersByControlPlaneResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_ListMcpServersByControlPlane_Call) RunAndReturn(run func(ctx context.Context, request operations.ListMcpServersByControlPlaneRequest, opts ...operations.Option) (*operations.ListMcpServersByControlPlaneResponse, error)) *MockMCPServersSDK_ListMcpServersByControlPlane_Call {
	_c.Call.Return(run)
	return _c
}

// PatchMcpServerConfig provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) PatchMcpServerConfig(ctx context.Context, mcpServerID string, patchMCPServerRequest components.PatchMCPServerRequest, opts ...operations.Option) (*operations.PatchMcpServerConfigResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, mcpServerID, patchMCPServerRequest, opts)
	} else {
		tmpRet = _mock.Called(ctx, mcpServerID, patchMCPServerRequest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PatchMcpServerConfig")
	}

	var r0 *operations.PatchMcpServerConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.PatchMCPServerRequest, ...operations.Option) (*operations.PatchMcpServerConfigResponse, error)); ok {
		return returnFunc(ctx, mcpServerID, patchMCPServerRequest, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.PatchMCPServerRequest, ...operations.Option) *operations.PatchMcpServerConfigResponse); ok {
		r0 = returnFunc(ctx, mcpServerID, patchMCPServerRequest, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PatchMcpServerConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, components.PatchMCPServerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, mcpServerID, patchMCPServerRequest, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_PatchMcpServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchMcpServerConfig'
type MockMCPServersSDK_PatchMcpServerConfig_Call struct {
	*mock.Call
}

// PatchMcpServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - mcpServerID string
//   - patchMCPServerRequest components.PatchMCPServerRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) PatchMcpServerConfig(ctx any, mcpServerID any, patchMCPServerRequest any, opts ...any) *MockMCPServersSDK_PatchMcpServerConfig_Call {
	return &MockMCPServersSDK_PatchMcpServerConfig_Call{Call: _e.mock.On("PatchMcpServerConfig",
		append([]any{ctx, mcpServerID, patchMCPServerRequest}, opts...)...)}
}

func (_c *MockMCPServersSDK_PatchMcpServerConfig_Call) Run(run func(ctx context.Context, mcpServerID string, patchMCPServerRequest components.PatchMCPServerRequest, opts ...operations.Option)) *MockMCPServersSDK_PatchMcpServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 components.PatchMCPServerRequest
		if args[2] != nil {
			arg2 = args[2].(components.PatchMCPServerRequest)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_PatchMcpServerConfig_Call) Return(patchMcpServerConfigResponse *operations.PatchMcpServerConfigResponse, err error) *MockMCPServersSDK_PatchMcpServerConfig_Call {
	_c.Call.Return(patchMcpServerConfigResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_PatchMcpServerConfig_Call) RunAndReturn(run func(ctx context.Context, mcpServerID string, patchMCPServerRequest components.PatchMCPServerRequest, opts ...operations.Option) (*operations.PatchMcpServerConfigResponse, error)) *MockMCPServersSDK_PatchMcpServerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// PostMcpServerStatus provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) PostMcpServerStatus(ctx context.Context, request operations.PostMcpServerStatusRequest, opts ...operations.Option) (*operations.PostMcpServerStatusResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PostMcpServerStatus")
	}

	var r0 *operations.PostMcpServerStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.PostMcpServerStatusRequest, ...operations.Option) (*operations.PostMcpServerStatusResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.PostMcpServerStatusRequest, ...operations.Option) *operations.PostMcpServerStatusResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PostMcpServerStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.PostMcpServerStatusRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_PostMcpServerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostMcpServerStatus'
type MockMCPServersSDK_PostMcpServerStatus_Call struct {
	*mock.Call
}

// PostMcpServerStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.PostMcpServerStatusRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) PostMcpServerStatus(ctx any, request any, opts ...any) *MockMCPServersSDK_PostMcpServerStatus_Call {
	return &MockMCPServersSDK_PostMcpServerStatus_Call{Call: _e.mock.On("PostMcpServerStatus",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockMCPServersSDK_PostMcpServerStatus_Call) Run(run func(ctx context.Context, request operations.PostMcpServerStatusRequest, opts ...operations.Option)) *MockMCPServersSDK_PostMcpServerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.PostMcpServerStatusRequest
		if args[1] != nil {
			arg1 = args[1].(operations.PostMcpServerStatusRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_PostMcpServerStatus_Call) Return(postMcpServerStatusResponse *operations.PostMcpServerStatusResponse, err error) *MockMCPServersSDK_PostMcpServerStatus_Call {
	_c.Call.Return(postMcpServerStatusResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_PostMcpServerStatus_Call) RunAndReturn(run func(ctx context.Context, request operations.PostMcpServerStatusRequest, opts ...operations.Option) (*operations.PostMcpServerStatusResponse, error)) *MockMCPServersSDK_PostMcpServerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMcpServerConfig provides a mock function for the type MockMCPServersSDK
func (_mock *MockMCPServersSDK) UpdateMcpServerConfig(ctx context.Context, mcpServerID string, updateMCPServerRequest components.UpdateMCPServerRequest, opts ...operations.Option) (*operations.UpdateMcpServerConfigResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, mcpServerID, updateMCPServerRequest, opts)
	} else {
		tmpRet = _mock.Called(ctx, mcpServerID, updateMCPServerRequest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateMcpServerConfig")
	}

	var r0 *operations.UpdateMcpServerConfigResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.UpdateMCPServerRequest, ...operations.Option) (*operations.UpdateMcpServerConfigResponse, error)); ok {
		return returnFunc(ctx, mcpServerID, updateMCPServerRequest, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.UpdateMCPServerRequest, ...operations.Option) *operations.UpdateMcpServerConfigResponse); ok {
		r0 = returnFunc(ctx, mcpServerID, updateMCPServerRequest, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpdateMcpServerConfigResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, components.UpdateMCPServerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, mcpServerID, updateMCPServerRequest, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServersSDK_UpdateMcpServerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMcpServerConfig'
type MockMCPServersSDK_UpdateMcpServerConfig_Call struct {
	*mock.Call
}

// UpdateMcpServerConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - mcpServerID string
//   - updateMCPServerRequest components.UpdateMCPServerRequest
//   - opts ...operations.Option
func (_e *MockMCPServersSDK_Expecter) UpdateMcpServerConfig(ctx any, mcpServerID any, updateMCPServerRequest any, opts ...any) *MockMCPServersSDK_UpdateMcpServerConfig_Call {
	return &MockMCPServersSDK_UpdateMcpServerConfig_Call{Call: _e.mock.On("UpdateMcpServerConfig",
		append([]any{ctx, mcpServerID, updateMCPServerRequest}, opts...)...)}
}

func (_c *MockMCPServersSDK_UpdateMcpServerConfig_Call) Run(run func(ctx context.Context, mcpServerID string, updateMCPServerRequest components.UpdateMCPServerRequest, opts ...operations.Option)) *MockMCPServersSDK_UpdateMcpServerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 components.UpdateMCPServerRequest
		if args[2] != nil {
			arg2 = args[2].(components.UpdateMCPServerRequest)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockMCPServersSDK_UpdateMcpServerConfig_Call) Return(updateMcpServerConfigResponse *operations.UpdateMcpServerConfigResponse, err error) *MockMCPServersSDK_UpdateMcpServerConfig_Call {
	_c.Call.Return(updateMcpServerConfigResponse, err)
	return _c
}

func (_c *MockMCPServersSDK_UpdateMcpServerConfig_Call) RunAndReturn(run func(ctx context.Context, mcpServerID string, updateMCPServerRequest components.UpdateMCPServerRequest, opts ...operations.Option) (*operations.UpdateMcpServerConfigResponse, error)) *MockMCPServersSDK_UpdateMcpServerConfig_Call {
	_c.Call.Return(run)
	return _c
}
