// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCatalogAIModelSpecsSDK creates a new instance of MockCatalogAIModelSpecsSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogAIModelSpecsSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogAIModelSpecsSDK {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockCatalogAIModelSpecsSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockCatalogAIModelSpecsSDK is an autogenerated mock type for the CatalogAIModelSpecsSDK type
type MockCatalogAIModelSpecsSDK struct {
	mock.Mock
}

type MockCatalogAIModelSpecsSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogAIModelSpecsSDK) EXPECT() *MockCatalogAIModelSpecsSDK_Expecter {
	return &MockCatalogAIModelSpecsSDK_Expecter{mock: &_m.Mock}
}

// DeleteAiModelVersionSpec provides a mock function for the type MockCatalogAIModelSpecsSDK
func (_mock *MockCatalogAIModelSpecsSDK) DeleteAiModelVersionSpec(ctx context.Context, aiModelID string, opts ...operations.Option) (*operations.DeleteAiModelVersionSpecResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, aiModelID, opts)
	} else {
		tmpRet = _mock.Called(ctx, aiModelID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteAiModelVersionSpec")
	}

	var r0 *operations.DeleteAiModelVersionSpecResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.DeleteAiModelVersionSpecResponse, error)); ok {
		return returnFunc(ctx, aiModelID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.DeleteAiModelVersionSpecResponse); ok {
		r0 = returnFunc(ctx, aiModelID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteAiModelVersionSpecResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, aiModelID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAiModelVersionSpec'
type MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call struct {
	*mock.Call
}

// DeleteAiModelVersionSpec is a helper method to define mock.On call
//   - ctx context.Context
//   - aiModelID string
//   - opts ...operations.Option
func (_e *MockCatalogAIModelSpecsSDK_Expecter) DeleteAiModelVersionSpec(ctx any, aiModelID any, opts ...any) *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call {
	return &MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call{Call: _e.mock.On("DeleteAiModelVersionSpec",
		append([]any{ctx, aiModelID}, opts...)...)}
}

func (_c *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call) Run(run func(ctx context.Context, aiModelID string, opts ...operations.Option)) *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call) Return(deleteAiModelVersionSpecResponse *operations.DeleteAiModelVersionSpecResponse, err error) *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call {
	_c.Call.Return(deleteAiModelVersionSpecResponse, err)
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call) RunAndReturn(run func(ctx context.Context, aiModelID string, opts ...operations.Option) (*operations.DeleteAiModelVersionSpecResponse, error)) *MockCatalogAIModelSpecsSDK_DeleteAiModelVersionSpec_Call {
	_c.Call.Return(run)
	return _c
}

// GetAiModelSpec provides a mock function for the type MockCatalogAIModelSpecsSDK
func (_mock *MockCatalogAIModelSpecsSDK) GetAiModelSpec(ctx context.Context, aiModelID string, opts ...operations.Option) (*operations.GetAiModelSpecResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, aiModelID, opts)
	} else {
		tmpRet = _mock.Called(ctx, aiModelID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAiModelSpec")
	}

	var r0 *operations.GetAiModelSpecResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.GetAiModelSpecResponse, error)); ok {
		return returnFunc(ctx, aiModelID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.GetAiModelSpecResponse); ok {
		r0 = returnFunc(ctx, aiModelID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAiModelSpecResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, aiModelID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAiModelSpec'
type MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call struct {
	*mock.Call
}

// GetAiModelSpec is a helper method to define mock.On call
//   - ctx context.Context
//   - aiModelID string
//   - opts ...operations.Option
func (_e *MockCatalogAIModelSpecsSDK_Expecter) GetAiModelSpec(ctx any, aiModelID any, opts ...any) *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call {
	return &MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call{Call: _e.mock.On("GetAiModelSpec",
		append([]any{ctx, aiModelID}, opts...)...)}
}

func (_c *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call) Run(run func(ctx context.Context, aiModelID string, opts ...operations.Option)) *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call) Return(getAiModelSpecResponse *operations.GetAiModelSpecResponse, err error) *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call {
	_c.Call.Return(getAiModelSpecResponse, err)
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call) RunAndReturn(run func(ctx context.Context, aiModelID string, opts ...operations.Option) (*operations.GetAiModelSpecResponse, error)) *MockCatalogAIModelSpecsSDK_GetAiModelSpec_Call {
	_c.Call.Return(run)
	return _c
}

// GetAiModelVersionSpec provides a mock function for the type MockCatalogAIModelSpecsSDK
func (_mock *MockCatalogAIModelSpecsSDK) GetAiModelVersionSpec(ctx context.Context, aiModelID string, opts ...operations.Option) (*operations.GetAiModelVersionSpecResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, aiModelID, opts)
	} else {
		tmpRet = _mock.Called(ctx, aiModelID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAiModelVersionSpec")
	}

	var r0 *operations.GetAiModelVersionSpecResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.GetAiModelVersionSpecResponse, error)); ok {
		return returnFunc(ctx, aiModelID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.GetAiModelVersionSpecResponse); ok {
		r0 = returnFunc(ctx, aiModelID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAiModelVersionSpecResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, aiModelID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAiModelVersionSpec'
type MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call struct {
	*mock.Call
}

// GetAiModelVersionSpec is a helper method to define mock.On call
//   - ctx context.Context
//   - aiModelID string
//   - opts ...operations.Option
func (_e *MockCatalogAIModelSpecsSDK_Expecter) GetAiModelVersionSpec(ctx any, aiModelID any, opts ...any) *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call {
	return &MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call{Call: _e.mock.On("GetAiModelVersionSpec",
		append([]any{ctx, aiModelID}, opts...)...)}
}

func (_c *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call) Run(run func(ctx context.Context, aiModelID string, opts ...operations.Option)) *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call) Return(getAiModelVersionSpecResponse *operations.GetAiModelVersionSpecResponse, err error) *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call {
	_c.Call.Return(getAiModelVersionSpecResponse, err)
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call) RunAndReturn(run func(ctx context.Context, aiModelID string, opts ...operations.Option) (*operations.GetAiModelVersionSpecResponse, error)) *MockCatalogAIModelSpecsSDK_GetAiModelVersionSpec_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAiModelVersionSpec provides a mock function for the type MockCatalogAIModelSpecsSDK
func (_mock *MockCatalogAIModelSpecsSDK) UpsertAiModelVersionSpec(ctx context.Context, aiModelID string, aiModelVersionSpecWrite components.AiModelVersionSpecWrite, opts ...operations.Option) (*operations.UpsertAiModelVersionSpecResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, aiModelID, aiModelVersionSpecWrite, opts)
	} else {
		tmpRet = _mock.Called(ctx, aiModelID, aiModelVersionSpecWrite)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpsertAiModelVersionSpec")
	}

	var r0 *operations.UpsertAiModelVersionSpecResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.AiModelVersionSpecWrite, ...operations.Option) (*operations.UpsertAiModelVersionSpecResponse, error)); ok {
		return returnFunc(ctx, aiModelID, aiModelVersionSpecWrite, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.AiModelVersionSpecWrite, ...operations.Option) *operations.UpsertAiModelVersionSpecResponse); ok {
		r0 = returnFunc(ctx, aiModelID, aiModelVersionSpecWrite, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpsertAiModelVersionSpecResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, components.AiModelVersionSpecWrite, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, aiModelID, aiModelVersionSpecWrite, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAiModelVersionSpec'
type MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call struct {
	*mock.Call
}

// UpsertAiModelVersionSpec is a helper method to define mock.On call
//   - ctx context.Context
//   - aiModelID string
//   - aiModelVersionSpecWrite components.AiModelVersionSpecWrite
//   - opts ...operations.Option
func (_e *MockCatalogAIModelSpecsSDK_Expecter) UpsertAiModelVersionSpec(ctx any, aiModelID any, aiModelVersionSpecWrite any, opts ...any) *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call {
	return &MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call{Call: _e.mock.On("UpsertAiModelVersionSpec",
		append([]any{ctx, aiModelID, aiModelVersionSpecWrite}, opts...)...)}
}

func (_c *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call) Run(run func(ctx context.Context, aiModelID string, aiModelVersionSpecWrite components.AiModelVersionSpecWrite, opts ...operations.Option)) *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 components.AiModelVersionSpecWrite
		if args[2] != nil {
			arg2 = args[2].(components.AiModelVersionSpecWrite)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call) Return(upsertAiModelVersionSpecResponse *operations.UpsertAiModelVersionSpecResponse, err error) *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call {
	_c.Call.Return(upsertAiModelVersionSpecResponse, err)
	return _c
}

func (_c *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call) RunAndReturn(run func(ctx context.Context, aiModelID string, aiModelVersionSpecWrite components.AiModelVersionSpecWrite, opts ...operations.Option) (*operations.UpsertAiModelVersionSpecResponse, error)) *MockCatalogAIModelSpecsSDK_UpsertAiModelVersionSpec_Call {
	_c.Call.Return(run)
	return _c
}
