// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAIGatewayModelsSDK creates a new instance of MockAIGatewayModelsSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIGatewayModelsSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIGatewayModelsSDK {
	mock := &MockAIGatewayModelsSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAIGatewayModelsSDK is an autogenerated mock type for the AIGatewayModelsSDK type
type MockAIGatewayModelsSDK struct {
	mock.Mock
}

type MockAIGatewayModelsSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIGatewayModelsSDK) EXPECT() *MockAIGatewayModelsSDK_Expecter {
	return &MockAIGatewayModelsSDK_Expecter{mock: &_m.Mock}
}

// CreateAiGatewayModel provides a mock function for the type MockAIGatewayModelsSDK
func (_mock *MockAIGatewayModelsSDK) CreateAiGatewayModel(ctx context.Context, gatewayID string, createAIGatewayModelRequest components.CreateAIGatewayModelRequest, opts ...operations.Option) (*operations.CreateAiGatewayModelResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, gatewayID, createAIGatewayModelRequest, opts)
	} else {
		tmpRet = _mock.Called(ctx, gatewayID, createAIGatewayModelRequest)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateAiGatewayModel")
	}

	var r0 *operations.CreateAiGatewayModelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.CreateAIGatewayModelRequest, ...operations.Option) (*operations.CreateAiGatewayModelResponse, error)); ok {
		return returnFunc(ctx, gatewayID, createAIGatewayModelRequest, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, components.CreateAIGatewayModelRequest, ...operations.Option) *operations.CreateAiGatewayModelResponse); ok {
		r0 = returnFunc(ctx, gatewayID, createAIGatewayModelRequest, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.CreateAiGatewayModelResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, components.CreateAIGatewayModelRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, gatewayID, createAIGatewayModelRequest, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIGatewayModelsSDK_CreateAiGatewayModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAiGatewayModel'
type MockAIGatewayModelsSDK_CreateAiGatewayModel_Call struct {
	*mock.Call
}

// CreateAiGatewayModel is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
//   - createAIGatewayModelRequest components.CreateAIGatewayModelRequest
//   - opts ...operations.Option
func (_e *MockAIGatewayModelsSDK_Expecter) CreateAiGatewayModel(ctx any, gatewayID any, createAIGatewayModelRequest any, opts ...any) *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call {
	return &MockAIGatewayModelsSDK_CreateAiGatewayModel_Call{Call: _e.mock.On("CreateAiGatewayModel",
		append([]any{ctx, gatewayID, createAIGatewayModelRequest}, opts...)...)}
}

func (_c *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call) Run(run func(ctx context.Context, gatewayID string, createAIGatewayModelRequest components.CreateAIGatewayModelRequest, opts ...operations.Option)) *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 components.CreateAIGatewayModelRequest
		if args[2] != nil {
			arg2 = args[2].(components.CreateAIGatewayModelRequest)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call) Return(createAiGatewayModelResponse *operations.CreateAiGatewayModelResponse, err error) *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call {
	_c.Call.Return(createAiGatewayModelResponse, err)
	return _c
}

func (_c *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call) RunAndReturn(run func(ctx context.Context, gatewayID string, createAIGatewayModelRequest components.CreateAIGatewayModelRequest, opts ...operations.Option) (*operations.CreateAiGatewayModelResponse, error)) *MockAIGatewayModelsSDK_CreateAiGatewayModel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAiGatewayModel provides a mock function for the type MockAIGatewayModelsSDK
func (_mock *MockAIGatewayModelsSDK) DeleteAiGatewayModel(ctx context.Context, gatewayID string, modelIDOrName string, opts ...operations.Option) (*operations.DeleteAiGatewayModelResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, gatewayID, modelIDOrName, opts)
	} else {
		tmpRet = _mock.Called(ctx, gatewayID, modelIDOrName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteAiGatewayModel")
	}

	var r0 *operations.DeleteAiGatewayModelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) (*operations.DeleteAiGatewayModelResponse, error)); ok {
		return returnFunc(ctx, gatewayID, modelIDOrName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) *operations.DeleteAiGatewayModelResponse); ok {
		r0 = returnFunc(ctx, gatewayID, modelIDOrName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.DeleteAiGatewayModelResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, gatewayID, modelIDOrName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAiGatewayModel'
type MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call struct {
	*mock.Call
}

// DeleteAiGatewayModel is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
//   - modelIDOrName string
//   - opts ...operations.Option
func (_e *MockAIGatewayModelsSDK_Expecter) DeleteAiGatewayModel(ctx any, gatewayID any, modelIDOrName any, opts ...any) *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call {
	return &MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call{Call: _e.mock.On("DeleteAiGatewayModel",
		append([]any{ctx, gatewayID, modelIDOrName}, opts...)...)}
}

func (_c *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call) Run(run func(ctx context.Context, gatewayID string, modelIDOrName string, opts ...operations.Option)) *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call) Return(deleteAiGatewayModelResponse *operations.DeleteAiGatewayModelResponse, err error) *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call {
	_c.Call.Return(deleteAiGatewayModelResponse, err)
	return _c
}

func (_c *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call) RunAndReturn(run func(ctx context.Context, gatewayID string, modelIDOrName string, opts ...operations.Option) (*operations.DeleteAiGatewayModelResponse, error)) *MockAIGatewayModelsSDK_DeleteAiGatewayModel_Call {
	_c.Call.Return(run)
	return _c
}

// GetAiGatewayModel provides a mock function for the type MockAIGatewayModelsSDK
func (_mock *MockAIGatewayModelsSDK) GetAiGatewayModel(ctx context.Context, gatewayID string, modelIDOrName string, opts ...operations.Option) (*operations.GetAiGatewayModelResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, gatewayID, modelIDOrName, opts)
	} else {
		tmpRet = _mock.Called(ctx, gatewayID, modelIDOrName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAiGatewayModel")
	}

	var r0 *operations.GetAiGatewayModelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) (*operations.GetAiGatewayModelResponse, error)); ok {
		return returnFunc(ctx, gatewayID, modelIDOrName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...operations.Option) *operations.GetAiGatewayModelResponse); ok {
		r0 = returnFunc(ctx, gatewayID, modelIDOrName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAiGatewayModelResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, gatewayID, modelIDOrName, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIGatewayModelsSDK_GetAiGatewayModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAiGatewayModel'
type MockAIGatewayModelsSDK_GetAiGatewayModel_Call struct {
	*mock.Call
}

// GetAiGatewayModel is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
//   - modelIDOrName string
//   - opts ...operations.Option
func (_e *MockAIGatewayModelsSDK_Expecter) GetAiGatewayModel(ctx any, gatewayID any, modelIDOrName any, opts ...any) *MockAIGatewayModelsSDK_GetAiGatewayModel_Call {
	return &MockAIGatewayModelsSDK_GetAiGatewayModel_Call{Call: _e.mock.On("GetAiGatewayModel",
		append([]any{ctx, gatewayID, modelIDOrName}, opts...)...)}
}

func (_c *MockAIGatewayModelsSDK_GetAiGatewayModel_Call) Run(run func(ctx context.Context, gatewayID string, modelIDOrName string, opts ...operations.Option)) *MockAIGatewayModelsSDK_GetAiGatewayModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 3 {
			variadicArgs = args[3].([]operations.Option)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockAIGatewayModelsSDK_GetAiGatewayModel_Call) Return(getAiGatewayModelResponse *operations.GetAiGatewayModelResponse, err error) *MockAIGatewayModelsSDK_GetAiGatewayModel_Call {
	_c.Call.Return(getAiGatewayModelResponse, err)
	return _c
}

func (_c *MockAIGatewayModelsSDK_GetAiGatewayModel_Call) RunAndReturn(run func(ctx context.Context, gatewayID string, modelIDOrName string, opts ...operations.Option) (*operations.GetAiGatewayModelResponse, error)) *MockAIGatewayModelsSDK_GetAiGatewayModel_Call {
	_c.Call.Return(run)
	return _c
}

// ListAiGatewayModels provides a mock function for the type MockAIGatewayModelsSDK
func (_mock *MockAIGatewayModelsSDK) ListAiGatewayModels(ctx context.Context, request operations.ListAiGatewayModelsRequest, opts ...operations.Option) (*operations.ListAiGatewayModelsResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListAiGatewayModels")
	}

	var r0 *operations.ListAiGatewayModelsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListAiGatewayModelsRequest, ...operations.Option) (*operations.ListAiGatewayModelsResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.ListAiGatewayModelsRequest, ...operations.Option) *operations.ListAiGatewayModelsResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ListAiGatewayModelsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.ListAiGatewayModelsRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIGatewayModelsSDK_ListAiGatewayModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAiGatewayModels'
type MockAIGatewayModelsSDK_ListAiGatewayModels_Call struct {
	*mock.Call
}

// ListAiGatewayModels is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.ListAiGatewayModelsRequest
//   - opts ...operations.Option
func (_e *MockAIGatewayModelsSDK_Expecter) ListAiGatewayModels(ctx any, request any, opts ...any) *MockAIGatewayModelsSDK_ListAiGatewayModels_Call {
	return &MockAIGatewayModelsSDK_ListAiGatewayModels_Call{Call: _e.mock.On("ListAiGatewayModels",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAIGatewayModelsSDK_ListAiGatewayModels_Call) Run(run func(ctx context.Context, request operations.ListAiGatewayModelsRequest, opts ...operations.Option)) *MockAIGatewayModelsSDK_ListAiGatewayModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.ListAiGatewayModelsRequest
		if args[1] != nil {
			arg1 = args[1].(operations.ListAiGatewayModelsRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAIGatewayModelsSDK_ListAiGatewayModels_Call) Return(listAiGatewayModelsResponse *operations.ListAiGatewayModelsResponse, err error) *MockAIGatewayModelsSDK_ListAiGatewayModels_Call {
	_c.Call.Return(listAiGatewayModelsResponse, err)
	return _c
}

func (_c *MockAIGatewayModelsSDK_ListAiGatewayModels_Call) RunAndReturn(run func(ctx context.Context, request operations.ListAiGatewayModelsRequest, opts ...operations.Option) (*operations.ListAiGatewayModelsResponse, error)) *MockAIGatewayModelsSDK_ListAiGatewayModels_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAiGatewayModel provides a mock function for the type MockAIGatewayModelsSDK
func (_mock *MockAIGatewayModelsSDK) UpdateAiGatewayModel(ctx context.Context, request operations.UpdateAiGatewayModelRequest, opts ...operations.Option) (*operations.UpdateAiGatewayModelResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateAiGatewayModel")
	}

	var r0 *operations.UpdateAiGatewayModelResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateAiGatewayModelRequest, ...operations.Option) (*operations.UpdateAiGatewayModelResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, operations.UpdateAiGatewayModelRequest, ...operations.Option) *operations.UpdateAiGatewayModelResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.UpdateAiGatewayModelResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, operations.UpdateAiGatewayModelRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAiGatewayModel'
type MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call struct {
	*mock.Call
}

// UpdateAiGatewayModel is a helper method to define mock.On call
//   - ctx context.Context
//   - request operations.UpdateAiGatewayModelRequest
//   - opts ...operations.Option
func (_e *MockAIGatewayModelsSDK_Expecter) UpdateAiGatewayModel(ctx any, request any, opts ...any) *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call {
	return &MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call{Call: _e.mock.On("UpdateAiGatewayModel",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call) Run(run func(ctx context.Context, request operations.UpdateAiGatewayModelRequest, opts ...operations.Option)) *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 operations.UpdateAiGatewayModelRequest
		if args[1] != nil {
			arg1 = args[1].(operations.UpdateAiGatewayModelRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call) Return(updateAiGatewayModelResponse *operations.UpdateAiGatewayModelResponse, err error) *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call {
	_c.Call.Return(updateAiGatewayModelResponse, err)
	return _c
}

func (_c *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call) RunAndReturn(run func(ctx context.Context, request operations.UpdateAiGatewayModelRequest, opts ...operations.Option) (*operations.UpdateAiGatewayModelResponse, error)) *MockAIGatewayModelsSDK_UpdateAiGatewayModel_Call {
	_c.Call.Return(run)
	return _c
}
