// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAwsSDK creates a new instance of MockAwsSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAwsSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAwsSDK {
	mock := &MockAwsSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAwsSDK is an autogenerated mock type for the AwsSDK type
type MockAwsSDK struct {
	mock.Mock
}

type MockAwsSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAwsSDK) EXPECT() *MockAwsSDK_Expecter {
	return &MockAwsSDK_Expecter{mock: &_m.Mock}
}

// ResolveCustomer provides a mock function for the type MockAwsSDK
func (_mock *MockAwsSDK) ResolveCustomer(ctx context.Context, request *components.AWSResolveCustomerRequest, opts ...operations.Option) (*operations.ResolveCustomerResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ResolveCustomer")
	}

	var r0 *operations.ResolveCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *components.AWSResolveCustomerRequest, ...operations.Option) (*operations.ResolveCustomerResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *components.AWSResolveCustomerRequest, ...operations.Option) *operations.ResolveCustomerResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.ResolveCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *components.AWSResolveCustomerRequest, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAwsSDK_ResolveCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCustomer'
type MockAwsSDK_ResolveCustomer_Call struct {
	*mock.Call
}

// ResolveCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - request *components.AWSResolveCustomerRequest
//   - opts ...operations.Option
func (_e *MockAwsSDK_Expecter) ResolveCustomer(ctx any, request any, opts ...any) *MockAwsSDK_ResolveCustomer_Call {
	return &MockAwsSDK_ResolveCustomer_Call{Call: _e.mock.On("ResolveCustomer",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockAwsSDK_ResolveCustomer_Call) Run(run func(ctx context.Context, request *components.AWSResolveCustomerRequest, opts ...operations.Option)) *MockAwsSDK_ResolveCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *components.AWSResolveCustomerRequest
		if args[1] != nil {
			arg1 = args[1].(*components.AWSResolveCustomerRequest)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAwsSDK_ResolveCustomer_Call) Return(resolveCustomerResponse *operations.ResolveCustomerResponse, err error) *MockAwsSDK_ResolveCustomer_Call {
	_c.Call.Return(resolveCustomerResponse, err)
	return _c
}

func (_c *MockAwsSDK_ResolveCustomer_Call) RunAndReturn(run func(ctx context.Context, request *components.AWSResolveCustomerRequest, opts ...operations.Option) (*operations.ResolveCustomerResponse, error)) *MockAwsSDK_ResolveCustomer_Call {
	_c.Call.Return(run)
	return _c
}
