// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAIGatewayDebugSDK creates a new instance of MockAIGatewayDebugSDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIGatewayDebugSDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIGatewayDebugSDK {
	mock := &MockAIGatewayDebugSDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAIGatewayDebugSDK is an autogenerated mock type for the AIGatewayDebugSDK type
type MockAIGatewayDebugSDK struct {
	mock.Mock
}

type MockAIGatewayDebugSDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIGatewayDebugSDK) EXPECT() *MockAIGatewayDebugSDK_Expecter {
	return &MockAIGatewayDebugSDK_Expecter{mock: &_m.Mock}
}

// GetAiGatewayDebugCpOutput provides a mock function for the type MockAIGatewayDebugSDK
func (_mock *MockAIGatewayDebugSDK) GetAiGatewayDebugCpOutput(ctx context.Context, gatewayID string, opts ...operations.Option) (*operations.GetAiGatewayDebugCpOutputResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, gatewayID, opts)
	} else {
		tmpRet = _mock.Called(ctx, gatewayID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAiGatewayDebugCpOutput")
	}

	var r0 *operations.GetAiGatewayDebugCpOutputResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) (*operations.GetAiGatewayDebugCpOutputResponse, error)); ok {
		return returnFunc(ctx, gatewayID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...operations.Option) *operations.GetAiGatewayDebugCpOutputResponse); ok {
		r0 = returnFunc(ctx, gatewayID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAiGatewayDebugCpOutputResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, gatewayID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAiGatewayDebugCpOutput'
type MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call struct {
	*mock.Call
}

// GetAiGatewayDebugCpOutput is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayID string
//   - opts ...operations.Option
func (_e *MockAIGatewayDebugSDK_Expecter) GetAiGatewayDebugCpOutput(ctx any, gatewayID any, opts ...any) *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call {
	return &MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call{Call: _e.mock.On("GetAiGatewayDebugCpOutput",
		append([]any{ctx, gatewayID}, opts...)...)}
}

func (_c *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call) Run(run func(ctx context.Context, gatewayID string, opts ...operations.Option)) *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call) Return(getAiGatewayDebugCpOutputResponse *operations.GetAiGatewayDebugCpOutputResponse, err error) *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call {
	_c.Call.Return(getAiGatewayDebugCpOutputResponse, err)
	return _c
}

func (_c *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call) RunAndReturn(run func(ctx context.Context, gatewayID string, opts ...operations.Option) (*operations.GetAiGatewayDebugCpOutputResponse, error)) *MockAIGatewayDebugSDK_GetAiGatewayDebugCpOutput_Call {
	_c.Call.Return(run)
	return _c
}
