// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Kong/sdk-konnect-go/models/components"
	"github.com/Kong/sdk-konnect-go/models/operations"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSSOAuth0SDK creates a new instance of MockSSOAuth0SDK. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSOAuth0SDK(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSOAuth0SDK {
	mock := &MockSSOAuth0SDK{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSSOAuth0SDK is an autogenerated mock type for the SSOAuth0SDK type
type MockSSOAuth0SDK struct {
	mock.Mock
}

type MockSSOAuth0SDK_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSOAuth0SDK) EXPECT() *MockSSOAuth0SDK_Expecter {
	return &MockSSOAuth0SDK_Expecter{mock: &_m.Mock}
}

// GetAuth0OrganizationsInternal provides a mock function for the type MockSSOAuth0SDK
func (_mock *MockSSOAuth0SDK) GetAuth0OrganizationsInternal(ctx context.Context, opts ...operations.Option) (*operations.GetAuth0OrganizationsInternalResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAuth0OrganizationsInternal")
	}

	var r0 *operations.GetAuth0OrganizationsInternalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...operations.Option) (*operations.GetAuth0OrganizationsInternalResponse, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...operations.Option) *operations.GetAuth0OrganizationsInternalResponse); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.GetAuth0OrganizationsInternalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuth0OrganizationsInternal'
type MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call struct {
	*mock.Call
}

// GetAuth0OrganizationsInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...operations.Option
func (_e *MockSSOAuth0SDK_Expecter) GetAuth0OrganizationsInternal(ctx any, opts ...any) *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call {
	return &MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call{Call: _e.mock.On("GetAuth0OrganizationsInternal",
		append([]any{ctx}, opts...)...)}
}

func (_c *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call) Run(run func(ctx context.Context, opts ...operations.Option)) *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]operations.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call) Return(getAuth0OrganizationsInternalResponse *operations.GetAuth0OrganizationsInternalResponse, err error) *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call {
	_c.Call.Return(getAuth0OrganizationsInternalResponse, err)
	return _c
}

func (_c *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call) RunAndReturn(run func(ctx context.Context, opts ...operations.Option) (*operations.GetAuth0OrganizationsInternalResponse, error)) *MockSSOAuth0SDK_GetAuth0OrganizationsInternal_Call {
	_c.Call.Return(run)
	return _c
}

// PostAuth0RegisterInternal provides a mock function for the type MockSSOAuth0SDK
func (_mock *MockSSOAuth0SDK) PostAuth0RegisterInternal(ctx context.Context, request *components.Auth0Registration, opts ...operations.Option) (*operations.PostAuth0RegisterInternalResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, request, opts)
	} else {
		tmpRet = _mock.Called(ctx, request)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PostAuth0RegisterInternal")
	}

	var r0 *operations.PostAuth0RegisterInternalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *components.Auth0Registration, ...operations.Option) (*operations.PostAuth0RegisterInternalResponse, error)); ok {
		return returnFunc(ctx, request, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *components.Auth0Registration, ...operations.Option) *operations.PostAuth0RegisterInternalResponse); ok {
		r0 = returnFunc(ctx, request, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*operations.PostAuth0RegisterInternalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *components.Auth0Registration, ...operations.Option) error); ok {
		r1 = returnFunc(ctx, request, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSSOAuth0SDK_PostAuth0RegisterInternal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAuth0RegisterInternal'
type MockSSOAuth0SDK_PostAuth0RegisterInternal_Call struct {
	*mock.Call
}

// PostAuth0RegisterInternal is a helper method to define mock.On call
//   - ctx context.Context
//   - request *components.Auth0Registration
//   - opts ...operations.Option
func (_e *MockSSOAuth0SDK_Expecter) PostAuth0RegisterInternal(ctx any, request any, opts ...any) *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call {
	return &MockSSOAuth0SDK_PostAuth0RegisterInternal_Call{Call: _e.mock.On("PostAuth0RegisterInternal",
		append([]any{ctx, request}, opts...)...)}
}

func (_c *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call) Run(run func(ctx context.Context, request *components.Auth0Registration, opts ...operations.Option)) *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *components.Auth0Registration
		if args[1] != nil {
			arg1 = args[1].(*components.Auth0Registration)
		}
		var arg2 []operations.Option
		var variadicArgs []operations.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]operations.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call) Return(postAuth0RegisterInternalResponse *operations.PostAuth0RegisterInternalResponse, err error) *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call {
	_c.Call.Return(postAuth0RegisterInternalResponse, err)
	return _c
}

func (_c *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call) RunAndReturn(run func(ctx context.Context, request *components.Auth0Registration, opts ...operations.Option) (*operations.PostAuth0RegisterInternalResponse, error)) *MockSSOAuth0SDK_PostAuth0RegisterInternal_Call {
	_c.Call.Return(run)
	return _c
}
