name: Generate SDK

on:
  workflow_call:

jobs:
  generate:
    permissions:
      contents: write
    runs-on:
      - ubuntu-latest
    steps:
      - name: Install Speakeasy
        uses: mheap/setup-go-cli@v1
        with:
          owner: speakeasy-api
          repo: speakeasy
          cli_name: speakeasy
          package_type: zip

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: jdx/mise-action@v2
        with:
          install: false

      - name: Generate SDK
        run: make generate.sdk
        env:
          SPEAKEASYAPIKEY: ${{ secrets.SPEAKEASY_API_KEY }}

      - name: Commit SDK changes to the PR
        uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actions
          message: Update provider based on openapi.yaml changes
