name: Ensure generated interfaces and mocks are up to date
run-name: generate interfaces and mocks, branch:${{ github.ref_name }}, triggered by @${{ github.actor }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    types:
    - opened
    - synchronize

permissions:
  contents: read

env:
  MISE_VERBOSE: 1

jobs:
  verify-diff:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout current repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          install: false

      - name: Generate interfaces
        run: make generate.interfaces

      - name: Generate mocks
        run: make generate.mocks

      - name: Verify no diff
        run: make verify.diff

